### ISSUE TITLE
Spesifikasjonsteksten bør inneholde opphavsrettslig status og bruksvilkår

### ISSUE THREAD

**Issue by petterreinholdtsen** [arkivverket/noark5-tjenestegrensesnitt-standard#1]
Dette er en kopi av mangelmelding sendt inn til Arkivverket, se også https://github.com/petterreinholdtsen/noark5-tester/blob/master/mangelmelding/sendt/2017-03-16-bruksvilkaar.md .

 ------------------  ---------------------------------
           Prosjekt  Noark 5 Tjenestegresesnitt
           Kategori  Versjon 1.0 beta
        Alvorlighet  protest
       Meldingstype  utelatt
    Brukerreferanse  pere@hungry.com
        Dokumentdel  Innhold
         Sidenummer  6
        Linjenummer  n/a
    Innsendingsdato  2017-03-16
 ------------------  ---------------------------------

Beskrivelse
-----------

Det er uklart om spesifikasjonsdokumentet for NOARK 5 Tjenestegresesnitt er vernet etter åndsverkslovens bestemmelser eller om det er omfavnet av et av unntakene i åndsverkslovens § 9.

De som tar spesifikasjonen i bruk kan dermed risikere at Riksarkivet som rettighetsinnehaver for spesifikasjonen og assosiert materiale kan kreve erstatning for uberettiget bruk av opphavsrettslig beskyttet materiale som er underlagt rettighetshaverens enerett.

Selv om Riksarkivet per dags dato ikke krever at det betales vederlag for bruk av standarden så betyr det ikke at det vil forbli slik i framtiden.  Dette er en risiko spesielt en fri programvare-implementasjon av spesifikasjonen må ta hensyn til, ettersom utnyttelsen/spredning av programvaren ikke er noe utviklerne
kontrollerer.

Utviklerne løper da en potensiell risiko at det kreves vederlag betaling for instanser som utviklere har ingen kontroll over. 

Denne problemstillingen omfatter både Norsk arkivstandard (NOARK-5), metadatakatalogene, tjenestegrensesnittet, XSD-filer og andre tekniske ressurser, dvs.  i hovedsak det som er tilgjengelig fra http://arkivverket.no/arkivverket/Offentleg-forvalting/Noark/Noark-5

Det er viktig å sikre at det ikke kan oppstå en situasjon slik Skolelinux-prosjektet opplevde da de ønsket å bruke norsk standard kontoplan (NS 4102) i fri programvaresystemet SQL Ledger og [ble
nektet av Pronorm AS i brev datert 2004-01-05](http://developer.skolelinux.org/brev/2004-01-10-ufri_norsk_standard.pdf). Dette på tross av at lov og forskrift krever at regnskapsstandarden brukes når en rapporterer regnskap til Skattemyndighet og Brønnøysundsregistrene.

Hvis spesifikasjonen er vernet etter åndsverksloven så bør det velges og dokumenteres bruksvilkår slik at alle som ønsker å bruke standarden vet hva som gjelder.  En bør velge godt kjente bruksvilkår egnet for tekster og dokumentasjon, slik som de fra Creative Commons.  Det bør ikke formuleres en ny type bruksvilkår, da det gir merarbeide og utgifter til jurister for de som vurderer å bruke spesifikasjonen når
de må vurdere et helt nytt sett med avtalevilkår som få har vurdert før.

Gitt formuleringen i åndsverkslovens § 9 antar jeg at dokumentet ikke er vernet, men det hadde vært veldig fint om det var klart skrevet ned om forfattere og utgiver av spesifikasjonsteksten er enig i den
vurderingen.

Forslaget om at dokumenet kommer inn under åndsverkslovens § 9 er understøttet av «Bruk av åpne IT-standarder og åpen kildekode i offentlig sektor» avgitt til Moderniseringsdepartementet 2005-06-21, der seksjon «4.3 Utfordringer knyttet til offentlig innhold» sier:

> «Lov om opphavsrett til åndsverk m.v. omhandler opphavsrett til
> verk. I utgangspunktet er offentlige verk (dvs. dokumenter etc.)
> uten vern etter denne lov, jf.  §9.  Dette gjelder uavhengig av om
> dokumentet (verket) foreligger i digital eller analog form.»

Ønsket endring
--------------

Legg inn nytt avsnitt mellom punkt 1.6 (Prosjektets organisering) og 1.7 (Endringslogg), der en klargjør åndsverksmessig status.  Jeg foreslår noe slikt:

> Denne spesifikasjonen faller inn under unntakene i åndsverkslovens §
> 9, og er ikke opphavsrettslig vernet.

Hvis Riksarkivet derimot mener spesifikasjonsteksten *er* vernet av åndsverksloven, så foreslår jeg at dokumentetet erklærer at bruksvilkårene er i tråd med [Cretive Commons CC0 1.0](https://creativecommons.org/publicdomain/zero/1.0/deed.no) og legger inn en formulering ala dette:

> Riksarkivet har, i den utstrekning loven tillater, erklært at dette
> dokumentet er i det fri ved å si fra seg alle de opphavsrettigheter
> og nærstående rettigheter som de hadde til verket.
>
> Du kan kopiere, endre, distribuere og fremføre verket, selv for
> kommersielle formål, uten å spørre om tillatelse i tråd med
> vilkårene beskrevet i [Cretive Commons CC0
> 1.0](https://creativecommons.org/publicdomain/zero/1.0/deed.no).

**Comment by oivkru** [comment]
Noark 5-standarden og tjenestegrensesnittspesifikasjonen er offentlige dokument etter offentlighetsloven, og da kommer § 7 til anvendelse: 

§ 7.Bruk av offentleg informasjon
Informasjon som det er gitt tilgang til etter lova her eller anna lovgiving som gir ålmenta rett til innsyn i offentleg verksemd, kan brukast til eitkvart formål dersom ikkje anna lovgiving eller retten til ein tredjeperson er til hinder for det.

Det er ikke noe annet lovverk eller tredjepersons rettigheter som er til hinder for gjenbruk. I åndsverkloven kommer standarden inn under unntaket i § 9. Vi har aldri sett dette som en aktuell problemstilling, det er så selvsagt at dette er et offentlig dokument.

**Comment by petterreinholdtsen** [comment]
Det var bra å høre.  Da oppdaterer jeg spesifikasjonen med aktuelt forslag.
