### ISSUE TITLE
Hva betyr «Tag»-feltet i tabellene over relasjonsnøkler?

### ISSUE THREAD

**Issue by petterreinholdtsen** [arkivverket/noark5-tjenestegrensesnitt-standard#102]
Dette er en mangelmelding som kun er registrert på github, og ikke er sendt inn til Arkivverkets postmottak. Se også https://github.com/petterreinholdtsen/noark5-tester/blob/master/mangelmelding/sendt/2019-04-04-rest-rel.md .

 ------------------  ---------------------------------
           Prosjekt  Noark 5
           Kategori  Versjon 4.0
        Alvorlighet  kommentar
       Meldingstype  utelatt
    Brukerreferanse  pere@hungry.com>
        Dokumentdel  7.2.1.1 (Arkiv)
         Sidenummer  57
        Linjenummer  n/a
    Innsendingsdato  2019-04-04
 ------------------  ---------------------------------

Denne teksten er del av en samling innspill til Noark5-standarden
tilgjengelig fra
[https://github.com/petterreinholdtsen/noark5-tester/](https://github.com/petterreinholdtsen/noark5-tester/).

Beskrivelse
-----------

Dette gjelder 75 tabeller fra side 57 til side 265.

Samtlige tabeller over relasjonsnøkler i kapittel 7 har et «Tag»-felt med verdi «REST_REL» eller «codeList».  Det er ingen forklaring i spesifikasjonen hva dette feltet betyr, ei heller hva verdien «REST_REL» og «codeList» står for.  Jeg ser ikke at dette feltet bidrar med opplysninger som leseren trenger. Kan det være en ide å droppe «Tag»-feltet?

I dag er det ikke eksplisitt beskrevet hvilken relasjonsnøkkel som skal brukes til hvilken relasjon i en entitet.  Kan det også være en ide å endre på struktur og format for tabellene over relasjoner og relasjonsnøkler slik at det er helt entydig hvilke nøkler som skal brukes hvor?  Det er vel helst en annen mangelmelding.

Ønsket endring
--------------

Fjern «Tag»-feltet fra alle tabeller over relasjonsnøkler.  Erstatt det med et «Beskrivelse»-felt etter Verdi-kolonnen som kan brukes til å forklare hvordan hver nøkkel skal brukes.  Endre navn på «Verdi»-feltet til «Relasjonsnøkkel».

**Comment by petterreinholdtsen** [comment]
I og med at ingen, på en måned, har forklaret hva Tag-feltet skal bety, vil jeg lage endringsforslag som tar det bort fra alle tabellene.

Dagens tabeller har følgende verdier i denne kolonnen:

| Verdi            | Antall |
|-------------|--------|
| REST\_REL | 196 |
| codeList       | 35 |
| LOV             | 1 |

Referansen til LOV er i beskrivelsen av Personidentifikator, der det henvises til personopplysningsloven hos lovdata.no.  Jeg tror det er mer fornuftig å flytte denne lenken til den tekstlige beskrivelse.

**Comment by petterreinholdtsen** [comment]
Etter #167 trenger denne en oppdatering.  Det hadde vært veldig fint å få vite om endringen er OK før jeg bruker mer tid på å oppdatere den.

**Comment by AnnKnu** [comment]
@petterreinholdtsen  fjern tag felt, når du har gjort andre opptateringer.
