### ISSUE TITLE
UML-diagrammet over BevaringOgKassasjon mangler linker mellom entitetene

### ISSUE THREAD

**Issue by petterreinholdtsen** [arkivverket/noark5-tjenestegrensesnitt-standard#109]
Dette er en mangelmelding som kun er registrert på github, og ikke er sendt inn til Arkivverkets postmottak. Se også https://github.com/petterreinholdtsen/noark5-tester/blob/master/mangelmelding/sendt/2019-04-07-uml-bevaring-linker.md .

 ------------------  ---------------------------------
           Prosjekt  Noark 5 Tjenestegresesnitt
           Kategori  Versjon 1.0 beta
        Alvorlighet  kommentar
       Meldingstype  utelatt
    Brukerreferanse  pere@hungry.com
        Dokumentdel  7.2.1 (Arkivstruktur)
         Sidenummer  40
        Linjenummer  n/a
    Innsendingsdato  2019-04-07
 ------------------  ---------------------------------

Denne teksten er del av en samling innspill til Noark5-standarden tilgjengelig fra [https://github.com/petterreinholdtsen/noark5-tester/](https://github.com/petterreinholdtsen/noark5-tester/).

Beskrivelse
-----------

UML-Diagrammet på side 40 med tittel "BevaringOgKassasjon - (diagram)" mangler lenker mellom entitetene.  Dette bør legges til for å gjøre diagrammet enklere å lese.  De aktuelle lenkene er beskrevet i andre UML-diagrammer og i entitetsbeskrivelsen i kapittel 7.

Det kan kanskje også være en idé å legge lenker mellom kodelistene og der de er i bruk?  Det er forresten en idé som også gjelder alle de andre UML-diagrammene.

Ønsket endring
--------------

Legg inn aktuelle lenker i diagrammet.

Når diagrammer som PlantUML er tatt i bruk i master-grenen ([mangelmelding #76](https://github.com/arkivverket/noark5-tjenestegrensesnitt-standard/issues/76)), så skal jeg sende inn konkret endringsforslag for å fikse dette.

**Comment by monadani** [comment]
27/06/2019 tas med høsten 2019, versjon 2.0
