### ISSUE TITLE
Mangler direkte relasjon mellom Dokumentobjekt og Registrering

### ISSUE THREAD

**Issue by petterreinholdtsen** [arkivverket/noark5-tjenestegrensesnitt-standard#118]
Dette er en mangelmelding som kun er registrert på github, og ikke er sendt inn til Arkivverkets postmottak. Se også https://github.com/petterreinholdtsen/noark5-tester/blob/master/mangelmelding/sendt/2019-04-09-registrering-dokumentobjekt.md .

 ------------------  ---------------------------------
           Prosjekt  Noark 5 Tjenestegresesnitt
           Kategori  Versjon 1.0 beta
        Alvorlighet  protest
       Meldingstype  trenger klargjøring
    Brukerreferanse  pere@hungry.com
        Dokumentdel  7.2.1.7 (Dokumentobjekt)
         Sidenummer  99
        Linjenummer  n/a
    Innsendingsdato  2019-04-09
 ------------------  ---------------------------------

Denne teksten er del av en samling innspill til Noark5-standarden tilgjengelig fra [https://github.com/petterreinholdtsen/noark5-tester/](https://github.com/petterreinholdtsen/noark5-tester/).

Beskrivelse
-----------

Gjelder også dokumentdel 7.2.1.18 (Registrering) side 146.

I følge arkivstruktur.xsd for Noark 5 versjon 4 så kan en registrering enten ha «dokumentbeskrivelse» eller «dokumentobjekt» under seg. Dagens datastruktur i API-et tillater kun dokumenbeskrivelse.  Bør en også tillate dokumentobjekt direktekoblet til registrering?  I motsatt fall bør det dokumenteres i spesifikasjonen at det er et bevisst valg å ikke støtte dette, med forklaring og begrunnelse.

Dette er definisjonen av registrering fra arkivstruktur.xsd:

```XML
<xs:complexType name="registrering">
  <xs:sequence>
    <xs:element name="systemID" type="n5mdk:systemID"/>
    <xs:element name="opprettetDato" type="n5mdk:opprettetDato"/>
    <xs:element name="opprettetAv" type="n5mdk:opprettetAv"/>
    <xs:element name="arkivertDato" type="n5mdk:arkivertDato"/>
    <xs:element name="arkivertAv" type="n5mdk:arkivertAv"/>
    <xs:element name="referanseArkivdel" type="n5mdk:referanseArkivdel" minOccurs="0" maxOccurs="unbounded"/>
    <xs:element name="kassasjon" type="kassasjon" minOccurs="0"/>
    <xs:element name="skjerming" type="skjerming" minOccurs="0"/>
    <xs:element name="gradering" type="gradering" minOccurs="0"/>
    <!-- Tillater registreringer uten forekomster av dokumentbeskrivelse og dokumentobjekt -->
    <xs:choice>
      <xs:element name="dokumentbeskrivelse" type="dokumentbeskrivelse" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="dokumentobjekt" type="dokumentobjekt" minOccurs="0" maxOccurs="unbounded"/>
    </xs:choice>
  </xs:sequence>
</xs:complexType>
```

Ønsket endring
--------------

Under del 7.2.1.18 (Registrering) legges det inn følgende Relasjoner:

| **Relasjon**                        | **Kilde**                              | **Mål**                        | **Merknad** |
| ----------------------------------- | -------------------------------------- | ------------------------------ | ----------- |
| **Aggregation** (Bi-Directional)    | dokumentobjekt 0..* Dokumentobjekt     | registrering 1..* Registrering |             |

Under samme del legges følgende relasjonsnøkler inn:

| **Tag**   | **Verdi**                                                                |
| --------- | ------------------------------------------------------------------------ |
| REST\_REL | http://rel.kxml.no/noark5/v4/api/arkivstruktur/dokumentobjekt/           |
| REST\_REL | http://rel.kxml.no/noark5/v4/api/arkivstruktur/ny-dokumentobjekt/        |

Under del 7.2.1.7 (Dokumentobjekt) legges det inn følgende Relasjoner:

| **Relasjon**                        | **Kilde**                              | **Mål**                        | **Merknad** |
| ----------------------------------- | -------------------------------------- | ------------------------------ | ----------- |
| **Aggregation** (Bi-Directional)    | dokumentobjekt 0..* Dokumentobjekt     | registrering 1..* Registrering |             |

Under samme del legges følgende relasjonsnøkkel inn:

| **Tag**   | **Verdi**                                                              |
| --------- | ---------------------------------------------------------------------- |
| REST\_REL | http://rel.kxml.no/noark5/v4/api/arkivstruktur/registrering/           |

**Comment by petterreinholdtsen** [comment]
Merk, denne endringen fordrer også noen nye relasjoner i UML-diagrammene som inneholder både Registrering og Dokumentobjekt.  Hvis det er enighet om denne endringen, så tar jeg det med i selve endringsforslaget.

**Comment by oivkru** [comment]
Frem til og med Noark 5 versjon 3.1 var det mulig å gå direkte fra registrering ned til dokumentobjekt, dvs. sløyfe dokumentbeskrivelse. Denne muligheten ble tatt bort f.o.m. Noark 5 versjon 4.0, siden det er status på dokumentbeskrivelse som styrer tilgangen til å redigere i dokumentet/innholdet. Hvis nivået dokumentbeskrivelse er valgfritt/kan omgås, er det ingen mekanismer/krav i standarden som sier når et dokument skal fryses for redigering.

**Comment by petterreinholdtsen** [comment]
Aha.  Det betyr vel at det er feil i både https://github.com/arkivverket/schemas/blob/master/N5/v4.0/arkivstruktur.xsd og https://github.com/arkivverket/schemas/blob/avlevering-wip/N5/v5.0/arkivstruktur.xsd?

**Comment by petterreinholdtsen** [comment]
Ut fra antagelsen om at det vil ta en god stund før eventuelle feil i v4-arkivstruktur.xsd blir korrigert, så bør det skrives eksplisitt inn i tjenestegrensesnitt-spesifikasjonen at det er med vilje ingen direkte lenke mellom registrering og dokumentobjekt.

**Comment by petterreinholdtsen** [comment]
Jeg ser fra https://github.com/arkivverket/schemas/blob/master/N5/v5.0/arkivstruktur.xsd#L274 at feilen i arkivstruktur.xsd er korrigert i Noark 5 versjon 5.

**Comment by AnnKnu** [comment]
Denne ser grei ut. Merger du denne @hanber

**Comment by petterreinholdtsen** [comment]
Med avgjørelsen om å gå for n5v5 (se #207) blir denne mangelmeldingen irrelevant, så jeg lukker den.
