### ISSUE TITLE
Definisjonsfeil for «arkivskaperNavn» og «tilknyttetRegistreringSom» i metadatakatalogen

### ISSUE THREAD

**Issue by tsodring** [arkivverket/noark5-tjenestegrensesnitt-standard#124]
Dette er en mangelmelding som kun er registrert på github, og ikke er sendt inn til Arkivverkets postmottak. 

Definisjonsfeil for «arkivskaperNavn» og «tilknyttetRegistreringSom» i metadatakatalogen
========================================================================================

 ------------------  ---------------------------------
           Prosjekt  NOARK 5
           Kategori  Versjon 4.0
        Alvorlighet  protest
       Meldingstype  trenger klargjøring
    Brukerreferanse  celinefredriksen89@yahoo.com
        Dokumentdel  n/a
         Sidenummer  11
        Linjenummer  n/a
    Innsendingsdato  Ikke sendt inn
 ------------------  ---------------------------------

Beskrivelse
-----------

Gjelder også side 26.

I [metadatakatalogen](https://www.arkivverket.no/forvaltning-og-utvikling/noark-standarden/noark-5/noark5-standarden/_/attachment/download/f52e37da-31ed-4bf0-9fbf-69f0357aa25c:025a30b602a65d74377b9e0c22a0f2fb8eab84df/Noark5v4%20vedl1%20Metadatakatalog.pdf)
(side 11) for Noark 5 versjon 4 er det en feil tilknyttet definisjonen
av attributtet «M023 arkivskaperNavn». Det står at «arkivskaperNavn»
er tilknyttet arkivenheten «*arkiv*». Det skal stå at
«arkivskaperNavn» er tilknyttet arkivenheten «*arkivskaper*». Videre
står det at attributtet forekommer mange ganger, men fra XSD ser vi at
dette ikke stemmer. Det skal forekomme en gang.

Attributtet «M217 tilknyttetRegistreringSom» (side 26) har også en
feil der det står at «tilknyttetRegistreringSom» forekommer mange
ganger under dokumentbeskrivelse.  Utifra XSD definisjonen, ser vi at
det forekommer en gang.

Merk at feilen gjelder også for Noark 5 versjon 5.

Ønsket endring
--------------

Attributtet «M023 arkivskaperNavn» blir endret i metadatakatalogen
slik at det har en tilknytning til arkivenhet «*arkivskaper*» og
forekomst egenskapen blir en endret til «En».

Forekomst egenskapen til attributtet «M217 tilknyttetRegistreringSom»
blir endret til «En».

Respons
-------

Ingen respons fra Arkivverket så langt.

**Comment by AnnKnu** [comment]
@oivkru ser du på denne?

**Comment by oivkru** [comment]
M023 arkivskaperNavn tilhører et objekt (arkivskaper) som er gruppert inn i arkivenheten arkiv. Det er sånn sett riktig det som står i metadatakatalogen, siden arkivskaper altså ikke er en arkivenhet. Arkivenheter er arkiv, arkivdel, klassifikasjonssystem, klasse, mappe, registrering, dokumentbeskrivelse og dokumentobjekt. 

Når det er sagt, så er ikke metadatakatalogen konsistent på dette. Det er flere metadata hvor det er oppgitt at de tilhører en spesialisering av en arkivenhet (f.eks. moeteregistrering, moetemappe, saksmappe eller journalpost). I tillegg er det noen (M400-M412) hvor det oppgis at de tilhører korrespondansepart eller part, som heller ikke er arkivenheter. Dette er en større ryddejobb, og det er mulig metadatakatalogen burde oppgitt hvilket objekt metadataelementet kan eller skal tilhøre, i stedet for arkivenheten. 

M217 tilknyttetRegistreringSom er feil i metadatakatalogen, ja. I objektsortert metadatakatalog er det riktig, der står det at forekomst er 1.

**Comment by petterreinholdtsen** [comment]
Overført til riktig prosjekt som https://github.com/arkivverket/noark5-standard/issues/46, så lukkes her.
