### ISSUE TITLE
Linjenummer i tekstmargen vil forenkle henvisninger

### ISSUE THREAD

**Issue by petterreinholdtsen** [arkivverket/noark5-tjenestegrensesnitt-standard#13]
Dette er en kopi av mangelmelding sendt inn til Arkivverket, se også https://github.com/petterreinholdtsen/noark5-tester/blob/master/mangelmelding/sendt/2017-03-29-skriv-linjenummer.md .

 ------------------  ---------------------------------
           Prosjekt  NOARK 5 Tjenestegresesnitt
           Kategori  Versjon 1.0 beta
        Alvorlighet  kommentar
       Meldingstype  utelatt
    Brukerreferanse  pere@hungry.com
        Dokumentdel  hele dokumentet
         Sidenummer  n/a
        Linjenummer  n/a
    Innsendingsdato  2017-03-29
 ------------------  ---------------------------------

Beskrivelse
-----------

Det ville være enklere å referere til bestemte deler i spesifikasjonen hvis teksten hadde linjenummer i margen.  Da slapp en å telle avsnitt og setninger, og kunne nøye seg med å opplyse om sidetall og linjenummer.  Dette gjelder også JSON- og XML-eksempler, som bør kunne refereres til med linjenummer.  Endel av disse eksemplene er i dag tatt inn i dokumentet som bilder.  Det at de er bilder, gjør i tillegg at hvis en trenger å hente ut deler av et eksempel så må en skrive av eksemplene med tilhørende fare for stavefeil.

Ønsket endring
--------------

Tekstmalen som brukes til spesifikasjonen bør endres slik at alle sider har linjenummer i marken.

Et eksempel på en oppskrift for Microsoft Word 2013 finnes på

* https://www.howtogeek.com/170789/how-to-number-lines-in-the-margins-in-word-2013/

Respons
-------

Ingen respons fra arkivverket så langt.

**Comment by torkjetil** [comment]
Støttes

**Comment by petterreinholdtsen** [comment]
Jeg har sett på hvordan det kan gjøres med dblatex og lineno-utvidelsen til LaTeX.  Desverre blir linjenummerene i mine første forsøk merkelige (fortsetter telling på neste side), så jeg er ikke i mål.
