### ISSUE TITLE
Beskriv bruken av PRONOM-koder i format-feltet (M701)

### ISSUE THREAD

**Issue by petterreinholdtsen** [arkivverket/noark5-tjenestegrensesnitt-standard#143]
Dette er en mangelmelding som kun er registrert på github, og ikke er sendt inn til Arkivverkets postmottak. Se også https://github.com/petterreinholdtsen/noark5-tester/blob/master/mangelmelding/sendt/2019-04-17-formatkoder.md .

 ------------------  ---------------------------------
           Prosjekt  Noark 5 Tjenestegresesnitt
           Kategori  Versjon 1.0 beta
        Alvorlighet  protest
       Meldingstype  utelatt
    Brukerreferanse  pere@hungry.com
        Dokumentdel  7.2.2.10 (Format)
         Sidenummer  172
        Linjenummer  n/a
    Innsendingsdato  2019-04-17
 ------------------  ---------------------------------

Denne teksten er del av en samling innspill til Noark5-standarden tilgjengelig fra [https://github.com/petterreinholdtsen/noark5-tester/](https://github.com/petterreinholdtsen/noark5-tester/).

Beskrivelse
-----------

I følge uttalelser fra Arkivverket i mangelmelding [#4](https://github.com/arkivverket/noark5-tjenestegrensesnitt-standard/issues/4), [#11](https://github.com/arkivverket/noark5-tjenestegrensesnitt-standard/issues/11) og [#77](https://github.com/arkivverket/noark5-tjenestegrensesnitt-standard/issues/77) er det bestemt at format-feltet i Noark 5, felt M701 i metadatakatalogen, skal inneholde PRONOM-koder.  Det bør stå i spesifikasjonen og det bør beskrives hvilken form slike formatkoder skal ha.  Foreslår å bruke samme form som PRONOM bruker på sine websider, det vil si "fmt/18" og "x-fmt/18".  Ved å bruke denne formen kan formatkoden enkelt slås opp i PRONOM-katalogen ved å besøke URL på denne formen: http://www.nationalarchives.gov.uk/PRONOM/x-fmt/18 .

Valget av PRONOM gir endel utfordringer.  En utfordring er at SOSI-formatet mangler PRONOM-kode.  Jeg har kontaktet PRONOM-prosjektet og bedt om slik kode (fikk referansenummer TNA1555078202S60 fra dem), men per 2019-04-17 har det ikke blitt opprettet kode for SOSI.  Inntil alle formater som skal arkiveres får PRONOM-koder må det finnes en prosedyre for å definere sine egne koder.  En åpenbar mulighet er å definere et annet prefix enn "fmt" og vedlikeholde sin egen katalog over ekstra formatkoder.  Foreslår at "vnd" brukes for slike formatkoder, at en slik kode defineres for SOSI ("vnd/1"), og at teksten beskriver at slike koder skal byttes ut med offisielle koder så snart offisiell PRONOM-kode eksisterer.  Det er uheldig med en skyggekatalog med ekstrakoder, men alternativet er å ikke sette format på slike filer, hvilket gjør det vanskelig å identifisere hvilke formater det gjelder.

En annen utfordring er at hver av formatene godkjent i Riksarkivarens forskrift kan bety flere PRONOM-koder.  En liste over mulige PRONOM-koder som kan brukes for disse formatene er tilgjengelig fra mitt gitlab-prosjekt [m701-noark5-katalog](https://gitlab.com/petterreinholdtsen/m701-noark5-katalog/blob/master/formatlist.rst), og en kan der se hvilke av formatene jeg har identifisert som har mer enn en formatkode hos PRONOM.

Et tredje problem er at enkelte PRONOM-koder kan bety flere av formatene som er listet opp i Riksarkivarens forskrift.  For eksempel er .docx både fmt/412 og fmt/494, alt etter om filen er kryptert eller ikke, mens fmt/494 som er det krypterte formatet også gjelder .pptx og .xlsx når de er krypterte.  Det er uklart for meg hvordan dette skal løses.  En mulighet er å slå fast at Riksarkivarens forskrift ikke gjelder krypterte dokumenter og dermed falle tilbake til formatkodene som identifiserer individuelle formater.  En annen er å godta samtlige mulige PRONOM-koder for et gitt format.  En tredje er å ikke forsøke å identifisere PRONOM-koder for formatene som er i Riksarkivarens forskrift, men det gjør det vanskelig å identifisere hvilke filer i arkivet som ikke er nevnt i forskriften.

Ønsket endring
--------------

Legg til beskrivelse for kodeliste Format på side 172 om at kodeverdiene skal hentes fra PRONOM.  Beskriv at formater som ikke har pronom-koder skal håndteres ved å bruke et annet prefix ("vnd/") og et nummer tildelt i den offisielle formatlisten over formater omtalt i Riksarkivarens forskrift.  Skriv at listen over formater i attributter-tabellen er et eksempel og henvis til eksternt vedlikeholdt liste over formater for oppdatert og komplett liste over PRONOM-koder for formatene i Riksarkivarens forskrift.  Frem til Arkivverket publiserer sin liste foreslår jeg at min liste ([m701-noark5-katalog](https://gitlab.com/petterreinholdtsen/m701-noark5-katalog/blob/master/formatlist.rst)) brukes.  Gitlab-repoet vil bli flyttet til nikita-prosjektet og vedlikeholdt der.

Bytt ut alle oppføringer i tabellen over "attributter" til å ha unike PRONOM-koder i "Kode"-kolonnen.

Jeg sender inn konkret forslag til endring som patch via github.

**Comment by petterreinholdtsen** [comment]
I følge @hanber i https://github.com/arkivverket/noark5-tjenestegrensesnitt-standard/issues/11#issuecomment-456063798 har Arkivverket en format-ansvarlig som 21. januar var igang med å gå gjennom alle gyldige arkivformater i Riksarkivarens forskrift for å finne PRONOM-identifikatorene for disse.  Kan noen i Arkivverket dele her hva den format-ansvarlige har funnet ut så langt?  Ligner den listen på det jeg har laget i git-repoet m701-noark5-katalog?

**Comment by petterreinholdtsen** [comment]
I XSD-filene for Noark 5 versjon 5 som er lagt ut på https://github.com/arkivverket/schemas/tree/master/N5/v5.0 er det lagt til to nye felter M703 pronomPUID og M704 pronomMIME i tillegg til M701 format.  Dette tyder på at M701 fortsatt kommer til å være uten definisjon, og at en må håndtere PRONOM PUID i tillegg for dokumentobjekt.  Mitt forslag til endring i #144 forutså ikke den tilnærmingen og må i så fall endres hvis det ikke er meningen å putte PUID i M701 format.

**Comment by petterreinholdtsen** [comment]
Jeg har sendt inn forespørsel til PRONOM og IANA om SOSI, samt endringsforslag for å lære file(1) å kjenne igjen SOSI-filer.  Detaljer og referanser kan leses på http://people.skolelinux.org/pere/blog/MIME_type__text_vnd_sosi__for_SOSI_map_data.html .  Det vil ta noen måneder før vi vet om alle forslagene går inn uten endringer.

**Comment by petterreinholdtsen** [comment]
Kan melde litt nytt om SOSI siden sist oppdatering.  IANA meldte dagen etter at forespørselen om offisiell MIME-type er sendt over til domeneeksperter for vurdering, og PRONOM-vedlikeholderne meldte i går at SOSI vil bli med i neste versjon av PRONOM-katalogen.  Endringsforslaget til file(1) er kommet inn i offisiell kildekode og vil være med i neste utgave når den blir sluppet.

Det ser dermed ut til at SOSI vil ha nødvendige identifikatorer om ikke lenge. :)

**Comment by tsodring** [comment]
Bra jobba Petter! Dette var en viktig jobb å få gjort!

**Comment by petterreinholdtsen** [comment]
Fikk beskjed i dag tidlig fra IANA om at text/vnd.sosi nå er registert som offisiell MIME-type for SOSI-formatet.  Har tidligere fått beskjed om at ny versjon av PRONOM skal komme i sommer med SOSI inkludert.

**Comment by petterreinholdtsen** [comment]
Oppdatert endringsforslag inneholder PRONOM-koder for alle eksempeloppføringer i kapittel 7 og gjør det klart  at dette bare er eksempler og at offisiell liste over formatkoder vedlikeholdes i regi av Arkivverket, uten å nevne Nikita.

**Comment by AnnKnu** [comment]
Fint @petterreinholdtsen . Er denne og  #144 nå ok?

**Comment by petterreinholdtsen** [comment]
Jeg tror teksten er i tråd med det vi ble enig om på møtet, ja.

Jeg vil helst at det også konkret fortelles hvor listen over formatkodene kan finnes, slik at de som implementerer tjenestegrensesnittet har en mulighet til å bruke de samme formatkodene, men innser at det må gjøres i en annen mangelmelding og tilhørende endringsforslag.
