### ISSUE TITLE
API-beskrivelsen fungerer ennå ikke, og det gjorde heller ikke 1.0 beta

### ISSUE THREAD

**Issue by petterreinholdtsen** [arkivverket/noark5-tjenestegrensesnitt-standard#163]
Jeg leser fra [nyhetsmelding publisert av arkivverket](https://www.arkivverket.no/nyheter/noark-5-er-under-videreutvikling), at "Tjenestegrensesnittet ble levert fra Samdok-prosjektet i betaversjon i september 2016, og var i utgangspunktet et fungerende grensesnitt. Siden det ikke var utprøvd ble det kalt en beta, og vi gikk ut fra at det ville komme innspill, kommentarer og feilmeldinger etterhvert som det ble tatt i bruk."  Hva legges i dette?

Beskrivelsen av tjenestegrensesnittet i 1.0 beta er etter mitt kvalifiserte skjønn milevis unna "et fungerende grensesnitt", da både basale ting som hvordan utveksling av meldinger med REST, hvordan ulike deler av arkivinstanser skal oppdateres og mer overordnede ting som hvordan håndtere feil, mangler i beskrivelsen av grensesnittet.

Spesifikasjonen, selv etter at samtlige mangelmeldinger rapportert via her via github er fikset, vil fortsatt ikke oppfylle prosjektets hovedmål (fra 1.0 beta-spesifikasjonen):

> 1.5 PROSJEKTETS HOVEDMÅL
> Mandatet for prosjektet var
> * å etablere en plattformuavhengig informasjonsmodell i UML for arkivstrukturen i Noark 5
> * å definere CRUD tjenester (Create, Read, Update, Delete) for objektene i informasjonsmodellen

Det er fortsatt for mange uklarheter og muligheter for tolkning i teksten, hvilket vil føre til leverandørinnlåsing (dvs. ikke en plattformuavhengig informasjonsmodell).

Jeg vil svært gjerne bidra til at spesifikasjonen blir så klar og entydig at den ikke fører til mer leverandørinnlåsing, og tror en god start er en felles forståelse om hvor mye som gjenstår før spesifikasjonen oppnår dette.  Nyhetsmeldingen omtalt over gjør meg i tvil om det er tilfelle.  Den legger opp til å senke listen for hva som må være på plass, for å tvinge igjennom en ny utgave av spesifikasjonen i sommer, uten tanke for konsekvensene dette kan få for å skade prosjektets hovedmål ved å bidra til mer platformavhengighet i stedet for mindre.

De mangelmeldingen som er tatt med i prosjekt [NOARK Tj.Gr. 5 versjon 4](https://github.com/arkivverket/noark5-tjenestegrensesnitt-standard/projects/1) er etter mitt skjønn ikke tilstrekkelig til å oppnå prosjektets mål, og planen om å fokusere på Noark 5 versjon 4 der mens nyhetsmeldingen sier at "Arkivverket kommer ikke lenger til å godkjenne løsninger etter de tidligere versjonene av standarden" som jo gjelder versjon 4 av standarden, betyr jo i realiteten at de som implementerer et tjenestegrensesnitt for Noark 5 versjon 4 aldri vil kunne få sin løsning godkjent.  Det er jo å torpedere ethvert håp om en godkjenningsordning for API-implementasjoner, og vil gjøre det umulig å bruke godkjenningsmekanismer for a hindre leverandørinnlåsing.

**Comment by tsodring** [comment]
Det som bekymrer meg mer er :

> Nye løsninger skal godkjennes for Noark 5 versjon 5

Vi vet jo at det er uoverenstemelser mellom n5v4 og n5v5. Tjenestegrensesnittet reduseres til en filleting hvis det faktisk ikke kreves at systemene godkjennes etter det. Her legges det opp til en hel ny runde med forvirring og misforståelser. Noark 5 versjon 4 skulle ikke blitt publisert tror jeg. Tjenestegrensesnittet burde ferdigstilles mot Noark 5 versjon 5 ikke Noark 5 versjon 4.

**Comment by oivkru** [comment]
Det viktigste for oss er at vi leverer et tjenestegrensesnitt som fungerer, et «minimal viable product». Vi ønsker at tjenestegrensesnittet er «noe» som leverandørene kan begynne å bruke, uten at det nødvendigvis er perfekt. Når flere i markedet tar det i bruk, får vi også et bedre erfaringsgrunnlag å jobbe videre med. Vi ønsker ikke å signalisere at vi leverer noe uferdig, som dermed ikke tas i bruk, og dermed ikke kan videreutvikles. Derfor går vi ut med nyheten om at tjenestegrensesnittet skal bli "ferdig" før sommeren.

For dette er det viktigste: tjenestegrensesnittet skal videreutvikles. Selv om vi før sommeren leverer noe som kan brukes, er vi ikke ferdige med tjenestegrensesnittet, det skal forvaltes videre. Vi skal håndtere feilmeldinger, endringsønsker, osv. på github. Det blir selvsagt aldri perfekt, men vi jobber med sikte på å få det så bra som mulig, også etter at vi har levert  en «ferdig» versjon, som lar seg implementere av leverandørene. 

Vi ser på hvordan den "ferdige" versjonen blir mot N5v5, og hva som skal til for å tilpasse - det trenger ikke være store jobben å oppdatere til siste versjon.

**Comment by tsodring** [comment]
Takk for tilbakemelding Øivind! Det er betryggende å høre at Arkivverket ønsker å videreutvikle tjenestegrensesnittet, men erfaringsmessig vet vi at dere er avhengig av midler og tilgjengelig menneskeressurser for å følge dette opp. Derfor er jeg reelt bekymret at dette tørker ut.

Hvis du sier her at tjenestegrensesnittet kan ferdigstilles mot Noark 5 versjon 5 så er det en gledens dag! Det har mye å si hvorvidt tjenestegrensesnittet blir en suksess eller ikke!

Dere skal ha ros for å utvikle dette på github og denne type åpne prosesser er noe forvaltningen burde se på som en slags best-practice for standard utvikling.

Hvis ikke de etablerte leverandørene tar i bruk tjenestegrensesnittet er arbeidet bortkastet. Derfor er det så viktig å få dette på plass. Jeg vet at noen av leverandørene har satt all utviklingsarbeid til land der de ikke forstår norsk så det er en høy terskel for at dette skal tas i bruk. Markedsprinsippene fungerer ikke særlig godt i dette markedet dessverre!

Vi er i en høne/egg situasjon. Jeg tror noen leverandører ikke vil støtte tjenestegrensesnittet før det er utbredt og det kommer aldri til å bli utbredt før det er tatt i bruk. Jeg tviler leverandørene har lyst til å sette av ressurser til å teste utvikling av en tjenestegrensesnitt når de vet at det allikevel kan forekomme  endringer. Vi ser det i den andre implementasjonen av tjenestegrensesnittet, det er et bra forsøk men fortsatt et stykke unna.

Du sier selv at dere ønsker å oppnå
> oppnå et «minimal viable product»

Da er det viktig at det signaliseres som et _«minimal viable product»_. Da er det dette som er _Beta versjonen_ og det er dette som skal på høring for å få innspill. Det er dette leverandørene kan bruke for å 
se hvorvidt systemene deres kan tilpasses Noark 5 versjon 5. Det er også dette fagsystem leverandører kan bruke for  å teste hvorvidt de kan oppnå integrasjon til en arkivkjerne uten å måtte betale kostnaden som ligger i å forstå alle versjoner ov varianter av sak/arkiv kjerner som er der ute! Da er det fortsatt en del ting som må avklares. Det er mange ting som er viktig i innspurten, men de tre tingene jeg ønsker å flagge er:

1. Få XSD-filene til Noark 5 versjon 5 i samsvar med tjenestegrensesnittet
2. Gå over til PATCH for oppdatering
3. Avklar håndtering av sekundærentiteter feks merknad

De første to er viktige områder som har mye å si for kvaliteten. Når det gjelder (1) så er det viktig at vi ikke kaster arkivverdig informasjon bare fordi vi ikke har  plass til det i XML. Når det gjelder (2) er det viktig at klienter trenger å forstå så lite som mulig om Noark og at de ikke ødelegger data fordi de skal oppdatere hele objekter, framfor enkelattributter. Når det gjelder (3) så er det foreløpig uklart hvordan de skal oppdateres, slettes osv. Sammen med (2) kan det fort resultere i at data forsvinner.

Petter har kanskje andre ting som han mener er viktig, men de tre over er noe av det som er viktig å få avklart for å få til en god løsning. 

Signaliser at dere har oppnådd en fantastisk milepæl, et Noark 5 tjenestegrensesnitt tilpasset siste versjon av Noark standarden og noe som er utgangspunkt for interoperabilitet. Signaliser at det er en Beta versjon. Vi er nesten i mål, men trenger å høre fra miljøet hvorvidt det fungerer som tenkt. Signaliser et veikart framover for hvordan prosjektet skal komme i mål. Sett tidsfrister og sørg for at dere har fått tildelt midler. Signaliser hvordan dere vil jobbe opp leverandører og interessenter for å fremme tjenestegrensesnittet og videreutvikle det. Signaliser hvordan godkjenningsordningen skal være og hvordan dere kan validere  påstander om samsvar med standarden. 

For det er nå arbeidet med Noark 5 virkelig begynner!

**Comment by petterreinholdtsen** [comment]
[Øyvind Kruse]
> Det viktigste for oss er at vi leverer et tjenestegrensesnitt som
> fungerer, et «minimal viable product».. Vi ønsker at
> tjenestegrensesnittet er «noe» som leverandørene kan begynne å bruke,
> uten at det nødvendigvis er perfekt.

Jeg også.  Jeg tror perfekt er langt utenfor rekkevidde her.

> Når flere i markedet tar det i bruk, får vi også et bedre
> erfaringsgrunnlag å jobbe videre med. Vi ønsker ikke å signalisere at
> vi leverer noe uferdig, som dermed ikke tas i bruk, og dermed ikke kan
> videreutvikles. Derfor går vi ut med nyheten om at
> tjenestegrensesnittet skal bli "ferdig" før sommeren.

Min utfordring her er at jeg ikke tror vi har samme forståelse av hva en
fungernde API-spesifikasjon er, dvs. hva som trengs for å ha et «minimal
viable product».  Det er dette som gjør meg bekymret, da et resultat som
er for uklart og tvetydig vil være _skadelig_ for utbredelsen, og
skremme vekk alle markedsaktører som kunne vurdere å ta i bruk Noark 5
Tjenestegrensesnitt.

La meg komme med en liten historie, som kanskje kan gjøre det jeg mener
litt klarere.

Tenk deg en liten leverandør av et fagsystem A for
håndtering av skadet vilt i kommunen.  Dette er et fagsystem som har
informasjon og dokumenter som skal arkiveres i tråd med lov og
forskrift, og som ønsker å få dette til.  En utvikler hører om denne
API-spesifikasjonen, ser at det kan være protokollen å bruke for å
levere inn til og hente ut av dokumenter mot kommunens arkiv, i
motsetning til dagens tungvindte løsning.  Vedkommende leser
spesifikasjonen, endrer på fagsystemet til å bruke API-et til å arkivere
dokumenter, tester mot Nikita som er den eneste fritt tilgjengelige
implementasjonen av API-et, og når det fungerer der overtaler de en
pilotkunde til å ta løsningen i bruk mot sin Arkivløsning X.
Leverandøren av X forteller at de har implementert Noark 5
Tjenestegrensesnitt, og at dette burde fungere fint.

Men det viser seg at det fungerer ikke fint.  Fagsystem A kan ikke
snakke med Arkivløsning X via denne protokollen.  Det kan ikke engang
logge seg på, og selv etter å ha endret innloggingsmekanisme til det
Arkivløsning X tilbyr, som ikke er det samme som Nikita tilbyr, så viser
det seg at protokollmeldinger, datastrukturer og feltverdier er så
forskjellige at det til kreve betydelig nyutvikling før Fagsystem A kan
snakke disse to ulike språkene.

Utvikleren av fagsystem A har lest spesifikasjonen og tolket den etter
beste evne, og hvis det var tvil om hvordan det skulle tolkes så har
utvikleren sett på Nikita og n5test-websidene for å vite hvordan API-et
skal fungere.

Det viser seg at utvikleren av Arkivsystem X derimot har fått beskjed om
å gjøre legges å få timer som mulig inn i utviklingsarbeidet av deres
tolkning av API-tjenesten, da det ikke finnes et markedsgrunnlag som
forsvarer utviklingen og de kun ønsker "Noark 5
Tjenestegrensesnittstøtte" som et sjekklistepunkt på lista over
egenskaper for å kunne bli akseptert i anbud, men helst vil at kunder
skal bruke deres proprietære X-APIet i stedet.  Utvikleren av
Arkivsystem X har derfor kun har forholdt seg til spesifikasjonsteksten,
og der det var mulighet for flere tolkninger har han valg minste
motstands vei uten å se på hvordan andre har tolket samme formulering i
spesifikasjonen.  Resultatet er en API-tjeneste som er i tråd med en
mulig tolkning av spesifikasjonen, men som låser enhver API-klient til
Arkivsystem X like godt som om de hadde brukt det proprietære X-APiet i
stedet.  I tillegg viser det seg at det implementerte API-et har mangler
som gjør det umulig å oppdatere endel verdier, og det kan ikke brukes
til det fagsystem A trenger.

Utvikleren av fagsystem A forsøker å snakke med kommunens kundekontakt
for Arkivsystem X og forklare hvorfor det er viktig at Arkivsystem X
endrer sitt API til å være mer i tråd med hvordan andre arkivsystemer
har tolket spesifikasjonen, men får beskjed om at tolkningen til
Arkivsystem X er fullt i tråd med det som står i spesifikasjonen, og at
eventuelle endringer må betales av pilotkommunen, dvs. kunden.  Det
viser seg umulig å komme i kontakt med utvikleren hos Arkivsystem X for
å diskutere forbedringer, da vedkommende var innleid fra et lavkostland
og ikke lenger er tilgjengelig.

Alternativ slutt 1: Utvikleren av fagsystem A innser at kommunen aldri
kommer til å ta seg råd til slik utvklingskostnad, dropper å bruke Noark
5 Tjenstegrensesnitt og går for GeoIntegrasjon 3000 i stedet, eventuelt
det proprietære X-APIet.

Alternativ slutt 2: Selskapet som lager fagsystem A har brukt så mye
penger på utvikling og oppfølging av denne saken at de går konkurs og
alle kommuner som brukte fagsystem A må finne seg en annen leverandør
som ikke falt i fellen å tro at Noark 5 Tjenestegrensesnitt virket på
tvers av systemer.

Andre utviklere hører om erfaringen og bestemmer seg også for å droppe
Noark 5 Tjenstegrensesnitt.

------ The end ------

For å sikre at dette ikke skjer så må spesifikasjonen til Noark 5
tjenestegrensesnitt være så entydig og klar at to utviklere som leser
den og forsøker å snakke dette språket, kommer opp med samme protokoll.

I dag er det ikke klart hvordan logge inn, det er ikke klart hvordan
oppdatere relasjoner, det er ikke klart hvordan opprette en saksmappe,
hvordan lagre en fil, hvordan søke opp en fil fagsystemet har lagret i
arkivet, hvordan finne en mappe basert på fagsystemets interne saks-id,
etc, etc.

Jeg snakker altså ikke om «perfekt» eller «komplett», jeg snakker om
minimum for å sikre at to uavhengige utviklere som følger
spesifikasjonen til punkt og prikke ender opp med to datasystemer som
kan snakke sammen.  Da kan vi snakke om at spesifikasjonen er ferdig og
brukbar.

Jeg vil gjerne bidra til at vi kommer tid. Min fokus er å lage
API-klienter, og jeg ønsker å sikre at de API-klientene jeg skriver vil
kunne snakke med et hvilket som helst arkivsystem som implementerer
Noark 5 Tjenestegrensesnitt.

Jeg bidrar gjerne som medlem i en liten redaksjon for spesifikasjonen,
og tror det kunne være nyttig med møter der hver enkelt mangel
diskuteres av interesserte aktører for å komme frem til gode løsninger
på problemene som beskrives.

Det oppleves som et stort problem at det ikke er noen som kommenterer og
kommer med innspill på mangelmeldingene vi har sendt inn, og nesten
aldri få hverken kritikk av de konkrete endringsforslagene som sendes
inn, og heller ingen tegn til at de blir vurdert tatt med i
spesifikasjonen.  De eldste endringsforslagene uten kommentar er i dag
fra 2019-03-02, dvs. to og en halv måned.  Og det er en og en halv måned
til spesifikasjonen skal være «perfekt».  Vi det er ikke mye tid til å
fikse alle manglene som er rapportert, og da er ikke alle de manglene vi
ennå ikke har rukket fullføre beskrivelsen av tatt med.  Det er mange
alvorlige og fundamentale problemer vi ennå ikke har rukket beskrive
ferdig. :(

Jeg tror vi har samme mål her, en spesifikasjon som lar seg implementere
av leverandører og som sikrer samhandling.  Skal vi nå dit tror jeg vi
også må ha samme forståelse av hvor målet befinner seg.

Målet jeg har fått beskrevet fra Arkivverket for det som skal bli ferdig
før sommeren er det som er listet opp i "NOARK Tj.Gr. 5 versjon 4".  Det
er langt unna det jeg tror er minimum for å sikre samhandling.

-- 
Vennlig hilsen
Petter Reinholdtsen
