### ISSUE TITLE
Relaterte XSD-filer bør inn i git-depotet

### ISSUE THREAD

**Issue by petterreinholdtsen** [arkivverket/noark5-tjenestegrensesnitt-standard#209]
------------------  ---------------------------------
           Prosjekt  NOARK 5 Tjenestegresesnitt
           Kategori  Versjon 1.0 beta
        Alvorlighet  kommentar
       Meldingstype  utelatt
    Brukerreferanse  pere@hungry.com
        Dokumentdel  n/a
         Sidenummer  n/a
        Linjenummer  n/a
 ------------------  ---------------------------------
### Beskrivelse

Jeg er fortalt at det lages et sett XSD-filer relatert til tjenestegrensesnittet, som ikke er identiske med XSD-filene som beskriver deponi-formatet.

Disse XSD-filene bør legges inn i dette GIT-depotet slik at endringshistorikken her viser hvilke endringer disse XSD-filene har.

## Ønsket endring

Opprett en ny katalog på toppnivå (for eksempel xsd/), som fylles med relevante og aktuelle XSD-skjema.

**Comment by monadani** [comment]
Enig

**Comment by petterreinholdtsen** [comment]
Dette ble fikset innsjekk 050bdf6db5d95a25951028aafc18afdfc660e5fe .
