### ISSUE TITLE
Når skal det brukes 'uri' i stedet for 'href' _links?

### ISSUE THREAD

**Issue by petterreinholdtsen** [arkivverket/noark5-tjenestegrensesnitt-standard#22]
Dette er en kopi av mangelmelding sendt inn til Arkivverket, se også https://github.com/petterreinholdtsen/noark5-tester/blob/master/mangelmelding/sendt/2017-04-19-links-href-uri.md .

 ------------------  ---------------------------------
           Prosjekt  NOARK 5 Tjenestegresesnitt
           Kategori  Versjon 1.0 beta
        Alvorlighet  kommentar
       Meldingstype  trenger klargjøring
    Brukerreferanse  pere@hungry.com
        Dokumentdel  http://rel.kxml.no/noark5/
         Sidenummer  n/a
        Linjenummer  n/a
    Innsendingsdato  2017-04-19
 ------------------  ---------------------------------

Beskrivelse
-----------

I spesifikasjonens 6.1.1.1 (Oppkobling og ressurslenker) på side 11 og 12 skal relasjonnøkler oppgis med 'href' og 'rel'.  Dette blir ikke gjort for eksempel i http://rel.kxml.no/noark5/v4/api/arkivstruktur/mappe/ som bruker 'uri' i \_links i stedet for href.  Andre deler av nettstedet, for eksempel i http://rel.kxml.no/noark5/v4/api/arkivstruktur/arkivdel/ som bruker 'href'.  Er det feil i nettsiden?  I motsatt tilfelle bør spesifikasjonen utvides til å forklare når 'uri' skal brukes i stedet for 'href'.  Jeg antar det er feil på nettsiden.  Det gjelder så vidt jeg kan se tre tilfeller.

Ønsket endring
--------------

Endre 'url' til 'href' i \_links-responsen som vises frem på disse nettsidene:

 * http://rel.kxml.no/noark5/v4/api/arkivstruktur/dokumentobjekt/
 * http://rel.kxml.no/noark5/v4/api/arkivstruktur/mappe/
 * http://rel.kxml.no/noark5/v4/api/arkivstruktur/registrering/

**Comment by hanber** [comment]
Dette har vi ingen synspunkter på.

**Comment by henningjensen** [comment]
Dette bør være konsistent og vi fikser disse tre tilfellene til å bruke href.

**Comment by petterreinholdtsen** [comment]
OK.  Da er slik jeg forstår det spesifikasjonen korrekt og websiden feil, og denne mangelmeldingen om behovet for klargjøring i spesifikasjonen kan i grunnen lukkes som løst, mens det lages en ny mangelmelding på egnet sted om fiks av innholdet på http://rel.kxml.no/.

**Comment by petterreinholdtsen** [comment]
Så vidt jeg kan se er alle url endret til href på nettsidene http://rel.kxml.no/noark5/v4/api/arkivstruktur/dokumentobjekt/, http://rel.kxml.no/noark5/v4/api/arkivstruktur/mappe/ og http://rel.kxml.no/noark5/v4/api/arkivstruktur/registrering/ .  Lukker dermed saken som løst.  Merk at det er flere andre feil på disse websidene, men det får dekkes av en annen mangelmelding.
