### ISSUE TITLE
Oppdatere Sakspart til part i kapittel 6?

### ISSUE THREAD

**Issue by AnnKnu** [arkivverket/noark5-tjenestegrensesnitt-standard#224]
------------------  ---------------------------------
           Prosjekt  NOARK 5 Tjenestegresesnitt
           Kategori  Versjon 1.0 beta
        Alvorlighet  kommentar / protest
       Meldingstype trenger klargjøring
    Brukerreferanse  @AnnKnu 
        Dokumentdel  # 06-konsepter_og_prinsipper.md
         Sidenummer  #
        Linjenummer  # 316 317
 ------------------  ---------------------------------

### Beskrivelse
Bør eksemplene oppdateres fra sakspart til part? 

| ../api/sakarkiv/Saksmappe/?$filter=sakspart/any(s:s/Default.SakspartPersonType/foedselsnummer eq '12334566')                                                                                                                    | Saksmapper med sakspart(SakspartPerson) med gitt fødselsnr                                              | utvidet |
| ../api/sakarkiv/Saksmappe/?$filter=sakspart/any(s:s/Default.SakspartEnhetType/organisasjonsnummer eq '12334566')                                                                                                                | Sakspart med organisasjonsnr    

## Ønsket endring
erstatt sakspart med part?

**Comment by petterreinholdtsen** [comment]
Ja, helt klart.
