### ISSUE TITLE
Er Mappe.mappetype overflødig eller kan det beskrives hva den skal brukes til?

### ISSUE THREAD

**Issue by petterreinholdtsen** [arkivverket/noark5-tjenestegrensesnitt-standard#242]
------------------  ---------------------------------
           Prosjekt  Noark 5 Tjenestegrensesnitt
           Kategori  Noark 5.5.0 TG versjon 1.0
        Alvorlighet  protest
       Meldingstype  trenger klargjøring
    Brukerreferanse  pere@hungry.com
        Dokumentdel  7.2.1.16 (Mappe)
         Sidenummer  135
        Linjenummer  n/a
    Innsendingsdato  2020-01-09
 ------------------  ---------------------------------

Denne teksten er del av en samling innspill til Noark5-standarden
tilgjengelig fra [https://github.com/petterreinholdtsen/noark5-tester/](https://github.com/petterreinholdtsen/noark5-tester/).

Beskrivelse
-----------

I listen over attributter knyttet til Mappe, så står det følgende:

| **Navn**  | **Merknad**   | **Multipl.**  | **Kode**  | **Type**  |
|-----------|---------------|---------------|-----------|-----------|
| mappetype | angir mappetype som blant annet kan brukes som hint til hva som ligger i virksomhetsspesifikkemetadata| \[0..1\] | | Mappetype |

Dette feltet står ikke i arkivstruktur.xsd for Noark 5 versjon 5.5, og
det er uklart hva det skal brukes til.  Det er ingen nærmere
informasjon i beskrivelsen for metadata-kodelisten Mappetype.

Vårt beste gjett er at dette er et felt som er ment å formidle om det
er snakk om en mappe, saksmappe eller moetemappe.  Det trengs ikke en
egen attributt for dette, da det vil fremgå av innholdet i _links, der
'self'-lenken kan brukes til å finne en gitt instans entitet/type,
jamfør beskrivelsen under overskriften "Identifisere enhetstype" i
kapittel 6.

Attributten er også listet opp i beta 1.0, og sidenummerene oppgitt
i ønsket endring er fra den PDF-en.

Ønsket endring
--------------

Fjern attributten mappetype fra listen over attributter knyttet til
Mappe i del 7.2.1.16 på side 135, og fjern Mappetype i del 7.2.2.19 på
side 180 fra listen over metadata-kodelister.

Fjern også henvisning til mappetype fra del 6.1.14 (Preutfylling av
objekt) på siden 18 og alle UML-diagram.

**Comment by tsodring** [comment]
Jeg er enig at feltet kan fjernes fra tjenestegrensesnittet. 

Jeg mistenker at bruksscenarioet her at det er tenkt at du kan hente ut et mappeobjekt. Hvis det er en saksmappe så vil  du kunne se mappetype = saksmappe. 

Du fikk inn en endring der du kan trekke ut hvilken datatype mappeobjeket er. Derfor blir feltet overflødig. Kanskje det må gjøres tydelig at en liste av mappe feks arkivstruktur->mappe vil gi klienten en liste mapper der mappen har riktig mappetype. Så det kunne være:

arkivdel 
 -> mappe 1
 -> mappe 2
 -> saksmappe 3
 -> byggesaksmappe 4
 -> mappe 5
 -> mappe  6 (med VSM)

Feltet henger kanskje igjen for å løse et problem som ikke lenger finnes i tjenestegrensesnittet

**Comment by petterreinholdtsen** [comment]
Jeg ser fra koden i Nikita at det der var laget følgende mappetyper i metadata-katalogen:

* Saksmappe
* Personalmappe
* Byggemappe
* Møtemappe

Hvis dette skal hinte om hvilke virksomhetsspesifikke metadata som er aktuelle i mappen, så holder det kanskje ikke å vite om det er Mappe, Saksmappe eller Møtemappe...

Kanskje det er bedre å få feltet inn i arkivstruktur.xsd for N5v5.5?

**Comment by monadani** [comment]
Jf din kommentar av 27/2 Petter; mener du i arkivstruktur.xsd for N5 versjon 5.1? M

**Comment by petterreinholdtsen** [comment]
[Mona Danielsen]
> Jf din kommentar av 27/2 Petter; mener du i arkivstruktur.xsd for N5
> versjon 5.1? M

I denne mangelmeldingen snakker jeg om
tjenestegrensesnitt-spesifikkasjonen, og bakgrunnen er at jeg fant en
attributt mappeType som ikke hadde tilsvarende felt i XSD-skjema.
Tenkte dermed at det vel måtte være en feil og derfor burde fjernes, da
en jo kan skille mellom Mappe, Saksmappe (og forsåvidt Moetemappe) ved å
se på self-relasjonen og tilhørende entitetsrelasjon.

Men så slo det meg at det står at mappeType gjør det mulig å
identifisere hvilke virksomhetsspesifikke metadata-nøkler (VSM) som er
aktuelle, og i så måte får en mulighet til å introdusere "mappe-typer"
som ikke har egne endepunkt og relasjonsnøkkel ved å bruke mappeType.

Hvorvidt det er ønskelig er et annet spørsmål, men jeg liker fleksible
og åpne standarder, og dermed ble jeg veldig i tvil om det gir mening å
fjerne mappeType fra tjenestegrensesnitt-spesifikkasjonen.  Kanskje er
det mer fornuftig å legge til et felt i arkivstruktur.xsd i stedet?

På den andre siden, hvis en først har VSM, så kan en jo finne på en
VSM-nøkkel for samme formål og få samme effekt, så det er kanskje ikke
nødvendig med et eget XML-felt i arkivstruktur.xsd.

I bunn og grunn ble jeg så usikker at jeg håper på en diskusjon med
flere om hva som er lurt og ønskelig her.  Spesielt med noen som vet
hvorfor mappeType ble lagt inn i første omgang.

-- 
Vennlig hilsen
Petter Reinholdtsen

**Comment by hanber** [comment]
All den tid mappetype fantes i Noark-4 og er videreført i Noark 5, og den finnes i Geointegrasjon Arkiv, er det mulig den er brukt i noen løsninger, og jeg synes det er skummelt å fjerne den. Den bør uansett hete _mappetype_, ikke _mappeType_, siden det er ett ord.

**Comment by petterreinholdtsen** [comment]
[Hans Fredrik Berg]
> All den tid mappetype fantes i Noark-4 og er videreført i Noark 5, og
> den finnes i Geointegrasjon Arkiv, er det mulig den er brukt i noen
> løsninger, og jeg synes det er skummelt å fjerne den. Den bør uansett
> hete _mappetype_, ikke _mappeType_, siden det er ett ord.

Hva mener du med at mappetype er videreført i Noark 5?  Jeg finner den i
Noark 5 kun brukt som konsept med 'saksmappe' og 'moetemappe' som
konkrete implementasjoner.  Finner den ikke som metadatakatalogoppføring
eller attributt.

Hvor kan jeg finne hvordan den er brukt i Noark 4 og Geointegrasjon
Arkiv?  Gjerne med sidereferanse for å være sikker på at vi snakker om
det samme.

-- 
Vennlig hilsen
Petter Reinholdtsen

**Comment by hanber** [comment]
I [Metakat](http://arkivverket.metakat.no/Objekttype/Index/EAID_BEB30D94_3115_4526_9F00_D05A2BFD27CF) og [Geointegrasjon Arkiv](https://geointegrasjon.no/images/stories/rapporter/geointegrasjon_grensesnitt_mot_arkiv_v1.1.pdf) er mappetype beskrevet. Her refereres det til saType i Noark-4 Web Services, og SA.TYPE i Noark-4. I noark-4 fantes ikke generaliseringen mappe, bare saksmappe.

**Comment by tsodring** [comment]
Ref samtale i dag der vi ble enig om å se nærmere på de forskjellige beskrivelsene av mappetype. Begrepet mappetype ser vi brukt en par ganger i Noark 5 standarden. (Utdraget under er fra n5v4):

    I denne versjonen av Noark 5 blir bare Mappe og spesialiseringene Saksmappe og Møtemappe spesifisert. Men det er mulig å lage en rekke andre spesialiserte mappetyper med utgangspunkt i Mappe eller Saksmappe. Mange av disse er kjent også fra løsninger basert på Noark-4: ansettelsessak, byggesak, møte/utvalgssak, delingssak, plansak, landbrukssak osv. Noen av disse mappetypene vil bli spesifisert i en senere versjon av Noark 5.

Videre ser vi i krav 5.4.8 en antydning til en attributt som heter mappetype:

    For et sakarkiv skal det kunne benyttes en spesialisert mappetype: Saksmappe. En spesialisert klasse kan betegnes som en utvidelse av hovedklassen

men så vidt jeg vet finnes det ikke i XSD, eller i  metadatakatalogene. 

Fra [metakat](http://arkivverket.metakat.no/Objekttype/Index/EAID_BEB30D94_3115_4526_9F00_D05A2BFD27CF) så står det:

       angir mappetype som blant annet kan brukes som hint til hva som ligger i virksomhetsspesifikkemetadata

I [GI standarden](https://geointegrasjon.no/images/stories/rapporter/geointegrasjon_grensesnitt_mot_arkiv_v1.1.pdf) er det beskrevet på følgende måter

    sak.mappetype.kodeverdi = "bygg.enkel"

Side 38 har en tabell der mappetype ser ut til å være en kodeverdi,

     mappetype.kodeverdi saType Sakstype

Her  står det videre at:

     Denne angir normalt hvilken prosess saken skal gjennom. Gyldige koder avhenger av oppsett sak/arkiv. Standardverdi: Defineres av angitt fagsystem på saksmappe/journalpost eller oppsett sak/arkiv

Det som er interessant med beskrivelsen over er at her får mappetype en klar bruksområde i henhold til funksjonalitet. Det virker som mappetype *angir prosessen saken skal gjennom*. Dette kan ha noe å si for avskrivning og dokumentflyt.

Mappetype er identifisert som en kodeverdi, både i tjenestegrensesnittet  og GI.

## Diskusjon

Det slår meg som interessant her er at GI virker å blande virksomhetsspesifikkemetadata og mappetype. Jeg mener disse to tingene er seperate ting. Virksomhetsspesifikkemetadata er tilleggsmetadata mens en mappetype feks *barnevernsmappe* er en egen spesialisering av mappe / saksmappe. Når det er sagt er det ingen som har tatt seg bry til å utvikle disse spesialiseringene så vi kan like så godt bruke virksomhetsspesifikkemetadata framfor spesialiseringer.

Virksomhetsspesifikkemetadata gjør at klienten / kunden / forvaltningsorganet blir mer i kontroll av hva som settes inn i arkivet, mens med spesialisering av mappetype er man kanskje mer avhengig av å involvere leverandør for å få til en integrasjon. 

Selv mener jeg at spesialiseringer er veien å gå, men når ingen tar seg tid til å gjøre det må vi bruke virksomhetsspesifikkemetadata som en nødløsning. 

Spørsmålet som vi diskuterte er vel egentlig hvorvidt vi trenger mappetype eller ikke. Et argument mot mappetype er at bruken av mappetype kan på en måte blande seg inn i den teknologi uavhengige datamodellen til Noark og gir et hint at relasjonsdatabaser skal brukes. Argumenter for å inkludere mappetype er at det er i bruk i GI, at det kanskje har en rolle i forhold til definisjon av prosessen en mappe skal gjennom og at flere systemer i dag antageligvis bruker det.

Jeg mener tjenestegrensesnittet skal beholde mappetype. Attributtet bør være obligatorisk da vi fort kan få kompatibilitetsproblemer dersom noen bruker det aktiv mens andre ikke gjør det.  

Hvis dere er enig så blir løsningen å lage en beskrivelse av attributtet ut ifra det som står over her og beskrivelsen tas  inn i tjenestegrensesnittet.

**Comment by petterreinholdtsen** [comment]
[Thomas Sødring]
> Jeg mener tjenestegrensesnittet skal beholde mappetype. Attributtet
> bør være obligatorisk da vi fort kan få kompatibilitetsproblemer
> dersom noen bruker det aktiv mens andre ikke gjør det.

Jeg er enig i at tjenestegrensesnittet bør beholde mappetype.  I tillegg
bør Noark 5 innføre mappetype slik at verdien kan avleveres.

Jeg er derimot litt usikker på hva du mener med obligatorisk i
tjenestegrensesnittet.  Kan du forklare litt nærmere?  Den bør jo ikke
være obligatorisk i Noark 5, så hvordan kan vi gjøre den obligatorisk i
tjenestegrensesnittet?

En i de er å gjøre den obligatorisk med en forvalgt verdi.  Jeg mener
her at attributten får verdien 'mappe' for mapper og 'saksmappe' for
saksmapper med mindre en annen verdi angis?

-- 
Vennlig hilsen
Petter Reinholdtsen

**Comment by petterreinholdtsen** [comment]
En ting som har slått meg rundt mappetype, er at hvis den skal brukes til å indikere hvilke virksomhetsspesifikke metadataverdier som forventes å være på en gitt mappe, så kan en jo like enkelt definere en virksomhetsspesifikke metadataverdi for mappetype, og se etter denne for å vite hvilke andre virksomhetsspesifikke metadataverdier som er aktuelle.  En kan dermed klare seg godt uten mappetype som attributt i mappe-entiteten.

**Comment by hanber** [comment]
Jeg ser vi har mange slike "typer" i ulike objekttyper. Noen er helt nødvendige, bl.a. _journalposttype_ som bl.a. bestemmer reglene for behandling av journalpostene. Denne har faste verdier og kan ikke utvides. Jeg vet ikke hvordan journalposter med _journalposttype_ "Saksframlegg" siden det bare er mulig med én verdi. De fleste andre er mer eller mindre valgfrie og benyttes sikkert forskjellig for å si noe om hvordan sakene (i sakarkiv) skal behandles.

Jeg synes det hadde vært mye bedre om vi hadde hatt en _mappetype_ og en _registreringstype_ på hhv. _mappe_ og _registrering_ som kan brukes som man vil, og redusere antall "type"-metadata så langt som mulig.

Jeg synes derfor vi skal innføre begge disse. Jeg vet ikke hvordan kravene er i dag, men det burde være et krav om beskrivelse av hva alle mappetyper og registreringstyper brukes til, med beskrivelser av alle mulige verdier de kan ha - hva betyr de og hvordan brukes de.

Derfor synes jeg vi skal beholde _mappetype_, men legge den i mappe, og innføre _registreringstype_ i _registrering_. Da blir vi både bakover-kompatible og kan begynne et oppryddingsarbeid.

**Comment by petterreinholdtsen** [comment]
Jeg er enig i at det er bedre å ta den ut inntil N5 er endret til å inneholde feltet.
