### ISSUE TITLE
Kun ASCII-tegn i kodeliste-koder?

### ISSUE THREAD

**Issue by petterreinholdtsen** [arkivverket/noark5-tjenestegrensesnitt-standard#246]
------------------  ---------------------------------
           Prosjekt  NOARK 5 Tjenestegresesnitt
           Kategori  Versjon 1.0 beta
        Alvorlighet  kommentar
       Meldingstype  trenger klargjøring
    Brukerreferanse  pere@hungry.com
        Dokumentdel  7.2.2.27 (SakspartRolle)
         Sidenummer  186
        Linjenummer  n/a
 ------------------  ---------------------------------

### Beskrivelse

I siste versjon av spesifikasjonen har SakspartRolle byttet navn til PartRolle, men har samme verdier som i beta 1.0.

Under testing møter jeg endel ekstra utfordringer når kodeliste-koder ikke består kun av ASCII-tegn.  Det er et eneste slikt tilfelle i spesifikasjonen, for SakspartRolle/PartRolle, der kodeverdien 'PÅ' er brukt.  Kan denne endres til 'PAA' i stedet?

Jeg er fullt klar over at det ikke er noen tungtveiende tekniske grunner til dette, da en i prinsippet bør kunne akseptere et hvilket som helst tegnsett i kodeverdier, men tenker også det gjør livet litt enklere for utviklere hvis vi begrenser oss til ASCII i kode-verdier.

## Ønsket endring

Endre kodeliste-tabell på side 186, bytt ut 'PÅ' med 'PAA'.

**Comment by tsodring** [comment]
Jeg er enig med argumentasjonen din. Det er kode som er 'PÅ' , ikke kodenavn. Dette er ikke noe en bruker vil se så det har ikke noe å se. Jeg opplever ikke kode 'PÅ' som data, og en 'å' gjør det litt vanskeligere for utviklere med utenlandske tastaturer å jobbe med dette,
