### ISSUE TITLE
Endre 'multipl.' til 'forekomster' i tråd med Noark 5 metadatakatalog?

### ISSUE THREAD

**Issue by petterreinholdtsen** [arkivverket/noark5-tjenestegrensesnitt-standard#251]
------------------  ---------------------------------
           Prosjekt  NOARK 5 Tjenestegresesnitt
           Kategori  Versjon 1.0 beta
        Alvorlighet  kommentar
       Meldingstype  trenger klargjøring
    Brukerreferanse  pere@hungry.com
        Dokumentdel  7
         Sidenummer  n/a
        Linjenummer  n/a
 ------------------  ---------------------------------

### Beskrivelse

I metadatakatalogen til Noark 5 så er feltet som viser antall forekomster av en gitt datatype kalt 'forekomster'.  I tjenestegrensesnitt-spesifikasjonen er tilsvarende ferdi navngitt 'multipl.'.  Jeg foreslår at API-spesifikasjonen bruker samme navn som metadatakatalogen.

## Ønsket endring

Endre alle slike henvisninger i teksten fra multiplisitet til forekomst.

**Comment by tsodring** [comment]
Dette er et uproblematisk endring synes jeg. Det handler om å være mer konsekvent i navngiving. Jeg støtter forslaget ditt.

**Comment by petterreinholdtsen** [comment]
Så vidt jeg kan se er det et avsnitt i starten av kapittel 7 samt en rekke tabelltitler som skal endres.  Jeg skal få gjort endringen.
