### ISSUE TITLE
Bytt navn på oppdatert* til endret*

### ISSUE THREAD

**Issue by petterreinholdtsen** [arkivverket/noark5-tjenestegrensesnitt-standard#255]
------------------  ---------------------------------
           Prosjekt  NOARK 5 Tjenestegresesnitt
           Kategori  Noark 5.5.0 TG versjon 1.0
        Alvorlighet  kommentar
       Meldingstype  trenger klargjøring
    Brukerreferanse  pere@hungryc.om
        Dokumentdel  7.2.1.3 (Arkivenhet)
         Sidenummer  76
        Linjenummer  1335
 ------------------  ---------------------------------

### Beskrivelse

Tjenestegrensesnittet har introdusert tre attributter oppdatertDato, oppdatertAv og referanseOppdatertAv som skal oppdateres automatisk.  Disse finnes ikke i metadatakatalogen eller i arkivstruktur.xsd.  Derimot finnes det to verdier i metadatakatalogen og endringslogg.xsd som heter endretDato og endretAv.  Disse virker å ha overlappende formål og det virker som en god ide å slå dem sammen.  For å gjenbruke navn fra de offsielle XSD-ene, foreslår jeg at vi bytter til endretDato, endretAv og referanseEndretAv.

## Ønsket endring

Endre attributtnavn i Arkivenhet fra oppdatertDato, oppdatertAv og referanseOppdatertAv til endretDato, endretAv og referanseEndretAv og oppdater beskrivelse til å henvise til metadatakatalogverdiene som brukes i endringslogg.xsd.

**Comment by petterreinholdtsen** [comment]
Dette ble diskutert på dagens videomøte, og vi er enige om at navneendringen er fornuftig og vi går for ordet endret som allerede er i bruk i Noark 5.

**Comment by monadani** [comment]
Disse 3 er hentet fra Noark 5 versjon 4.0: oppdatertDato, oppdatertAv og referanseOppdatertAv

**Comment by monadani** [comment]
Noark har endretDato og endretAv. Mangler referanseEndretAv, så den må inn som NY i N.5.5.1

**Comment by petterreinholdtsen** [comment]
[Mona Danielsen]
> Disse 3 er hentet fra Noark 5 versjon 4.0: oppdatertDato, oppdatertAv
> og referanseOppdatertAv

Sjekket, og tror du tenker på opprettetDato og opprettetAv
(referanseOpprettetAv finnes ikke) i Noark 5 versjon 4.0.

> Noark har endretDato og endretAv. Mangler referanseEndretAv, så den må
> inn som NY i N.5.5.1

Enig.  M682 endretDato og M683 endretAv er på plass i 5.5.0, men ingen
referanseEndretAv.  Kanskje sistnevnte også bør inn i attributtlisten
for endringslogg?

Tenker det kan være lurt om endret* også legges inn som valgfrie (aka
0..1) i mange av arkivenhetene i Noark 5 og tilhørende XSD, for de samme
som har disse attributtene i tjenestegrensesnittet, slik at en kan
utveksle alt fra tjenestegrensesnittet mellom to databaser ved hjelp av
XML-formatet. :)

-- 
Vennlig hilsen
Petter Reinholdtsen

**Comment by hanber** [comment]
Jeg skjønner ikke hvorfor oppdatertDato, oppdatertAv og referanseOppdatertAv er forsvunnet etter versjon 4.0.
1. Jeg er enig i at det bør være det samme i standarden og tjenestegrensnittet. det er viktigst.
2. Jeg ville foretrukket oppdatertDato, oppdatertAv og referanseOppdatertAv, siden disse har vært brukt før.
3. Det er mulig de nye "endret"-elementene benyttes (midlertidig) for å sikre konsistens ved oppdatering via API-et, som en slags transaksjonshåndtering. Det er i så fall noe annet enn "oppdatert"-elementene.

**Comment by petterreinholdtsen** [comment]
[Hans Fredrik Berg]
> Jeg skjønner ikke hvorfor oppdatertDato, oppdatertAv og
> referanseOppdatertAv er forsvunnet etter versjon 4.0.

Hvor i versjon 4.0 (hvilken versjon 4.0?) er det oppdatertDato,
oppdatertAv og referanseOppdatertAv er nevnt?

> 2. Jeg ville foretrukket oppdatertDato, oppdatertAv og
> referanseOppdatertAv, siden disse har vært brukt før.

Hvor har disse vært brukt før?  Jeg klarte ikke finne dem.  Det ser for
meg ut som de ble introdusert i tjenestegrensesnittet, i parallel med
endretDato og endretAv (i endringslogg).

> 3. Det er mulig de nye "endret"-elementene benyttes (midlertidig) for
> å sikre konsistens ved oppdatering via API-et, som en slags
> transaksjonshåndtering. Det er i så fall noe annet enn
> "oppdatert"-elementene.

Jeg mistenker du her tenker på ETag, som er mekanismen som brukes for å
unngå konflikter ved endring.

-- 
Vennlig hilsen
Petter Reinholdtsen

**Comment by hanber** [comment]
Du har helt rett. Her er vi utsatt for dårlig versjonshåndtering. Det ser ut som de metadataene jeg tenker på er definert i en arbeidsversjon av metadatakatalogen, som er her: [Metadatakatalog.docx](https://github.com/arkivverket/noark5-tjenestegrensesnitt-standard/files/4415422/Metadatakatalog.docx).
Beklager.

**Comment by monadani** [comment]
Noark 5.5.0 issue nr 55 må løses og tas inn først, så kan API issue 255 tas etterpå

**Comment by petterreinholdtsen** [comment]
https://github.com/arkivverket/noark5-standard/issues/55 er nå løst, og navneendringen er delvis gjennomført f9189bffd4fd7da7482711f27e1ffc3552d90bb5 .  Jeg har oppdatert #259 til å fikse de resterende plassene i spesifikasjonen som må endres.
