### ISSUE TITLE
Hvordan gjøres SystemdID unik og persistent på tvers av andre systemer?

### ISSUE THREAD

**Issue by petterreinholdtsen** [arkivverket/noark5-tjenestegrensesnitt-standard#26]
Dette er en kopi av mangelmelding sendt inn til Arkivverket, se også https://github.com/petterreinholdtsen/noark5-tester/blob/master/mangelmelding/sendt/2017-04-06-systemid-unik.md .

 ------------------  ---------------------------------
           Prosjekt  NOARK 5 Tjenestegresesnitt
           Kategori  Versjon 1.0 beta
        Alvorlighet  protest
       Meldingstype  utelatt
    Brukerreferanse  pere@hungry.com
        Dokumentdel  6.3
         Sidenummer  28
        Linjenummer  n/a
    Innsendingsdato  2017-04-06
 ------------------  ---------------------------------

Beskrivelse
-----------

I følge del 6.3 (Identifikatorer) skal arkivkjernen sørge for at systemID blir en unik og persistent identifikator på tvers av andre systemer.  Men hvordan skal dette gjøres uten sentral koordinering? En enkelt leverandør kan jo ikke garantere at ingen andre lager ID-er som får samme verdi som det leverandøren selv lager.  Slik teksten står i dag i spesifikasjonen kan jo én leverandør velge UUID og en annen velge en annen algoritme som gir samme verdier som leverandøren som bruker UUID, uten å vite om hverandre.  Er det meningen at leverandørene skal koordinere seg imellom for å unngå ID-kollisjoner uten sentralisert styring?  Holder det at det er liten sjanse for kollisjoner, ved å bruke for eksempel tilfeldig UUID slik det er definert i [IETF RFC 4122](http://www.ietf.org/rfc/rfc4122.txt), ISO/IEC 9834-8:2004 og ITU-T Rec. X.667?

I så fall, bør systemID avledes fra verdier i objektet det henviser til, eller bør det være frakoblet dette?  Svaret på dette spørsmålet avgjør hvilken algoritme fra RFC 4122 som er aktuell hvis en skal lage en UUID.  Det kan være problematisk å avlede systemID fra verdier i objektet den omhandler hvis objekter med samme innhold skal ha ulik systemID.

Hvis ikke UUID foreslås, så bør det beskrives en annen metode som sikrer at leverandører er i stand til å velge unike ID-er som ikke gir ID-kollisjoner.

Ønsket endring
--------------

Foreslå tilfeldig UUID som akseptabel systemID-verdi ved å legge inn følgende under 6.3 på side 28:

> En mulig måte å lage systemID-verdier er å følge UUID-algoritmen
> beskrevet i [IETF RFC 4122](http://www.ietf.org/rfc/rfc4122.txt),
> ISO/IEC 9834-8:2004 og ITU-T Rec. X.667.  Slike UUID-verdier bør
> være frakoblet verdiene i objektet det henviser til.

**Comment by henningjensen** [comment]
Øivind Kruse
10 months ago

Fra metadatakatalogen M001 SystemID Definisjon: "Entydig identifikasjon av arkivenheten innenfor det arkivskapende organet. Dersom organet har flere arkivsystemer, skal altså systemID være gjennomgående entydig" Det trenger altså ikke være UUID, så lenge den er unik innenfor organet. Et annet spørsmål er om det burde vært det.

**Comment by hanber** [comment]
Jeg synes ikke vi skal stille andre krav til systemID enn at den skal være en tekststreng som er entydig (i den grad UUID-er er det) og persistent innenfor det arkivskapende organet, altså på tvers av uttrekk (perioder) og systemer. Jeg foreslår at vi legger til endringsønsket fra @petterreinholdtsen som et eksempel, forslag eller anbefaling.
Siden systemID først og fremst blir benyttet til sammenligning, er det ikke så viktig hvordan den er representert (f.eks. hex) eller formatert (f.eks. med mellomrom eller streker), men vi kan gjerne komme med en anbefaling til det også.
Vi har i utgangspunktet ikke tenkt at systemID skal inneholde noen semantikk.
For å slippe å utlede en globalt entydig identifikator ved sammenstilling på tvers av arkivskapere, kunne vi kreve globalt unike identifikatorer. Jeg antar at det er like lett for en leverandør å generere en UUID som en annen unik identifikator.

**Comment by hanber** [comment]
Selv om Noark 5.5 er gjeldende med gammel ordlyd om systemID, ønsker vi å endre dette til at systemID skal være en UUID i fremtiden. Siden en UUID også tilfredsstiller kravet i Noark 5.5, gjør vi det slik i tjenestegrensesnittet.
Øivind: er du enig i det? Vi spør Ragnar, Harry og Dimitar om de har motforestillinger. Assigner denne til Øivind.

**Comment by hanber** [comment]
Fra Ragnar:
For Noark 5 tjenestesnitt kan det være OK, men Noark 4-kompatibel system-ID vil fortsatt være nødvendig p.g.a. GeoIntegrasjon og andre grensesnitt.

Jeg er derfor litt skeptisk til å gjøre en «kjapp fiks». Dette må vurderes opp mot bruk i forskjellige integrasjoner.

**Comment by hanber** [comment]
Fra Dimitar:
Hi all. I think it should be mandatory that systemID contains a UUID in Noark 5.5 systems because that is an easy way to guarantee global uniqueness of the identifier and use it beyond the scope of the current system. It is also possible to rename systemID to e.g. uuid so that the field name is more recognizable by developers integrating with Noark systems.

**Comment by hanber** [comment]
Da synes det som at vi tar inn kravet om UUID i versjon 5.5.

**Comment by hanber** [comment]
Fra Harry!
Hei, har sjekket litt med våre utviklere, og bruk av UUID hos Visma vil ikke være noe problem. Vi håndterer kun Noark5-standarden.
