### ISSUE TITLE
Bytt ut 'åpen kodeliste' i beskrivelse av kodelister med noe mer forklarende.

### ISSUE THREAD

**Issue by petterreinholdtsen** [arkivverket/noark5-tjenestegrensesnitt-standard#263]
------------------  ---------------------------------
           Prosjekt  NOARK 5 Tjenestegresesnitt
           Kategori  Noark 5.5.0 TG versjon 1.0
        Alvorlighet  kommentar
       Meldingstype  trenger klargjøring
    Brukerreferanse  pere@hungry.com
        Dokumentdel  7.2.2
         Sidenummer  127
        Linjenummer  1817
 ------------------  ---------------------------------

### Beskrivelse

Noen kodelister har nøkkelordene 'åpen kodeliste', andre har det ikke.  Jeg tror dette betyr at arkivansvarlig kan definere sine egne kodelisteverdier, mens for de øvrige er listen over kodelisteverdier "låst" i følge Noark 5.

Men når jeg sammenligner med GeoIntegrasjons kodelister, der det er to typer kodelister, så virker det som om det ikke er de samme kodelistene som er uten standardverdier der som er 'åpen kodeliste' der.

Uansett bør formuleringen 'åpen kodeliste' byttes ut med noe som forklarer bedre hva som gjelder for den aktuelle kodeliste.  Hva med 'Arkivskaper velger selv tilgjengelige verdier.  Den oppgitte listen er enbefalinger.' der det står 'åpen kodeliste' i dag, og 'Kodelisten er bestemt av Noark 5 og kan ikke endres av arkivskapes' der det ikke står noe?

## Ønsket endring

Endre formulering i beskrivelse av alle kodelister, og sjekk at hver kodeliste har riktig klassifisering.

**Comment by hanber** [comment]
Det kan virke litt forvirrende at det i metadatakatalogen opereres med "obligatoriske" verdier (enumeration). Jeg mener det kan oppfattes på flere måter.

1. Obligatoriske verdier betyr at det er et krav til Noark-løsninger at det skal være mulig å tilordne disse verdiene og bare disse.
2. Obligatoriske verdier betyr at det er et krav til Noark-løsninger at det skal være mulig å tilordne disse verdiene, men det er også mulig å tilordne andre verdier.

Noen krav i Noark refererer til bestemte verdier av bestemte metadataelementer, da må nødvendigvis disse verdiene kunne tilordnes, altså være obligatoriske. Dette gjelder bl.a. for svært mange statusverdier.

For alle andre obligatoriske verdilister er det slik jeg ser det ingen ting i veien for at de kan utvides med ikke-obligatoriske verdier, så lenge meningen med de obligatoriske er den samme. For eksempel har _dokumentstatus_ de obligatoriske verdiene "Dokumentet er under redigering" og "Dokumentet er ferdigstilt". Da bør det ikke være noe i veien for at man kan forfine "Dokumentet er under redigering" til "Utkast", "Til kommentering", "Til høring", "Til godkjenning" e.l. dersom man har rutiner for dokumenthåndteringen som er mer detaljert. Alle disse verdiene faller inn under "Dokumentet er under redigering".
På den annen side er det knyttet krav til verdien "Dokumentet er ferdigstilt", slik at den verdien må benyttes. I dette tilfellet synes jeg bare "Dokumentet er ferdigstilt" burde vært obligatorisk.

Når det gjelder ikke-obligatoriske verdiene, oppfatter jeg dem først og fremst som forslag til standardisering.

Jeg foreslår en gjennomgang av alle verdisettene for å identifisere hvilke verdier som er knyttet til krav i standarden og gjøre disse obligatoriske.

Det hadde også vært fint om lister med ikke-obligatoriske verdier kunne vært vedlikeholdt i Github, med en verdi og en forklaring på hva verdien betyr. Hver gang en leverandør vil benytte en spesiell verdi, kan denne lista konsulteres for å finne ut om noen allerede har definert denne verdien før leverandøren innfører et nytt.

**Comment by petterreinholdtsen** [comment]
Dette ble diskutert på dagens redaksjonsmøte.  Foreslår at 'åpen kodeliste' byttes ut med følgende over alt der det forekommer:

> Kodelisteverdiene listet i tabellen under må kunne benyttet ved oppretting og endring av instanser.  I tillegg skal det være støtte for å legge inn flere verdier ved bruk av ny-relasjonslenke.

**Comment by petterreinholdtsen** [comment]
I dag er det tre kodelister i spesifikasjonen som ikke nevner 'åpen kodeliste'.  Det er Journalstatus, Land og Postnummer.  Mistenker alle disse også skal kunne få ekstra verdier etter hvert som verden endrer seg.
