### ISSUE TITLE
Velg en av 'utdatert' og 'inaktiv'

### ISSUE THREAD

**Issue by petterreinholdtsen** [arkivverket/noark5-tjenestegrensesnitt-standard#268]
------------------  ---------------------------------
           Prosjekt  NOARK 5 Tjenestegresesnitt
           Kategori  Noark 5.5.0 TG versjon 1.0
        Alvorlighet  protest
       Meldingstype  trenger klargjøring
    Brukerreferanse  pere@hungry.com
 ------------------  ---------------------------------

### Beskrivelse

Jeg la merke til at spesifikasjonen har to ulike navn på identiske konsepter, henholdsvis 'utdatert' i virksomhetsspesifikkeMetadata og 'inaktiv' i kodelister.  Det bør brukes samme navn på disse, for å få en mer konsistent spesifikasjon.

## Ønsket endring

Usikker på hvilke av disse som er best, men tenker 'utdatert' er bedre norsk enn 'inaktiv', og foreslår at den brukes.

**Comment by petterreinholdtsen** [comment]
Det kan forresten være verdt å nevne forslaget i https://github.com/arkivverket/noark5-standard/issues/95 om å ikke bruke en boolsk verdi for gjeldende/inaktiv/utdatert, men heller notere tidspunktet for når verdien ikke lenger er gyldig, og sammenligne med dagens dato for å finne ut om det er greit å bruke koden/navnet.

**Comment by petterreinholdtsen** [comment]
I dag brukes Utdatert: YYYY-MM-DD for å markere når en metadatakatalogoppføring ikke lenger var gjeldende i Noark 5, se for eksempel https://github.com/arkivverket/noark5-standard/blob/master/metadata/M009.yaml .  Basert på det foreslår jeg å endre definisjonen på kodelister og virksomhetsspesifikkeMetadata til å bruke 'utdatert' som et datofelt som kan være tomt for å markere om verdier er gjeldende eller ikke.

**Comment by tsodring** [comment]
Jeg er enig at vi ikke skal ha to begreper for samme ting.
