### ISSUE TITLE
Mangler informasjon om plassering av metadata-relasjonsnøkkel

### ISSUE THREAD

**Issue by petterreinholdtsen** [arkivverket/noark5-tjenestegrensesnitt-standard#276]
------------------  ---------------------------------
           Prosjekt  NOARK 5 Tjenestegresesnitt
           Kategori  Noark 5.5.0 TG versjon 1.0
        Alvorlighet  protest
       Meldingstype  utelatt
    Brukerreferanse  pere@hungry.com
        Dokumentdel  kapittel 6
         Sidenummer  n/a
        Linjenummer  n/a
 ------------------  ---------------------------------

### Beskrivelse

I kapittel syvs del om kodelister står det "Når en gjør GET mot href til relasjonsnøkkel https://rel.arkivverket.no/noark5/v5/api/metadata/, så returneres liste over relasjonsnøkler til de ulike entitetene som er tilgjengelig."  Men så vidt jeg klarer se fra dagens spesifikasjonstekst står det ingen steder hvor relasjonsnøkkelen skal gjøres tilgjengelig.  Det bør gjøres entydig klart for å sikre at alle implementasjoner er forutsigbare og klienter vet hvor de skal finne kodelistene. Det mest naturlige er å gjøre den tilgjengelig på toppnivå, parallellt med relasjonsnøklene til arkivstruktur og sakarkiv.  Dette er der Nikita har gjort relasjonen tilgjengelig i dag.

## Ønsket endring

Foreslår at relasjonslenken legges inn i eksemplet i kapittel 6 og listen over relasjonslenker på toppnivå, dvs. slik:

```
diff --git a/kapitler/06-konsepter_og_prinsipper.rst b/kapitler/06-konsepter_og_prinsipper.rst
index d7153f4..1a855bb 100644
--- a/kapitler/06-konsepter_og_prinsipper.rst
+++ b/kapitler/06-konsepter_og_prinsipper.rst
@@ -64,6 +64,9 @@ Content-Type: application/vnd.noark5+json
            "https://rel.arkivverket.no/noark5/v5/api/arkivstruktur/": {
                "href": "https://n5.example.com/api/arkivstruktur"
            },
+           "https://rel.arkivverket.no/noark5/v5/api/metadata/": {
+               "href": "https://n5.example.com/api/metadata"
+           },
            "https://rel.arkivverket.no/noark5/v5/api/sakarkiv/": {
                "href": "https://n5.example.com/api/sakarkiv"
            },
@@ -110,6 +113,8 @@ relevant for denne relasjonsnøkkelen.
 
  * - Relasjonsnøkkel (rel)
    - Beskrivelse
+ * - https://rel.arkivverket.no/noark5/v5/api/metadata/
+   - Tilgjengelige kodelister.
  * - https://rel.arkivverket.no/noark5/v5/api/arkivstruktur/
    - Arkivkjerne støtter konformitetsnivå 1 arkivstruktur
  * - https://rel.arkivverket.no/noark5/v5/api/sakarkiv/
```

**Comment by tsodring** [comment]
Enig og dette er helt uproblematisk å ta inn.
