### ISSUE TITLE
Feil forekomstinformasjon fra Skjerming til Skjermingmetadata

### ISSUE THREAD

**Issue by petterreinholdtsen** [arkivverket/noark5-tjenestegrensesnitt-standard#277]
------------------  ---------------------------------
           Prosjekt  NOARK 5 Tjenestegresesnitt
           Kategori  Noark 5.5.0 TG versjon 1.0
        Alvorlighet  protest
       Meldingstype  trenger klargjøring
    Brukerreferanse  pere@hungry.com
        Dokumentdel  kapittel 7 del Skjerming
         Sidenummer  n/a
        Linjenummer  n/a
 ------------------  ---------------------------------

### Beskrivelse

Dagens spesifikasjon lister opp forekomstinformasjon [0..*] for Skjerming sin Skjermingmetadata.  Men i Noark 5-spesifikasjonen og tilhørende XML-skjema er det ført opp forekomst [1..*].  Det virker naturlig at hvis alt skal skjermes, så trenger en ikke spesifisere skjermingsmetadata, men jeg kan ta feil her.  Hvis en også må oppgi Skjermingmetadata når en hel instans er skjermet, så bør nok forekomstinformasjonen i TG endres til [1..*].

## Ønsket endring

Avklare hva som er riktig forekomst for Skjermingmetadata.  Mistenker denne endringen er ønskelig:

```
diff --git a/kapitler/07-tjenester_og_informasjonsmodell.rst b/kapitler/07-tjenester_o
g_informasjonsmodell.rst
index c20097f..34a49dd 100644
--- a/kapitler/07-tjenester_og_informasjonsmodell.rst
+++ b/kapitler/07-tjenester_og_informasjonsmodell.rst
@@ -3992,7 +3992,7 @@ den enkelte mappe, registrering eller det enkelte dokument. (Se 
Noark
      og journalpost.  Ved midlertidig skjerming skal alle metadata
      ovenfor skjermes, må bare brukes inntil skjermingsbehovet er
      vurdert. M502
-   - [0..\*]
+   - [1..\*]
    -
    - SkjermingMetadata
  * - skjermingDokument
```

**Comment by tsodring** [comment]
Er dette relatert til [denne](https://github.com/arkivverket/noark5-standard/issues/128)?

**Comment by petterreinholdtsen** [comment]
[Thomas Sødring]
> Er dette relatert til
> [denne](https://github.com/arkivverket/noark5-standard/issues/128)?

Mistenker det, ja, men litt på siden.  Takk for tipset.

Mitt utgangspunkt er at et skjermet dokument alltid må ha minst en verdi
i Skjermingmetadata, som forklarer hva som er skjermet.  Jeg antar det
er årsaken til at XSD har forekomstinfo [1..*] og ikke [0..*].

-- 
Vennlig hilsen
Petter Reinholdtsen
