### ISSUE TITLE
På tide å gi ut en oppdatert utgave av spesifikasjonen?

### ISSUE THREAD

**Issue by petterreinholdtsen** [arkivverket/noark5-tjenestegrensesnitt-standard#279]
Den siste stemplede utgaven av spesifikasjonen ble annonsert i 2019.  Er det på tide å annonsere en ny utgave?  Jeg tror det er lurt, for å få med de siste korreksjonene og samkjøringene med Noark 5-spesifikasjonen.

**Comment by tsodring** [comment]
Selv om RA har valgt å satse på andre tilnærminger enn Noark standarden så er faktisk viktig at de følger opp det ansvaret de har med standarden. Det gjelder både TG og selve standarden. Jeg er enig med deg Petter. Det meste av det som kom etter 1.0 er presisering/polering og det er i tråd med en "minor"-nummer utgivelse.

**Comment by petterreinholdtsen** [comment]
Kapittel 1 henviser til github for å se hva som er gjort av endringer siden 1.0.  Bør vi i tillegg lage en tekstlig oversikt over de viktigste endringene?

**Comment by tsodring** [comment]
Enig at det er på tide å få stemplet en ny versjon. Uoh-prosjektet viser hvor viktig det er å stemple en versjon og å få ryddet opp i uklarheter dersom de finnes. 

Jeg tror også det er lurt å angi forskjellen fra 1.0 til 1.1 på en mer overordnet nivå. For det meste har det vært å ryddig opp i uklarheter, formatering / bilder opprydding og ny funksjonalitet. Det er greit at det er lett for en leser å skjønne hva som er endret, men det er kanskje lurt å stadfeste ny funksjonalitet.

**Comment by petterreinholdtsen** [comment]
[Thomas Sødring]
> Jeg tror også det er lurt å angi forskjellen fra 1.0 til 1.1 på en mer
> overordnet nivå. For det meste har det vært å ryddig opp i uklarheter,
> formatering / bilder opprydding og ny funksjonalitet. Det er greit at
> det er lett for en leser å skjønne hva som er endret, men det er
> kanskje lurt å stadfeste ny funksjonalitet.

Foreslår at slik overordnet beskrivelse tas inn i endringsloggen på side
3 (1.3 Endringslogg for dette dokumentet).  Utfordringen er hvem som
skal skrive og hvor detaljert vi skal skrive det.

-- 
Vennlig hilsen
Petter Reinholdtsen

**Comment by oleaamot** [comment]
Dette er en god idé.

**Comment by oleaamot** [comment]
Thomas skriver:

Petter og jeg er veldig glade for å kunne melde at vi, i dag, har stemplet og publisert versjon 1.1 av Noark 5 Tjenestegrensesnittet.

Denne har versjonsnummer 1.1 og det bl.a.  rydder opp i uklarheter i 1.0 spesifikasjonen. 

Selve releasen er tagget her:

 [ https://github.com/arkivverket/noark5-tjenestegrensesnitt-standard/releases/tag/versjon-1.1](https://github.com/arkivverket/noark5-tjenestegrensesnitt-standard/releases/tag/versjon-1.1)

mens en PDF versjon for de som liker det er her:

 [ https://github.com/arkivverket/noark5-tjenestegrensesnitt-standard/blob/master/arkiv/2023-06-09-spesifikasjon-1.1.pdf](https://github.com/arkivverket/noark5-tjenestegrensesnitt-standard/blob/master/arkiv/2023-06-09-spesifikasjon-1.1.pdf)
