### ISSUE TITLE
Uklar beskrivelse om opprettelse av journalpost og bruken av arv

### ISSUE THREAD

**Issue by petterreinholdtsen** [arkivverket/noark5-tjenestegrensesnitt-standard#28]
Dette er en kopi av mangelmelding sendt inn til Arkivverket, se også https://github.com/petterreinholdtsen/noark5-tester/blob/master/mangelmelding/sendt/2017-05-09-opprette-journalpost.md .

------------------- ---------------------------------
           Prosjekt NOARK 5 Tjenestegresesnitt
           Kategori Versjon 1.0 beta
        Alvorlighet protest
       Meldingstype utelatt
    Brukerreferanse thomas.sodring@hioa.no
        Dokumentdel 7.2.3.11
         Sidenummer 239
        Linjenummer n/a
    Innsendingsdato 2017-05-09
------------------- ---------------------------------

Beskrivelse
-----------

Gjelder også side 66, 117 og 131.

Det er uklart fra spesifikasjonen hvordan en journalpost skal opprettes.  Det virker mest fornuftig å tro at følgende HTTP-forespørsel vil kunne opprette en journalpost.

`[contextpath][api]/sakarkiv/saksmappe/{systemID}/ny-journalpost`

Del 7.2.3.11 (Saksmappe) Side 239 viser en liste av relasjoner som hører til saksmappe og der mangler det en relasjon for å opprette en journalpost. Imidlertid ser vi at det er en relasjon

`http://rel.kxml.no/noark5/v4/api/sakarkiv/ny-saksmappe/`

og kanskje denne skulle egentlig være

`http://rel.kxml.no/noark5/v4/api/sakarkiv/ny-journalpost/` ?

Videre ser vi at hvordan journalpost skal opprettes gjøres enda mer uklart med måten arv er håndtert.  Både `mappe/saksmappe` og `registrering/basisregistrering/journalpost` bruker arv og [webbeskrivelsen](http://rel.kxml.no/noark5/v4/api/arkivstruktur/mappe/) viser noe annet enn tjenestegrensesnittet når det gjelder arveforholdet `mappe/saksmappe`.  I webbeskrivelsen er det en relasjon

`http://rel.kxml.no/noark5/v4/utvid-til-saksmappe`

som ikke finnes på listen med relasjon i del 7.2.1.16 (Mappe) på side 131.  Det er heller ikke noe relasjon på arkivdel eller klasse for å opprette en saksmappe, kun mappe.

`http://rel.kxml.no/noark5/v4/api/arkivstruktur/ny-mappe/`

så den virker som om den eneste måten å opprette en saksmappe er å lage en mappe for så å utvide den til saksmappe.  Men dette er ikke spesifisert i tjenestegrensesnitt-spesifikasjonen, men finnes som et 'hint' i webbeskrivelsen.

Hvordan arv håndteres blir enda mer uklart ved at [mappe](http://rel.kxml.no/noark5/v4/api/arkivstruktur/mappe/) har relasjon for å opprette registrering og basisregistrering.

`http://rel.kxml.no/noark5/v4/ny-registrering`

`http://rel.kxml.no/noark5/v4/ny-basisregistrering`

Her brukes ikke utvid-til-* metoden for å opprette basisregistrering eller eventuelt journalpost.

Det er ingen informasjon på http://rel.kxml.no/noark5/v4/api/sakarkiv/journalpost/ og heller ingen
informasjon på http://rel.kxml.no/noark5/v4/api/arkivstruktur/registrering/ om dette.

Vi forstår at dette er noe som kanskje er litt komplisert å få til da grensesnittene for arkivstruktur og sakarkiv vil overlappe hverandre. Dette ser vi også i `Noark 5 Standard for elektronisk arkiv`, versjon
5v4. `Del 5.4 Mappe` (sidenummer mangler i standarden).

Slik vi tolker Tjenestegrensesnitt-spesifikasjonen er det i dag ikke spesifisert hvordan en kan opprette en journalpost koblet til en saksmappe.  Det er viktig at det finnes en tydelig beskrivelse i spesifikasjonen om hvordan en saksmappe og en journalpost skal opprettes.  Det er fordeler og ulemper med utvid-til-* metoden, men det ville gjøre tjenestegrensesnittet enklere å utvikle hvis det var mulig å opprette en saksmappe uten `utvid-til-saksmappe`. Det vil imidlertid kreve at arkivdel og klasse får en relasjon til

`http://rel.kxml.no/noark5/v4/api/sakarkiv/ny-saksmappe/`

Ønsket endring
--------------

Det introduseres en relasjon for å tillate opprettelse av journalpost til en saksmappe på side 131.

`http://rel.kxml.no/noark5/v4/api/sakarkiv/ny-journalpost/`

Det introduseres en relasjon for å tillate opprettelse av en saksmappe til en arkivdel på side 66, Del (7.2.1.2).

`http://rel.kxml.no/noark5/v4/api/sakarkiv/ny-saksmappe/`

Det bør antagelig nevnes i teksten at denne kun skal være tilgjengelig hvis det finnes en `http://rel.kxml.no/noark5/v4/api/sakarkiv/`-relasjon på toppnivå.

Det introduseres en relasjon for å tillate opprettelse av en saksmappe til en arkivdel på side 117, Del (7.2.1.12).

`http://rel.kxml.no/noark5/v4/api/sakarkiv/ny-saksmappe/`

Tilsvarende her bør det nevnes at den kun skal være tilgjengelig hvis det finnes en `http://rel.kxml.no/noark5/v4/api/sakarkiv/`-relasjon på toppnivå.

I del 7.2.3.11 (Saksmappe) side 239 endres relasjon

`http://rel.kxml.no/noark5/v4/api/sakarkiv/ny-saksmappe/`

til

`http://rel.kxml.no/noark5/v4/api/sakarkiv/ny-journalpost/`

**Comment by hanber** [comment]
Jeg overskuer ikke konsekvensen av forslaget, og har derfor ingen mening. NB! Husk at _registrering_ og _basisregistrering_ er slått sammen i _registrering_ i versjon 5. Har spørsmålet nedenfor relevans for endringsønsket?

@oivkru, @monadani og @annknu: Skal det være mulig å blande _mappe_ og spesialiseringer av _mappe_ i mappe-hierarkiet?

**Comment by petterreinholdtsen** [comment]
Beklager uklar beskrivelse av problemet.  Her er et nytt forsøk.  Det er i dag ingen beskrevet måte i spesifikasjonen av tjenestegrensesnittet for å opprette en journalpost knyttet til en saksmappe.  Det er dermed helt i det blå hvordan dette skal gjøres, og forslaget er at dette gjøres på samme måte som alle andre entiteter opprettes, ved å følge en ny-journalpost-entitet.  Hvis dette er måten det skal gjøres på, så må foreslåtte relasjon legges inn i listen over relasjoner knyttet til saksmappe.

Et alternativ er at det finnes en beskrevet måte, og men hverken Thomas eller jeg har klart å finne den.

**Comment by petterreinholdtsen** [comment]
Hvis noen kan forklare hvordan det er ment å fungere, så kan jeg skrive forslag til formulering i spesifikasjonen.  Min anbefaling etter å ha studert spesifikasjon og UML-diagram i flere år nå, er at en går for tilnærmingen med ny-xxx i stedet for utvid-til-xxx, da det gjør opprettingen atomisk, og klienter trenger ikke forholde seg til problemet som oppstår hvis ny-registrering lykkes, mens en av  utvid-til-basisregistrering med påfølgende utvid-til-journalpost feiler.  En kan gjerne i tillegg ha utvid-til-xx hvis det er behov for å kunne utvide.  Jeg ser dog ikke bruksområdet for det i dag.  Kan det være at en oppdager at et dokument som startet som en registrering skal gjøres tilgjengelig i postjournalen?

**Comment by petterreinholdtsen** [comment]
Apropos kommentar fra @hanber om sammenslåing av Registrering og Basisregistrering, så kan det være en ide å slå dem sammen også i dette API-et, se mangelmelding #145.  Det påvirker ikke det fundamentale spørsmål om hvordan underentitetstyper bør opprettes.  Jeg anbefaler ny-<type> i stedet for utvid-til-&lt;type>, for å kunne gjøre det atomisk og redusere kompleksiteten i API-klienter hvis utvid-til-&lt;type> feiler.  Jeg ser kapittel 6 ble utvidet etter 1.0 beta med mer beskrivelse av utvid-til-&lt;type>-tilnærmingen, men ser altså ikke helt bruksområdet der den tilnærmingen er en fordel forran ny-&lt;type>.

**Comment by hanber** [comment]
Vi beholder utvid-til, men benytter ny- ved opprettelse av spesialiseringer.

**Comment by petterreinholdtsen** [comment]
Da er endringsforslag #185 endret til å beholde utvid-til-* samt ikke nevne Møte-relaterte relasjonsnøkler.  Jeg tror dermed denne endringen er i tråd med det vi diskuterte i dag og planlegger da den inn i spesifikasjonen torsdag hvis ingen protesterer.
