### ISSUE TITLE
Avskrivning#referanseAvskrivesAvJournalpost is a *-to-many relation in Noark 5.5

### ISSUE THREAD

**Issue by ivaylomitrev** [arkivverket/noark5-tjenestegrensesnitt-standard#281]
------------------  ---------------------------------
           Prosjekt  NOARK 5 Tjenestegresesnitt
           Kategori  Noark 5.5.0 TG versjon 1.0
        Alvorlighet  kommentar / protest
       Meldingstype  utelatt / trenger klargjøring
    Brukerreferanse  user@example.com
        Dokumentdel  Chapter#7 (Avskrivning)
 ------------------  ---------------------------------

### Beskrivelse

Avskrivning#referanseAvskrivesAvJournalpost (M215) is defined as a *-to-many relation in the Noark 5 standard whereas the specification defines a single (non-array) field for it. This makes it difficult to map to existing systems and might lead to data loss.

## Ønsket endring

Avskrivning#referanseAvskrivesAvJournalpost to be converted to a list of Journalpost entities or to an array of UUIDs.

**Comment by petterreinholdtsen** [comment]
[ivaylomitrev]
> Avskrivning#referanseAvskrivesAvJournalpost is defined as a *-to-many
> relation in the Noark 5 standard

Where do you see this?  In the XSD and appendix B section B.1.13,
B.3.2.6 and B.3.3.6 of the Noark 5 standard it is listed with
multiplicity 0-1, which is the same as is used in the API specification.

If it is wrong, it is wrong in Noark 5 and need to be fixed there first.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by petterreinholdtsen** [comment]
[ivaylomitrev]
> It is a discrepancy in the standard in that case and must be fixed
> there one way or the other. Thank you!

I had a look at it seem to have been fixed in
<URL: https://github.com/arkivverket/noark5-standard/commit/5bfc68bb91a746dcf48f7e41e246baaa259a981c >
the summer of 2021.

-- 
Happy hacking
Petter Reinholdtsen
