### ISSUE TITLE
oData date filter examples discrepancy (v2 vs v4)

### ISSUE THREAD

**Issue by ivaylomitrev** [arkivverket/noark5-tjenestegrensesnitt-standard#283]
------------------  ---------------------------------
           Prosjekt  NOARK 5 Tjenestegresesnitt
           Kategori  Noark 5.5.0 TG versjon 1.0
        Alvorlighet  kommentar / protest
       Meldingstype  utelatt / trenger klargjøring
    Brukerreferanse  user@example.com
        Dokumentdel  Chapter #6 date filter examples
 ------------------  ---------------------------------

### Beskrivelse

The links in Chapter #6 with regard to oData filters refer to oData v 4.01 whereas the actual examples specify filters such as the following:
```
/api/sakarkiv/saksmappe?$filter=saksdato gt DateTime'2017-02-15'
```
which are only relevant for older versions of oData

## Ønsket endring

I assume the examples simply need to be updated to reflect the oData v4 standard.

**Comment by petterreinholdtsen** [comment]
[ivaylomitrev]
> The links in Chapter #6 with regard to oData filters refer to oData v
> 4.01 whereas the actual examples specify filters such as the
> following:
> ```
> /api/sakarkiv/saksmappe?$filter=saksdato gt DateTime'2017-02-15'
> ```
> which are only relevant for older versions of oData

The cast to DateTime seem to be something originating for the early
Arkitektum edition of the specification, and has been in the text since
before 2018.  I guess no-one noticed the problem.  I am not a oData
expert, and hope Thomas who have studied the specification a lot more
than me can chime in here.  Btw, when you state 'older versions of
oData', can you provide references to which versions had this cast notation?

Until the specification is changed version 4.01 is the one it is
supposed to use, so I believe any example in conflict with that version
should be changed, unless there is a very good reason not to, and this
reason need to be written into the specification.

> I assume the examples simply need to be updated to reflect the oData
> v4 standard.

Make sense to me, but I am no oData expert.  Can you provide a pull
request a patch or just a reply with proposed wording for this update?

-- 
Happy hacking
Petter Reinholdtsen

**Comment by tsodring** [comment]
I agree with Petters points. The OData syntax was something that came from the original document, and I don't think we did much to deal with it. We assumed the original examples were correct. 

Of the top of my head, I think the request likely should be rejected with 400 Bad Request as it breaks with the OData syntax description.

It raises a question, though, of how we expect an implementation of the API to behave when searching for a DateTime object using a Date. Perhaps, if the DBMS allows it, then do nothing. If the DBMS does not allow it, capture an exception and throw a Bad Request error. That will, however, not result in similar results across implementations. 

Ultimately, this is something that the OData standard should define. It's not an issue for the API specification unless there are uncertainties in the OData standard. 

I agree that we need to update the OData examples.

**Comment by petterreinholdtsen** [comment]
Just to reiterate, in case my questions were not noticed:

 * When you state 'older versions of oData', can you provide references
   to which versions had this cast notation?
   
 * Can you provide a pull request, a patch or just a reply with proposed
   wording for this update?

-- 
Happy hacking
Petter Reinholdtsen

**Comment by ivaylomitrev** [comment]
I'm sorry. I didn't have time to respond earlier.

> When you state 'older versions of oData', can you provide references to which versions had this cast notation?

It seems that [oData v2](https://www.odata.org/documentation/odata-version-2-0/overview/) is the last version that has the DateTime'literal' syntax
![image](https://user-images.githubusercontent.com/21099109/223965475-0e121e76-2fe8-49f2-8d33-e3524a47ddfd.png)

> Can you provide a pull request, a patch or just a reply with proposed wording for this update?

I will be able to create a patch as early as next week. Should you need that earlier, feel free to go ahead and introduce it.

The change in the examples in Chapter 6 should be from:
```
filter=saksdato gt DateTime'2017-02-15'
```
to
```
filter=saksdato gt 2017-02-15
```
(i.e. without the cast and without wrapping the literal in single quotes)

An example of this can be found in the [OData version 4 URL Conventions (5.1.1.6.1 Primitive literals)](https://docs.oasis-open.org/odata/odata/v4.0/cos01/part2-url-conventions/odata-v4.0-cos01-part2-url-conventions.html#_Toc371343071)

**Comment by ivaylomitrev** [comment]
I have opened a PR with the fix here: https://github.com/arkivverket/noark5-tjenestegrensesnitt-standard/pull/290
