### ISSUE TITLE
Are both kodelister kode and kodenavn required to be returned in responses?

### ISSUE THREAD

**Issue by ivaylomitrev** [arkivverket/noark5-tjenestegrensesnitt-standard#284]
The specification explicitly states that __kode__ is the only _required_ field in _create requests_ (i.e. kodenavn is optional).

Examples for _responses_ include both __kode__ and __kodenavn__, however, and a question arises whether both __must__ be returned in responses or the same principle can be applied as with the create requests and _kodenavn_ can be considered optional in responses?

**Comment by petterreinholdtsen** [comment]
[ivaylomitrev]
> The specification explicitly states that __kode__ is the only
> _required_ field in _create requests_ (i.e. kodenavn is optional).
>
> Examples for _responses_ include both __kode__ and __kodenavn__,
> however, and a question arises whether both __must__ be returned in
> responses or the same principle can be applied as with the create
> requests and _kodenavn_ can be considered optional in responses?

The background for this is in the Noark 5 standard, which dokument that
the value for 'kodenavn' used when a archive entity is created or last
updated is the value that should be extracted to long term storage.  If
the code list entry for a given 'kode' value is updated after after an
instance is archived/finalized, the instance should not inherit the
change, but retain the original value.

Given this requirement, the only way to get the correct code name for an
instance is to return it when asking for the values of the given
instance.  Looking up the code in the code list might return the
incorrect value.

Thus returning _kodenavn_ with each instance is required, not optional.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by ivaylomitrev** [comment]
Thank you for the clarification!
