### ISSUE TITLE
Klargjør kravet om bruk av CORS og Allow i REST-API-et

### ISSUE THREAD

**Issue by petterreinholdtsen** [arkivverket/noark5-tjenestegrensesnitt-standard#29]
Dette er en kopi av mangelmelding sendt inn til Arkivverket, se også https://github.com/petterreinholdtsen/noark5-tester/blob/master/mangelmelding/sendt/2017-05-12-cors.md .

 ------------------  ---------------------------------
           Prosjekt  NOARK 5 Tjenestegresesnitt
           Kategori  Versjon 1.0 beta
        Alvorlighet  protest
       Meldingstype  utelatt
    Brukerreferanse  pere@hungry.com
        Dokumentdel  4
         Sidenummer  9
        Linjenummer  n/a
    Innsendingsdato  2017-05-12
 ------------------  ---------------------------------

Beskrivelse
-----------

Spesifikasjonens vedlegg 1 (Konformitetskrav) på side 267 referer til [http://rel.kxml.no/noark5/konformitetsniva/](http://rel.kxml.no/noark5/konformitetsniva/) som inneholder foreløpig liste med konformitetsnivå.  Websiden lister opp CORS Cross-origin resource sharing som et nivå 0-krav.  Men W3Cs CORS nevnes ikke med et ord i spesifikasjonen.

CORS bør nevnes i spesifikasjonen hvis det er et krav, og den bør forklare nærmere hvilke krav som gjelder relatert til CORS, deriblant hvilken versjon av CORS som kreves.  I skrivende stund er siste utgave datert 2014-01-16.  Demonstrasjonsimplementasjonen tilgjengelig fra http://n5test.kxml.no/api/ støtter ikke HTTP-forespørselen «OPTIONS». Støtte for denne forespørselen er en forutsetning for at CORS skal fungere.  Det er dermed vanskelig å finne ut hva som er tenkt rundt bruken av CORS i tjenestegrensesnittet.  For eksemepel, skal innlogging endre hvilke operasjoner som vises i hodefeltet
«Access-Control-Allow-Methods» alt etter om en bruker har logget inn eller ikke?  Med andre ord, skal kun de som får lov til å slette en entitet får se at «DELETE» er støttet?  I så fall bør det nevnes i
spesifikasjonen at hodefeltet «Authenticate» alltid skal være satt når CORS brukes.  Det er dog uklart om et slikt krav vil fungere, da nettlesere ser ut til å gjøre gjøre sine CORS-kall uavhengig av eventuell innlogging registrert i JavaScript-klientkode.

Et relatert spørsmåler er om GET- og HEAD-responsene alltid skal ha med «Allow»-hodefeltet definert i [IETF RFC 2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html) for å forklare hvilke operasjoner brukeren har tilgang?  Det blir enklere for en API-klient hvis «Allow»-feltet er satt og korrekt for enhver GET- og HEAD-respons.  Det kan dermed være lurt å kreve at OPTIONS ikke krever innlogging og returnerer alle mulige operasjoner for alle brukere, mens GET og HEAD returnerer de operasjonene som er mulig med gjeldende innlogging.

Ønsket endring
--------------

Det bør legges inn en beskrivelse enten under punkt 4 (Teknologi) eller punkt 6 (Konsepter og Prinsipper) som forklarer hva som forventes fra API-et når det gjelder CORS, samt referanse til aktuell
CORS-spesifikasjon.

Her er et forslag som skisserer endel krav, uten mange detaljer.

> Tjenestegrensesnittet skal støtte CORS (Cross-Origin Resource
> Sharing) slik det er beskrevet på https://www.w3.org/TR/cors/ .
> Dette betyr blant annet at alle lenker skal støtte
> OPTIONS-forespørsler uten innlogging der alle mulige operasjoner
> returneres i «Access-Control-Allow-Methods».
> 
> I tillegg skal alle forespørsler returnere i HTTP-hodefeltet «Allow»
> de operasjonene (GET, HEAD, POST, PUT, DELETE, OPTIONS, etc) som
> gjeldende innlogget bruker har tilgang til.

**Comment by hanber** [comment]
Jeg forstår ikke rekkevidden av endringsønsket, og har derfor ingen kommentar til det.

**Comment by petterreinholdtsen** [comment]
Hvem skal i så fall vurdere endringen, hvis ikke arkivverket gjør det?  Er det noe som er uklart i forslaget, som kan forklares bedre?

**Comment by henningjensen** [comment]
Enig i at vi tar med avsnittet om CORS for å spesifisere hvilken standard det er snakk om. 
Men det er ikke nødvendig å støtte OPTIONS på alle metodekall. Ref simple requests nevnt her: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Simple_requests

Autentisering og autorisering er ikke tatt med i denne versjonen av grensesnittet. Derfor bør vi la Allow headeren ligge i denne omgangen. Dette er en bra kandidat for en utvidelse på et senere tidspunkt.

**Comment by tsodring** [comment]
Hei,

Ref denne:

> Autentisering og autorisering er ikke tatt med i denne versjonen av grensesnittet.

Snakker vi her da om at en vanlig saksbehandler skal ha muligheten til å avslutte eller slette et arkiv? Hvis autorisering ikke er med, så er det jo en "_free for all_" i tjenestegrensesnittet.


Ref denne:

> utvidelse på et senere tidspunkt.

Kanskje Riksarkivet kan si litt mer om videre forvaltning av tjenestegrensesnittet. Vi har brukt 6-8 år fram til dette, det sies at prosjektet skal være ferdig til sommeren. Vi snakker her om 8-10 uker og vi fortsatt skriver og leverer mangelmeldinger på 1.0-beta . Vi er ganske langt unna ferdigstilling av noe som jeg ville kalt en teknisk standard. Det virker som om begrepet  "konseptuel standard" henger fortsatt med i tjenestegrensesnittet.

**Comment by henningjensen** [comment]
Kjernen må jo selvsagt behandle autorisering av brukere, men for selve tjenestegrensesnittet så er det ikke essensielt å spesifisere denne delen. Klienten vil fint kunne benytte metodene selv om den ikke får eksplisitt beskjed om hva brukeren kan eller ikke kan gjøre.

**Comment by petterreinholdtsen** [comment]
Slik jeg forstår CORS og dagens nettlesere, så vil dynamiske nettsider som forsøker å snakke med API-et bli nektet tilgang hvis OPTIONS ikke fungerer, eller hvis Accepts-hodetfeltet ikke blir satt.  Nettleseren gjør en sjekk i forkant med ett OPTIONS-kall før javascript for lov til å koble seg opp til endepunktet, slik at å ikke kreve at OPTIONS støttes, og ikke kreve at lovlige operasjoner listes opp i Accepts vil gjøre det umulig å bruke API-et fra en javascript-klient.

Det vil være svært uheldig hvis API-et ikke kan brukes fra javascript-nettsider.

Hvis jeg forstår https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Simple_requests, så gjelder den ikke API-et, da vi bruker andre Content-type-verdier enn det slike enkle forbindelser gjelder for.

**Comment by henningjensen** [comment]
Ser ut som jeg har oversett den biten om Content type - skal teste ut dette.

**Comment by henningjensen** [comment]
Har testet dette og det er ikke nødvendig med OPTIONS-metoden på ordinære GET-metoder. Vi trenger kun OPTIONS på metoder hvor klienten skal sende inn data, typisk POST og PUT. Utbrodert dette noe i #158
