### ISSUE TITLE
Unsupported OData substringof function specified in examples

### ISSUE THREAD

**Issue by ivaylomitrev** [arkivverket/noark5-tjenestegrensesnitt-standard#291]
------------------  ---------------------------------
           Prosjekt  NOARK 5 Tjenestegresesnitt
           Kategori  Noark 5.5.0 TG versjon 1.0
        Alvorlighet  kommentar / protest
       Meldingstype  utelatt / trenger klargjøring
    Brukerreferanse  user@example.com
        Dokumentdel  #6
 ------------------  ---------------------------------

### Beskrivelse

Chapter 6 specifies the following example:
```
/api/arkivstruktur/mappe/?$filter=substringof('test', tittel)
```

This is not an OData v4 function. It is an OData v2 function, but even then it should be followed by an operator and a true/false value as per [OData v2 URI conventions](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/) (unless of course functions returning functions imply `eq true` which I have not checked). In either case, a change in the specification is needed.

## Ønsket endring

Judging by the specified arguments, I am not sure whether the intention was to use [contains](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html#_Toc31360982) which would look like this:
```
contains(tittel, 'test')
```
or [substring](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html#_Toc31360987) which would also require an operator and a literal and look like this:
```
substring(tittel, 1, 4) eq 'test'
```

**Comment by tsodring** [comment]
The point you are making is that there is no **substringof**, but there is a **substring** in Odata v 4.1. I agree, and the examples should be updated to reflect that.

**Comment by ivaylomitrev** [comment]
Correct. I was just not sure whether they should be updated to `substring` or `contains`, because the intention seems to be `substring`, but the contract is closer to `contains`.

I see the original intention was `substring` after all.

**Comment by ivaylomitrev** [comment]
PR: https://github.com/arkivverket/noark5-tjenestegrensesnitt-standard/pull/295

**Comment by petterreinholdtsen** [comment]
#295 is in master now.
