### ISSUE TITLE
Korriger lenke til Noark 5-standarden

### ISSUE THREAD

**Issue by petterreinholdtsen** [arkivverket/noark5-tjenestegrensesnitt-standard#3]
I kapittel 2 er det en lenke til https://arkivverket.no/arkivverket/Offentleg-forvalting/Noark/Noark-5/Standarden som skal gå til Noark 5-standarden.  Den lenken fungerer ikke lenger.  En bedre lenke kan være https://www.arkivverket.no/forvaltning-og-utvikling/noark-standarden/noark-5/noark5-standarden .

**Comment by petterreinholdtsen** [comment]
I tillegg refereres det til versjon 3.1 av Noark t, mens versjon 4 er siste utgave.  Foreslår at avsnittet byttes ut med dette:

```
Siste versjon av [Norsk Arkivstandard (NOARK) 5](https://www.arkivverket.no/forvaltning-og-utvikling/noark-standarden/noark-5/noark5-standarden).
```

**Comment by petterreinholdtsen** [comment]
Jeg er fortalt at Noark 5.5 er på trappene.  Det kan være lurt å se om det vil endre aktuell URL a lenke til.

**Comment by oivkru** [comment]
Endret lenke til korrekt side.
