### ISSUE TITLE
Klargjør sjekksumalgoritme-verdi og referanse

### ISSUE THREAD

**Issue by petterreinholdtsen** [arkivverket/noark5-tjenestegrensesnitt-standard#31]
Dette er en kopi av mangelmelding sendt inn til Arkivverket, se også https://github.com/petterreinholdtsen/noark5-tester/blob/master/mangelmelding/sendt/2017-06-12-sjekksumalgoritme.md .

 ------------------  ---------------------------------
           Prosjekt  NOARK 5 Tjenestegresesnitt
           Kategori  Versjon 1.0 beta
        Alvorlighet  kommentar
       Meldingstype  trenger klargjøring
    Brukerreferanse  pere@hungry.com
        Dokumentdel  7.2.1.7
         Sidenummer  106
        Linjenummer  n/a
    Innsendingsdato  2017-06-12
 ------------------  ---------------------------------

Denne teksten er del av en samling innspill til NOARK5-standarden tilgjengelig fra [https://github.com/petterreinholdtsen/noark5-tester/](https://github.com/petterreinholdtsen/noark5-tester/).

Beskrivelse
-----------

Gjelder også side 61 i Noark 5 versjon 4.0 vedlegg nr. 1 Metadatakatalog.

Det fremgår ikke klart fra tjenestegrensesnittet og Noark 5-standarder hvilke verdier som er gyldige i metadatafeltet M706 sjekksumAlgoritme. Tjenestegrensesnittet forklarer at algoritmen som skal brukes i dag er SHA 256, men sier ikke noe om hvilken verdi selve feltet skal ha når det gjøres.

Betingelsen for M706 i metadatakatalogen til Noark 5 versjon 4.0 på side 61 sier

> Betingelser: Kan ikke endres. Algoritmen som skal brukes inntil videre er SHA256.

Spesifikasjonen for tjenestegrensesnittet del 7.2.1.7 (Dokumentobjekt) i listen med restriksjoner på side 106 sier:

> M706 sjekksumAlgoritme: Algoritmen som skal brukes inntil videre per SHA256.

En kunne ut fra dette anta at verdien som skal brukes er «SHA256», men «[Eksempel på innhold i malen for arkivuttrek.xml for Noark 5 versjon 4.0](http://arkivverket.no/arkivverket/content/download/20549/186617/version/1/file/pdf.pdf)» bruker verdien «SHA-256» med bindestrek.  Det er dermed minst to ulike tolkninger av lovlig verdi for dette feltet.  Det bør være entydig definiert i tjenestegrensesnittet hvilken verdi som vil bli gjenkjent av klient og tjeneste.  Gitt at verdien «SHA-256» allerede er brukt i et eksempeluttrekk, foreslår jeg at denne varianten velges som lovlig verdi for metadatafelt M706.

Jeg har ikke klart å finne en referanse i spesifikasjonen for tjenestegrensesnitt eller i Noark 5-spesifikasjonene forøvrig til hva som konkret menes med sjekksumalgoritmen SHA 256, hverken i spesifikasjonen for Noark 5 versjon 4.0 eller i spesifikasjonen for Noark 5 Tjenestegrensesnitt versjon 1.0 Beta.  Algoritmen er velkjent, men det kunne med fordel refereres til en spesifikasjon der SHA 256 er forklart.  En slik mulig referanse er [IETF RFC 4634](https://tools.ietf.org/html/rfc4634).  Jeg foreslår at denne legges inn i tjenestegrensesnitt-spesifikasjonen under del 2 (Normative referanser) i tjenestegrensesnittspesifikasjonen.

Ønsket endring
--------------

Endre del 2 (Normative referanser), legg inn nytt punkt på slutten:

> SHA-256 er definiert i IETF RFC 4634 - https://tools.ietf.org/html/rfc4634.

Endre spesifikasjonen for tjenestegrensesnittet del 7.2.1.7 (Dokumentobjekt), bytt ut denne tekst i listen med restriksjoner på side 106

> M706 sjekksumAlgoritme: Algoritmen som skal brukes inntil videre er SHA256.

med denne teksten:

> M706 sjekksumAlgoritme: Algoritmen som skal brukes inntil videre er SHA-256.  Obligatorisk verdi: «SHA-256»

Endre betingelsen for M706 i metadatakatalogen for Noark 5, bytt ut

> Algoritmen som skal brukes inntil videre er SHA256»

med

> Algoritmen som skal brukes inntil videre er SHA-256».
>
> Obligatorisk verdi:
>
>  * «SHA-256»

**Comment by petterreinholdtsen** [comment]
I ettertid har jeg oppdaget at det bør klargjøres hvilken representasjon av SHA-256-verdien som skal brukes i feltet.  Skal det være f.eks. være hexadesimal representasjon eller base64.  Eksempler jeg har sett tyder på at det er hexadesimal representasjon som brukes andre steder.

**Comment by hanber** [comment]
Jeg tror vi har sagt ett eller annet sted at verdien skal være "SHA-256", og at det skal være hexadesimalt. Vi sjekker det med Avlevering.

**Comment by joergen-vs** [comment]
Det er SHA-256 [med bindestrek] som er det korrekte. Har forekommet i dokumentasjon noen ganger uten bindestrek, men internasjonale standarder spesifiserer sjekksum-algoritmen med bindestrek.
Den skal også representeres med hexadesimale verdier.

**Comment by hanber** [comment]
Det er sjekket, og verdien til sjekksumalgoritme skal være "SHA-256", sjekksumverdien skal være i hex.

**Comment by petterreinholdtsen** [comment]
Merk, mitt endringsforslag #63 vil kun korrigere teksten i tjenestegrensesnittspesifikasjonen.  Endring i metadatakatalogen bør følges opp på egnet sted, men jeg vet ikke hvor det i så fall er.  Kan noen i arkivverket ta den delen videre, og få byttet ut 'SHA256' med 'SHA-256' der?

**Comment by hanber** [comment]
Jeg har rettet i neste versjon av metadatakatalogen.

**Comment by petterreinholdtsen** [comment]
[Hans Fredrik Berg]
> Jeg har rettet i neste versjon av metadatakatalogen.

Ypperlig.  Jeg tok inn min endring i tjenestegrensesnittet, slik at det
er fikset også der.  Er forresten neste versjon av metakatalogen
offentlig tilgjengelig?

-- 
Vennlig hilsen
Petter Reinholdtsen
