### ISSUE TITLE
Er relasjonen .../sakarkiv/sak/ under presedens en skrivefeil?

### ISSUE THREAD

**Issue by petterreinholdtsen** [arkivverket/noark5-tjenestegrensesnitt-standard#34]
Dette er en kopi av mangelmelding sendt inn til Arkivverket, se også https://github.com/petterreinholdtsen/noark5-tester/blob/master/mangelmelding/sendt/2017-05-16-rel-sakarkiv-sak.md .

 ------------------  ---------------------------------
           Prosjekt  NOARK 5 Tjenestegresesnitt
           Kategori  Versjon 1.0 beta
        Alvorlighet  kommentar
       Meldingstype  trenger klargjøring
    Brukerreferanse  pere@hungry.com
        Dokumentdel  7.2.3.10
         Sidenummer  231
        Linjenummer  n/a
    Innsendingsdato  2017-05-16
 ------------------  ---------------------------------

Beskrivelse
-----------

Dette gjelder del 7.2.3.10 (Presedens) på side 231.

Der er det ført opp en relasjonsnøkkel http://rel.kxml.no/noark5/v4/api/sakarkiv/sak/ uten nærmere forklaring og beskrivelse.  Jeg finner heller ikke 'sak' eller noe som ligner beskrevet under 6.2.6 (Presedens) i Noark 5-standarden, og det er ikke andre eksempler på bruk av denne nøkkelen i spesifikasjonen.  Er denne relasjonen en skrivefeil for ../saksmappe/?  Jeg antar det og foreslår at den endres.

Hvis den ikke er en skrivefeil, kan det legges inn en beskrivelse om hva relasjonen betyr og hvordan den er knyttet til innholdet i Noark 5?

Ønsket endring
--------------

Endre i del 7.2.3.10 (Presedens) på side 231.  Under Relasjonsnøkler, bytt ut http://rel.kxml.no/noark5/v4/api/sakarkiv/sak/ med http://rel.kxml.no/noark5/v4/api/sakarkiv/saksmappe/.

**Comment by hanber** [comment]
Det ser ut som en skrivefeil.

**Comment by petterreinholdtsen** [comment]
I listen over relasjoner er denne ført opp som en relasjon til saksmappe, så det virker ganske klart at det er en skrivefeil. Den navngitte relasjonen 'sak' burde kanskje også bytte navn til 'saksmappe'?  Det er en tilsvarende relasjon i beskrivelsen av Saksmappe, og der er det ikke en relasjon .../sak/.  De aller fleste relasjoner har navn som er identisk med entitetsnavnet i små bokstaver (mappe, saksmappe, registrering, arkiv, etc, etc.), med det henvises tilbake til samme entitet der det må brukes et annet relasjonsnavn (forrige, neste, under*, etc).  For å være konsistent, så vil jeg anbefale at 'sak' byttes til 'saksmappe' i både relasjon og relasjonsnøkkel, både for Presedens og Saksmappe.
