### ISSUE TITLE
Hvordan defineres relasjoner mellom arkiv og underarkiv?

### ISSUE THREAD

**Issue by petterreinholdtsen** [arkivverket/noark5-tjenestegrensesnitt-standard#38]
Dette er en kopi av mangelmelding sendt inn til Arkivverket, se også https://github.com/petterreinholdtsen/noark5-tester/blob/master/mangelmelding/sendt/2017-06-21-ny-underarkiv.md .

 ------------------  ---------------------------------
           Prosjekt  NOARK 5 Tjenestegresesnitt
           Kategori  Versjon 1.0 beta
        Alvorlighet  protest
       Meldingstype  trenger klargjøring
    Brukerreferanse  pere@hungry.com
        Dokumentdel  7.2.1.1
         Sidenummer  57
        Linjenummer  n/a
    Innsendingsdato  2017-06-21
 ------------------  ---------------------------------

Denne teksten er del av en samling innspill til NOARK5-standarden tilgjengelig fra [https://github.com/petterreinholdtsen/noark5-tester/](https://github.com/petterreinholdtsen/noark5-tester/).

Beskrivelse
-----------

Dette gjelder del 7.2.1.1 (Arkiv).

Listen over relasjonsnøkler på side 57 viser at en kan få ut oversikt over underarkiv ved å benytte relasjonen .../arkivstruktur/underarkiv/, men har ingen ny-underarkiv/ for å opprette et nytt underarkiv.  Det er relasjonspar for arkivskaper/ny-arkivskaper, arkivdel/ny-arkivdel, arkiv/ny-arkiv men ikke for underarkiv.  Hvordan er det mening at en skal opprette et nytt underarkiv knyttet til et arkiv?

Det er uklart hva som er forskjellen på relasjonene 'arkiv' og 'underarkiv'.  I følge UML-skjema er ethvert arkiv koblet under et annet arkiv et underarkiv.  Det virker dermed nærliggende å tro at relasjonen .../arkivstruktur/underarkiv/ er en skrivefeil.  Hvis ikke, må det forklares hva som er forskjellen på arkiv- og underarkiv-relasjonene for klassen Arkiv.

Jeg foreslår at relasjonen 'underarkiv' fjernes og at kun relasjonene 'arkiv/' og 'ny-arkiv/' brukes til å finne og opprette underarkiv. Følgende brukes for å illustrere dette.

For å opprette en underarkiv skal en dermed bruke POST til href knyttet til rel-verdien `http://rel.kxml.no/noark5/v4/api/arkivstruktur/ny-arkiv/`. Den kan for eksempel angi en slik struktur:

 * POST `[contextpath][api]/arkivstruktur/arkiv/{systemID}/ny-arkiv`   

For å hente en liste av underarkiv skal en dermed bruke  GET til href knyttet til rel-verdien `http://rel.kxml.no/noark5/v4/api/arkivstruktur/arkiv/`. Den kan for eksempel angi en slik struktur:

 * GET `[contextpath][api]/arkivstruktur/arkiv/{systemID}/arkiv`

Merk, det er en tilsvarende situasjon for mappe/undermappe, der det kun finnes relasjoner for å opprette 'mappe', men ingen relasjoner for å liste opp både 'mappe' og 'undermappe'.

Ønsket endring
--------------

I del 7.2.1.1 (Arkiv), endre følgende setning i siste avsnitt i beskrivelsen av klassen på side 56:

> Toppnivået skal bare ha én forekomst, men kan ha ett eller flere
> undernivåer, se om underarkiv nedenfor.

Endres til følgende:

> Toppnivået skal bare ha én forekomst, men kan ha ett eller flere
> undernivåer, se om underarkiv nedenfor.  Underarkiv opprettes ved å
> bruke arkiv-objektets relasjon  
> `http://rel.kxml.no/noark5/v4/api/arkivstruktur/ny-arkiv/`
> og listes
> opp ved å bruke arkiv-objektets relasjon
> `http://rel.kxml.no/noark5/v4/api/arkivstruktur/arkiv/`.

Endre i relasjonslisten på side 56, endre Kilde 'undearkiv' til 'arkiv' og legg inn følgende merknad:

> Lenker til underarkiv.

Fjern duplikat-Aggregation med kilde underarkiv på side 57 (identisk med første relasjon i listen).

Fjern relasjonen `http://rel.kxml.no/noark5/v4/api/arkivstruktur/underarkiv/` fra listen over relasjonsnøkler på side 57.

**Comment by hanber** [comment]
Trenger vi tjenester for dette? Vi ble på ett eller annet tidspunkt enige om at det ikke er naturlig å drive arkivadministrasjon gjennom tjenestegrensesnittet, men lage tjenester for å vedlikeholde arkivstrukturen fra og med klasse og ned.

**Comment by tsodring** [comment]
Jeg ble veldig overrasket over dette. Dette er et viktig poeng å få diskutert og komme fram til en konklusjon. Målet med tjenestegrensesnitt prosjektet er følgende:

> -  å etablere en plattformuavhengig informasjonsmodell i UML for arkivstrukturen i Noark 5
> -  å definere CRUD tjenester (Create, Read, Update, Delete) for objektene i informasjonsmodellen

arkiv, arkivdel, klassifikasjonsystem og klasse er alle en del av arkivstrukturen. Så utgangspunktet er jo at disse også skulle defineres. I alle UML tegningene er hele arkivstrukturen vist, ikke bare mappe og nedover.  Da synes jeg at hvis dere skal oppfylle målet med prosjektet så forpliktes det å levere helheten. Et såpass stor avvik som dette representerer bør begrunnes og diskuteres med fagmiljøet forøvrig.

Videre argumenteres det at prosjektet skal levere:

> Et standardisert Noark 5 tjenestegrensesnitt skal bidra til gode, sammenhengende digitale tjenester på tvers av virksomhetsgrensene i offentlig sektor, støtte opp under offentlige virksomheters ønske om leverandøruavhengighet, samt fremme digitalisering og gi bedre tjenester.

Hvis arkiv/arkivdel/klassikasjonsystem/klasse ikke er definert med CRUD funksjonlitet så blir Noark 5 tjenestegrensesnittet en dårlig løsning som motvirker interoperabilitet og fleksibel bruk av et Noark basert arkiv. En kommune som ønsker å integrere et fagsystem som har behov for et fagspesifikk klassifikasjonsystem  og kanskje eget arkivel vil da trenge å snakke med ACOS, Documaster, Evry eller Tieto hver gang de skal ta integrasjonen i bruk. Alle leverandører har egne versjoner og varianter av sine tjenestegrensesnitt og det er mulig at noen har ingen tjenestegrensesnitt på det som går på struktur.

Hvis prosjektet ikke leverer et ordentlig tjenestegrensesnitt som dekker hele arkivstrukturen så bryter prosjektet målet : 

> støtte opp under offentlige virksomheters ønske om leverandøruavhengighet

og faktisk legger til rette for **leverandøravhengigheter** og **innlåsing**. Prosjektet fremmer ikke digitalisering uten standardisering. Standardisering forplikter.

**Comment by oivkru** [comment]
Enig i at dette er noe som bør være del av tjenestegrensesnittet, men vi tenker at disse tjenestene ikke bør prioriteres nå for å få ferdigstilt tjenestegrensesnittet. 

Det handler blant annet om at administratortjenester (opprette, endre eller avslutte arkiv, arkivdeler, klassifikasjonssystem og klasser i klassifikasjonssystemet) skiller seg fra andre tjenester (opprette, endre eller avslutte mapper, registreringer, dokumenter, osv.). Krav 5.13.1 sier at det skal finnes en tjeneste/funksjon for å administrere kjernen, og 5.13.2 at brukeren som skal utføre dette må logge seg eksplisitt på kjernen for å utføre tjenestene. 5.13.4-7 sier også at arkiv, underarkiv, arkivdel og klassifikasjonssystem kun kan opprettes og endres gjennom administratorfunksjonen for Noark 5 kjerne. 

Videre sier kravene til sikkerhet og sikkerhetskonfigurasjon i kapittel 6.6 at eksterne system, moduler, mv., som skal ha tilgang til kjernen må være definert i kjernen, og at man i kjernen skal angi hvilken grad av tillit kjernen skal ha til det eksterne systemet og hva som er lov til å gjøre derfra. (Ikke sik å forstå at det er leverandør som skal styre dette, men at konfigurasjonen skal være i tråd med virksomhetens egne behov og tiltak på sikkerhetsområdet.) 

Administrasjon av kjernen kan dermed godt tenkes utført fra en egen administratormodul, og sånn sett er det behov for å definere tjenester for å utføre funksjoner fra denne modulen. Samtidig ser vi det ikke som så realistisk at noen kommer til å anskaffe en arkivkjerne fra én leverandør og en administratormodul fra en annen, som vil være noe av formålet med å definere administratortjenestene. 

Dette er altså ikke for å si at det ikke skal defineres tjenester, men at disse ikke blir prioritert for å ferdigstille tjenestegrensesnittet. 

Kom gjerne med tilbakemelding på disse vurderingene.

**Comment by tsodring** [comment]
I nikita-prosjektet ser vi på tjenestegrensesnittet veldig fra klient-perspektivet, der vi prøver å se for oss hvordan mange forskjellig klienter skal forholde seg til en arkivkjerne. Kanskje nikita sitt utgangspunkt er anderledes enn de tradisjonelle  leverandørene som typisk leverer en helhetlig stack. Når jeg leser tjenestegrensesnitt-dokumentet opplever jeg det slik som om det er skrevet fra tjener-perspektivet. Et godt eksempel på det er [PATCH forslaget](https://github.com/arkivverket/noark5-tjenestegrensesnitt-standard/issues/6). Slik det foreligger nå skal tjenestegrensesnittet oppdatere en hel rad av informasjon i databasen, framfor et enkelt felt. Problemet med det er at du tvinger klienten til å bedre forstå Noark standarden og vi løper risikoen at dårlige klienter visker ut data ved feil. Det er også usikker hvordan endring i sekundær tilkoblet entiteter (feks mappetype) skal håndteres i en innkommende nyttelast som en del av en PUT.

Jeg opplever at tjenestegrensesnittet beveger seg i retning av kun å definere CRUD på entiteter i transaksjonslaget altså mappe og nedover. Samtidig har prosjektet begynt å se på virksomhetspesifikkemetadata for *et* fagområde framfor å se på det fra et mer generell perspektiv slik Dimitar [skisserer](https://github.com/arkivverket/noark5-tjenestegrensesnitt-standard/issues/61#issuecomment-457250405). Jeg blir veldig usikker om vi blir sittende igjen med en slags Noark 4 webservices som hadde begrenset suksess.

Noark blir omtalt som fleksibel. Det er noe vi er enig i, selv om rykte til Noark sier noe annet. Vi tror det ligger mye mer potensial i Noark enn det som kommer fram i dag, men da må det synes i tjenestegrensesnittet. Spesielt må klassifikasjon og arkivdeler være tilgjengelig via tjenestegrensesnittet. Kanskje spørsmålet burde vært, hvordan sikrer tjenestegrensesnittet en realisering av fleksibiliteten i Noark på en standardisert måte?

Når du nevner "en arkivkjerne fra én leverandør og en administratormodul fra en annen" så er jeg helt enig. Men jeg tror vi ser på ting fra forskjellig perspektiver. Jeg mener arkivstrukturen er *arkivet* og da ser jeg for meg hele arkivstrukturen. Hele arkivstrukturen må ha CRUD på seg for at arkivstrukturen skal kunne brukes på en fleksibel måte. Det ville være første versjon av tjenestegrensesnittet.

Jeg lurer også om det sitter litt langt inne å bryte med tankegangen av at Noark er en konseptuell standard. Jeg kritiserer dere ikke for det, men tenker at når vi går i retning av et tjenestegrensesnitt så vil det være viktig å lande én konkret realisering av en konseptuell standard. Da vil det naturlig være diskusjon i tolkning, men arkivstrukturens helhet er hellig.

Men jeg forstår også at man kan kvie seg for å trekke organisatorisk struktur inn i kjernen. Jo mer man gjør det, jo mer Noark 5 ligner på Noark 4. Det er to motargumenter på det.

1. Dataene er der. administrativtEnhet og journalEnhet er felter som er i bruk og slik jeg tolker tjenestegrensesnittet skal verdien være definert i egne tabeller. Da blir det ekstra viktig at disse feltene har ordentlig CRUD på seg slik at man enkelt kan opprette disse på en ordentlig måte.

2. Vi definerer en tjenestegrensesnitt. Det er ikke en datamodell osv. Hva som ligger foran og bak tjenestegrensesnittet er irrelevant. Det som er relevant er at det er en standardisert måte å utveksle data.

Utfordringen med å ikke ta dette med nå er at det er lite sannsynlig at det i det hele tatt vil komme. Jeg tror ikke vi kan vente i 5 år til for å ferdigstille det.  Men du kan jo også utfordre community på dette. Jeg kunne godt tenkt meg å ha dette som en liten case i nikita. Vi har ventet på beskrivelsene av dette, og vi vil gjerne forsøke å komme med et forslag som dere kan vurdere.

**Comment by petterreinholdtsen** [comment]
Mens jeg har holdt på med UML-diagrammene har det slått meg at alle rekursive strukturer, dvs. alle klasser utledet fra arkiv, klasse og mappe, trenger to relasjoner, en for seg selv, og en for underobjekter.  Det jeg har innsett er at f.eks. en mappe (men vil også gjelde arkiv og klasse) vil kunne ha følgende relasjoner:

```
{ ...
  "_links" : {
    { "rel": "self", "href="somewhere" },
    { "rel": "http://rel.kxml.no/noark5/v4/api/arkivstruktur/mappe/",
       "href="somewhere" },
    { "rel": "http://rel.kxml.no/noark5/v4/api/arkivstruktur/undermappe/",
       "href="somewhere/undermappe" },
   ...
}
```

For å identifisere hvilken type objektet vi snakker om har, så vil det være to relasjoner som peker til samme URL (her "somewhere"), en med rel=self og en med rel=entitets-URL.  Dette kan for eksempel brukes til å identifisere om det er snakk om en mappe, saksmappe, moetemappe etc.  Relasjonen som har samme href som 'self'-relasjonen kan dermed ikke brukes til å finne ut hvilke underentiteter som gjelder, da det ikke er tillatt med flere _links-oppføringer med samme rel-verdi.  Dermed må det eksistere en annen relasjon for å identifisere under-objekter, her representert med 
rel=http://rel.kxml.no/noark5/v4/api/arkivstruktur/undermappe/.

Gitt at det må være to ulike relasjoner, en for mappe-instansen selv og en annen for undermappe, så er det nærliggende å bruke relasjonsnavnestrukturen over.

Et relatert og åpent spørsmål er så hvordan under-entiteter skal opprettes.  Relasjonen kan jo hete hva som helst, men det er naturlig å enten bruke et av navnene "ny-mappe" og "ny-undermappe" for å opprette neste nivå i en rekursiv struktur.   Jeg tror det vil være mest konsistent med øvrig kode om en bruker ny-<klassenavn>, i stedet for ny-under<klassenavn>.  Etter å ha skrevet importkode for arkivstruktur.xml i en avleveringspakke, så slår det meg som mest praktisk om en kan bruke ny-<klassenavn> (da kan typenavn fra XML-koden gjenbrukes direkte), men det er ikke spesielt vanskelig å forholde seg til ny-under<klassenavn> som relasjonsnavn i stedet.

```
{ ...
  "_links" : {
    { "rel": "self",
      "href="somewhere" },
    { "rel": "http://rel.kxml.no/noark5/v4/api/arkivstruktur/mappe/",
      "href="somewhere" },
    { "rel": "http://rel.kxml.no/noark5/v4/api/arkivstruktur/undermappe/",
      "href="somewhere/undermappe" },
    { "rel": "http://rel.kxml.no/noark5/v4/api/arkivstruktur/ny-mappe/",
      "href="somewhere/ny-mappe" },
   ...
}
```

Er dere enig i at dette er en god tilnærming?

Jeg håper dere ser at problemstillingen ikke om API-spesifikasjonen skal fortelle hvordan arkiv og klasse skal vedlikeholdes, men derimot hvordan rekursive entiteter skal håndteres.  Dette må løses for mappe, klasse og arkiv, og bør løses på samme vis for samtlige.  Når vi har landet på en god beskrivelse til spesifikasjonen, så er det løst for samtlige rekursive strukturer.

**Comment by petterreinholdtsen** [comment]
Jeg laget konkret endringsforslag som bruker underxx og overxx som metoder/relasjoner i rekursive strukturer, samt gjorde det klart at ny-xx skal brukes til å opprette underinstanser.  Dette burde løse både #38 og #100, og er relatert til diskusjonen rundt foreldrerelasjon i #45.  Jeg valgte å bruke under/over, i stedet for under/forelder da det virket mer intuitivt på meg.  En relatert problemstilling er sideveis relasjoner mellom entiteter beskrevet i #101, som gjelder både Arkivdel og Moetemappe (se #96).

**Comment by hanber** [comment]
Vi benytter ny-arkiv, ny-klasse, ny-mappe ved opprettelse av underentiter.

**Comment by hanber** [comment]
Ikke helt landet om over/under skal representeres ved et attributt som er referanse til over/under, eller en relasjonslenke i API-en.

**Comment by petterreinholdtsen** [comment]
Slik jeg forsto konklusjonene fra gårdagens møte, så er vi enige om at det brukes underxx og overxx som navn for de hierarkiske rekursive strukturerene til arkiv, klasse og mappe, samt kodenøkler ny-xx for å opprette en underentitet koblet til en eksisterende instans.

Stridstemaet, som vi ikke rakk diskutere ferdig i går, er hvorvidt oppretting og endring av slike skal gjøres via relasjonsnøkler eller attributter.  Jeg mener det er klart ut fra beskrivelsen i kapittel 6 at oppretting av slike 0..*-relasjoner skal gjøres via ny-xx og endring skal gjøres via $ref-mekanismen, som er mangelfullt beskrevet under overskriften "Oppdatere referanser mellom objekter".

Kan noen fra Arkitektum forklare hvor eventuelle attributter kommer inn?

**Comment by AnnKnu** [comment]
@henningjensen kan du se på dette til mandag og beslutt hva som er best løsning, ref kommentar fra HF: _Ikke helt landet om over/under skal representeres ved et attributt som er referanse til over/under, eller en relasjonslenke i API-en._
