### ISSUE TITLE
Kan en sette verdien «tom streng» i et påkrevd felt?

### ISSUE THREAD

**Issue by petterreinholdtsen** [arkivverket/noark5-tjenestegrensesnitt-standard#39]
Dette er en kopi av mangelmelding sendt inn til Arkivverket, se også https://github.com/petterreinholdtsen/noark5-tester/blob/master/mangelmelding/sendt/2017-07-03-missing-or-blank.md .

 ------------------  ---------------------------------
           Prosjekt  NOARK 5 Tjenestegresesnitt
           Kategori  Versjon 1.0 beta
        Alvorlighet  kommentar
       Meldingstype  trenger klargjøring
    Brukerreferanse  pere@hungry.com
        Dokumentdel  7.1
         Sidenummer  31
        Linjenummer  n/a
    Innsendingsdato  2017-07-03
 ------------------  ---------------------------------

Denne teksten er del av en samling innspill til NOARK5-standarden tilgjengelig fra
[https://github.com/petterreinholdtsen/noark5-tester/](https://github.com/petterreinholdtsen/noark5-tester/).

Beskrivelse
-----------

Det er flere påkrevde felt for objekter i tjenestegrensesnittet, men det står ingen steder i spesifikasjonen om hva som er ugyldige JSON-verdier for slike felt.  Et eksempel er feltet arkiv.tittel som i følge spesifikasjonen er en tekststreng som må være satt.  En naturlig tolkning av dette er at JSON-verdi satt til null ikke er tillatt, dvs at dette ikke er lov:

```
{
  "tittel": null,
  ...
}
```

Men et spørsmål som melder seg er om feltet kan være satt til en tom tekststreng, dvs om dette er tillatt:

```
{
  "tittel": "",
  ...
}
```

Det virker mest fornuftig å avvise både null og `""` som gyldige verdier, for å sikre at tittelen kan vises frem og har et reelt innhold.

Det er ikke åpenbart hvor i spesifikasjonen det bør klargjøres.  Det virker mest fornuftig å legge det inn under 7 (Tjenester og informasjonsmodell), men det kan også legges inn under både 4 (Teknologi) og 6 (Konsepter og prinsipper).

Ønsket endring
--------------

Endre i del 7.1, blokken om «Multiplisiteten» på side 31, legg til følgende setning etter «En Klasse skal alltid ha en klasseID, og kan bare ha en.»:

> En tom tekststreng-verdi (`""`) er likestilt med en manglende verdi,
> slik at ved multiplisiteten [1..1] betyr det at klasseID også må ha
> en verdi forskjellig fra tom streng.

**Comment by hanber** [comment]
Bare for å presisere: Et obligatorisk felt må ha en verdi forskjellig fra null og forskjellig fra "".

**Comment by oivkru** [comment]
Krav 6.4.5 i standarden (Noark 5 versjon 5) sier: "Metadataelementer som ikke har verdi, skal utelates fra arkivuttrekket. I uttrekket skal det med andre ord ikke forekomme tomme elementer med kun start- og slutt-tagg." Det er behov for å avklare internt først hvordan vi håndterer dette i uttrekk, når obligatoriske metadataelement mangler verdi: testen i Arkade5 feiler his metadataelementet mangler, mens tom verdi (eller dummyverdi) vil være i strid med kravet.

**Comment by petterreinholdtsen** [comment]
Endringen fra @henningjensen nevner tom streng, men tar ikke med kravet om å ikke kun inneholde 'whitespace'.  Hvordan bør slikt formuleres på norsk?  Kan vi bruke "blanke tegn"?  Trengs det en henvisning til en definisjon som forklarer hva det betyr?  Jeg antar mellomrom, linjeskift, tab etc, alle anses som 'whitespace'.  Som en kan se fra https://en.wikipedia.org/wiki/Whitespace_character er det ikke rett frem å definere hva det betyr.

**Comment by hanber** [comment]
Ja, vi oversetter whitespace med "blanke tegn som f.eks. mellomrom, tabulator eller linjeskift."

**Comment by petterreinholdtsen** [comment]
[Hans Fredrik Berg]
> Ja, vi oversetter whitespace med "blanke tegn som f.eks. mellomrom,
> tabulator eller linjeskift."

Det er bruken av 'for eksempel' som er problemet her.  Som du kan se fra
Wikipedia-siden er det mange tvilstilfeller om hva som er blanke tegn.
Er U+1680 (ogham space mark) et blankt tegn som ikke kan være alene i et
påkrevd felt i API-et?  Det er ikke sikkert den tegnes som et blankt
tegn, det kommer an på skrifttype og tegnemotor.  Hva med U+2423 (Open
box)?  Eller kontrolltegnet U+0007 (BEL)?  Sistnevnte tegnes jo ikke på
skjerm, men forventes å lage et pip ved utskrift.  Det trengs en klar og
entydig maskinlesbar definisjon slik at alle implementasjoner av API og
klient har felles forståelse av hva som ikke aksepteres inn i påkrevde
felt.

Enten må det henvises til en ekstern og entydig definisjon, eller så må
det lages en liste over hvilke tegn som anses som blanke tegn.

Uten slik felles forståelse risikerer vi at en klient aksepterer et tegn
fra brukeren som API-tjeneren senere avviser, eller at en API-tjener tar
imot informasjon som ikke senere lar seg migrere til en annen
API-tjener, eller som avvises av klienten som skal hente informasjon ut
fra en API-tjenerer.

-- 
Vennlig hilsen
Petter Reinholdtsen

**Comment by hanber** [comment]
Dette er neimen ikke lett, og antakelig et lite problem i praksis. For å kunne verifisere verdiene automatisk ser jeg behovet. Unicode har kategoriene "Letter" og "Decimal_Number" (se [http://www.unicode.org/reports/tr44/#General_Category_Values](url)), som antakelig vil dekke det vi trenger godt og vel. Jeg antar at det finnes programvare som kan si om et tegn tilhører kategorien eller ikke, for de ser ikke ut til å være sammenhengende kode-sekvenser. Innholdet av kategoriene finnes bl.a. her: [https://www.compart.com/en/unicode/category](url).
Alternativt kan vi mer upresist si at obligatoriske felt må inneholde tegn med en grafisk representasjon.

**Comment by petterreinholdtsen** [comment]
[Hans Fredrik Berg]
> Dette er neimen ikke lett, og antakelig et lite problem i praksis.

Det er ikke lett, nei.  Det som er et problem i praksis er hvis to ulike
implementasjoner av tjenestegrensesnittet velger to ulike sett av tegn
som "blanke".  Det vil gjøre at en klient som sender data inn i disse to
implementasjon kan ende opp med at den ene implementasjonen aksepterer
en metadatastreng, mens den andre avviser den.  Det kan f.eks. være hvis
epost forsøkes arkivert med tilhørende tittel.  Der er er det stor
variasjon i hvilke tegn som brukes.  En klient vil ikke kunne vite
hvilke tegn skal vil bli avvist før den har forsøkt...

Jeg ser derfor kravet til klar og entydig oppførsel på tvers at
implementasjoner kun kan oppfylles ved å gjøre det mulig for enhver
utvikler av tjenestegrensesnittimplementasjon å finne ut hvilke tegn som
anses som blanke.

> For å kunne verifisere verdiene automatisk ser jeg behovet. Unicode
> har kategoriene "Letter" og "Decimal_Number" (se
> [](url)),
> som antakelig vil dekke det vi trenger godt og vel. Jeg antar at det
> finnes programvare som kan si om et tegn tilhører kategorien eller ikke,
> for de ser ikke ut til å være sammenhengende kode-sekvenser. Innholdet
> av kategoriene finnes bl.a. her:
> [https://www.compart.com/en/unicode/category](url).

Dette tror jeg er en god tilnærming.  Kan det være en ide å liste opp
alle tegnene som anses som "blanke" i standarden, og si at den er basert
på <URL: https://www.compart.com/en/unicode/category/Zs >, og oppdatere
listekopien i en fremtidig versjon av tjenestegrensesnittet hvis det
kommer flere blanke tegn i Unicode?  Det vil sikre at alle
implementasjoner av en gitt versjon av tjenestegrensesnittet bruker
samme definisjon?

Alternativet som du skisserer, å henvise til Uninett-kategorier med
lovlige tegn, risikerer at to tjenestegrensesnitt-implementasjoner har
basert seg på ulike lister over tegn i Uninett, og dermed vil
klassifisere tegn forskjellig.  Jeg mistenker dermed at det er bedre å
lage en kort "svarteliste" over tegn som ikke kan stå alene i tittel og
andre felt, enn å lage en liste over aksepterte tegn.

> Alternativt kan vi mer upresist si at obligatoriske felt må inneholde
> tegn med en grafisk representasjon.

Dem må i så fall formuleres slik at enhver implementasjon tolker den på
samme måte.  Det tror jeg blir vanskelig å få til.

-- 
Vennlig hilsen
Petter Reinholdtsen

**Comment by hanber** [comment]
Vi spesifiserer at "white space" er som definert i Unicode-kategorien space separator [https://www.compart.com/en/unicode/category/Zs](https://www.compart.com/en/unicode/category/Zs).

**Comment by petterreinholdtsen** [comment]
Nettopp.  Jeg skal fikse konkret endringsforslag/patch.

Merk, kategorien «Space Separator» inneholder ikke tegn som tabulator, linjeskift, bjellelyd osv.  De er i kategorien «Control», https://www.compart.com/en/unicode/category/Cc .  Det virker litt uheldig å akseptere en tittel som kun inneholder usynlige kontrolltegn inn i API-et.  Kanskje er det bedre om både kategoriene «Space Separator» og «Control» anses som usynlige tegn?

**Comment by petterreinholdtsen** [comment]
Jeg tror denne ble anset som ferdig forrige uke, hvis jeg forstår "Ferdig uke 17" korrekt.  Betyr det noe annet enn jeg tror?  Problemet er fortsatt uløst, endringen jeg laget er ikke tatt inn i spesifikasjonsteksten, og endringen jeg laget basert på uttalelsen fra @hanber 1. mars er så vidt jeg forstår ufullstendig, da den ikke anser linjeskift og tabulator som blanke tegn, i strid med det @hanber skrev 8. februar.

Kan vi enes om å gå for både kategoriene «Space Separator» og «Control» som usynlige tegn i stedet for kun «Space Separator»?

**Comment by henningjensen** [comment]
@hanber må akseptere pull-requesten. Saken ble flytta til "ferdig" fordi arbeidet som skulle gjøres var ferdig.

**Comment by petterreinholdtsen** [comment]
Fra og med i dag sier spesifikasjonen at " " er en ugyldig tittel, mens "\t" og "\n" er gyldige titler.  Er det virkelig meningen?
