### ISSUE TITLE
Legge inn PNG formatkode i listen over arkivformater?

### ISSUE THREAD

**Issue by petterreinholdtsen** [arkivverket/noark5-tjenestegrensesnitt-standard#4]
I følge "Forskrift om utfyllende tekniske og arkivfaglige bestemmelser om behandling av offentlige arkiver (riksarkivarens forskrift)"[1] aksepteres PNG ved deponering av arkiv, men i spesifikasjonen for tjenestegrensesnittet er PNG ikke med i listen over formatkoder[2]. Dette er type M701 i metadatakatalogen.  I følge definisjonen til feltet i dokumentobjekt vil "faste verdier bestemmes senere".

Kan det være en ide å utvide listen over formatkoder i tjenestegrensesnittet til å inneholde alle formater i riksarkivarens forskrift, eller i det minste legge til PNG?

[1] https://lovdata.no/dokument/SF/forskrift/2017-12-19-2286
[2] https://github.com/arkivverket/noark5-tjenestegrensesnitt-standard/blob/master/kapitler/07-tjenester_og_informasjonsmodell.md#format
[3] https://github.com/arkivverket/noark5-tjenestegrensesnitt-standard/blob/master/kapitler/07-tjenester_og_informasjonsmodell.md#dokumentobjekt

**Comment by petterreinholdtsen** [comment]
En relatert ide er å lage et opplegg ala IANA MIME-register, dvs. rutine for å fortløpende registrere formater og publisere dem i en autorativ liste over kjente formater.  Se https://www.iana.org/assignments/media-types/media-types.xhtml for å lære mer om IANA.

**Comment by petterreinholdtsen** [comment]
Jeg har startet på et slikt register over formatkoder på https://gitlab.com/petterreinholdtsen/m701-noark5-katalog .  Det gir alle som ønsker å standardisere formatkoder et felles sted å samle kodeverdier.

**Comment by petterreinholdtsen** [comment]
Ja.

Det hadde dog vært fint med et svar på om autorativ liste over formater skal vedlikeholdes som del av tjenestegrensesnittet eller utenfor, og å få på plass kodeverdier for alle formatene i riksarkivarens forskrift.  Min anbefaling er å vedlikeholde en slik liste uavhengig av tjenestegrensesnitt-spesifikasjonen, det vil si som eget git-repo, enten basert på mitt git-repo m701-noark5-katalog, eller med et annet opplegg.  En kan da referere til den listen i stedet for å forsøke å gi ut ny tjenestegrensesnitt-spesifikasjon hver gang listen endrer seg.

**Comment by AnnKnu** [comment]
Vi ser ikke hensikt til å ta dette inn i tjenestegrenssnittet 5.4. Vi ser heller at det henvises til Riksarkivarens forskrift over godkjente format. Er det noe forskjell på format og format kode? (ref kommentarer fra Petter.  ) AV avventer tilbakemelding fra Petter på denne. ref mail sendt 15  jan- Mona

**Comment by hanber** [comment]
Se Issue #11.

**Comment by hanber** [comment]
Vi legger ikke inn andre gyldige arkivformater enn det som nå står i forskriften. Kodene for filtypene skal være identiske med Pronom-identifikatorene (PUID).

**Comment by petterreinholdtsen** [comment]
Hvis ulike API-klienter skal kunne fungere sammen, og kunne koble seg til ulike leverandører og implementasjoner, så tror jeg det må vedlikeholdes en formatkatalog for M707 for bruk med tjenestegrensesnittet.

Når det gjelder PNG, så ser jeg fra   https://www.nationalarchives.gov.uk/PRONOM/Format/proFormatSearch.aspx?status=new at det finnes tre ulike PRONOM-identifikatorer (fmt/11 fmt/12 fmt/13) for ulike versjoner av PNG-formatet, i tillegg til en for animerte PNG-er (fmt/935).  En oppføring i forskriften vil dermed kunne gi flere format-oppføringer, og det kan bli vanskelig for både tjenermaskin og klient å vite hvilken PRONOM-identifikator som skal velges med tilhørende problem med samvirke mellom klienter.

**Comment by petterreinholdtsen** [comment]
I mangel av liste over PRONOM-verdier fra Arkivverket, så har jeg oppdatert mitt forslag til register over formatkoder på https://gitlab.com/petterreinholdtsen/m701-noark5-katalog med PRONOM Unique ID.  Usikker på om det ble riktig, da det er veldig mange PUID-verdier å ta av i et hierarki av generiske og spesifikke formater, men har gjort mitt beste.

**Comment by petterreinholdtsen** [comment]
PNG er på eksempellista i spesifikasjonen, og Arkivverket har lovet å få på plass en liste med formater.  Lukker derfor denne mangelmeldingen.
