### ISSUE TITLE
Fjerne lenker fra inkluderte datatyper [68]

### ISSUE THREAD

**Issue by henningjensen** [arkivverket/noark5-tjenestegrensesnitt-standard#40]
Such types are part of a parent object only, without their own context and systemId, but they may define Links. How should we understand this?

Conclusions: 
We must make these links available on all parents that includes the specific datatype.
Arkitektum removes e.g. ny-enkeladresse, enkeladresse and self from EnkelAdresse, and similar irrelevant links from other DataTypes.

Saken er migrert fra Arkivverkets Jira.

**Comment by petterreinholdtsen** [comment]
Denne bør ses i sammenheng med mangelmelding #80 og #146.  Jeg mistenker slike oppføringer faktisk bør ha SystemID og self-relasjon for å kunne slettes, oppdateres og søkes opp.

**Comment by henningjensen** [comment]
Disse objekte skal oppdateres gjennom sin "forelder" og skal ikke ha slike lenker. Vi fjerner disse lenkene.
