### ISSUE TITLE
Klasse has both ../klasse and ../underklasse links [71]

### ISSUE THREAD

**Issue by henningjensen** [arkivverket/noark5-tjenestegrensesnitt-standard#41]
Following conclusion on Mappe:The klasse/ny-klasse means creating a "underklasse", providing a hierarchical structure.On the other objects, ny-klasse means creating a new "top-level" klasse.

Further, only GET is applicable to the ../underklasse link. POST should work as on klasse/ny-klasse

Conclusions:
PUT and DELETE are not intended used on the ../underklasse link.Arkitektum In special cases like this, and for mappe/undermappe, the spec should clarify which methods should be supported on these routes, preferably with examples.

Saken er migrert fra Arkivverkets Jira.

**Comment by petterreinholdtsen** [comment]
Er dette relatert til #38?

**Comment by hanber** [comment]
Ja det er det samme forholdet, når man står på et (under)arkiv betyr ny-arkiv nytt underarkiv, men det tilhører administrasjon. , ikke med i versjon 5.4.

**Comment by petterreinholdtsen** [comment]
Hvis resultatet fra GET mot underklasse inneholder en self-lenke, skal det da være mulig å slette alle underklasser med en DELETE?  Det bør beskrives klart i spesifikasjonen.  Det vil være en fordel om HTTP-hodefeltet «Allow» brukes til å annonsere støttede operasjoner, jamfør mangelmelding #29.
