### ISSUE TITLE
Klassifikasjonssystem have no field mapping to Noark 4 field OrdnPri [72]

### ISSUE THREAD

**Issue by henningjensen** [arkivverket/noark5-tjenestegrensesnitt-standard#43]
In N5 v.3.1 spec, Klassifikasjonssystem.systemId is incorrectly❓ defined - not beeing globally unique, but matching N4 ordnpri.
In services spec, no field is matching Noark 4 ordnpri. Currently we map this to the N5 systemID, but this is not correct, as it's not globally unique (a guid).
(It can neither be mapped to Klassifikasjonstype, as this is a parent metadata type applicable for multiple Klassifikasjonssystem.)

The Noark 5 spec should add a new field for this.

Conclusions
Arkitektum and Arkivverket need to come back on this.
We suggest to add Klassifikasjonssystem.KlassifikasjonsPrinsipp as new field (to match N4 ordnpri).
Alternatively to "flatten" the hierarchy, so that klassifikasjonstype is not a metadata code-register. But then one cannot group mulitple k.system into a given type anymore.
This must be checked with GI - where ordningsprinsipp now maps with klassifikasjonstype. This may fail if a customer have multiple kl.system of a given type.

Rev 27/10-17
Still open. Arkivdel also has a systemId with similar usage (mapped to ad_arkdel). Such usage of systemID is also found in Arkiv and DokumentBeskrivelse.

Saken er migrert fra Arkivverkets Jira

**Comment by henningjensen** [comment]
Hva mener dere her?

**Comment by tsodring** [comment]
Jeg må innrømme at jeg lurer hvorfor dette er et spørsmål. Noen som kan utdype litt? I Noark 4 står det at

> OP.ORDNPRI Kode for ordningsprinsipp.

Så det vil kanskje være "K-koder" eller "Fellesnøkkel" eller lignende. OP.ORDNPRI er angitt å være primærnøkkel til den tabellen. Er det derfor dette er et spørsmål?

I Noark 5 har vi følgende:

- systemID : UUID
- klassifikasjonstype : OP.TYPE
- tittel : OP.ORDNPRI (K-Koder 2012-2016)
- beskrivelse : OP.BETEGN

Dette løfter et annet spørsmål relatert til klassifikasjonsystem. Hvis K-kodene oppdateres, som de gjør innimellom så må et N5 system håndtere to versjoner av kodene, de gamle og de nye. 

Men hvorfor ser dere tilbake til Noark 4? 

Hvis jeg forstår @hanber sin kommentar så er det vel at det kan like sågodt være en systemID og det feltet fra Noark 4 er jo bare en primærnøkkel som er erstattet av systemID.

**Comment by oivkru** [comment]
Det @tsodring skriver er riktig, det som var ordnpri i Noark-4 er erstattet av systemID i Noark 5.
