### ISSUE TITLE
Klasse and Mappe have links ./underklasse and ./undermappe, but nothing for referencing parent object [75]

### ISSUE THREAD

**Issue by henningjensen** [arkivverket/noark5-tjenestegrensesnitt-standard#45]
Example: We can use GET on ./undermappe to see those, but on a given mappe, there is no field pointing to the parent.
Should there be a field e.g. overliggendeXXX or forelderXXX?

Conclusions
Arkitektum will consider to introduce a parentId (and maybe a rel link) to allow following the relation back to a parent object.

Rev 27/10-17
Still open. Ref Krav 6.2.5 on references to parent.

Saken er migrert fra Arkivverkets Jira.

**Comment by oivkru** [comment]
Metadataelementet referanseForelder ble tatt ut av en tidligere versjon av standarden (før 5.4), så kravet 6.2.5 er ikke lenger relevant. Det aktuelle kravet er ikke videreført i Noark 5v5.

**Comment by petterreinholdtsen** [comment]
As far I can tell, this issue was about providing a mechanism to allow API clients to find the parent of a given (sub)file.  It is useful when searching and finding a document, to be able to find which file and fond it belong to.   If there is no way to find the parent file and fond, traversing the database become a lot harder, as the API client will have to start from the top and browse wide and deep to try to find the search result.  Is there some other way to fulfill this use case?  If not, please provide a way to get the parent for every object in the database using the API.

**Comment by AnnKnu** [comment]
HF - ser på om dette kan være en løsning: lag en rel lenke som peker på foreldre objektet, eller opprette som et metadata element til forelder.

**Comment by petterreinholdtsen** [comment]
Slik jeg ser det, så inneholder spesifikasjonen lenker til foreldre i de relasjonene som har navn på begge sider av relasjonen, slik f.eks. klasse<->mappe-relasjonen har.  Det som trengs er en beskrivelse av hvordan JSON for slike relasjoner skal se ut.  En slik beskrivelse må forklare hvordan relasjoner av typen 0..1, 1..1, 0..* og 1..* skal se ut i JSON.  Et mulig løsning er å si om for eksempel denne relasjonen mellom Klasse og Mappe:

| **Relasjon**                             | **Kilde**                                                | **Mål**                | **Merknad** |
| ---------------------------------------- | -------------------------------------------------------- | ---------------------- | ----------- |
| **Aggregation** (Bi-Directional)           | mappe 0..* Mappe                                         | klasse 0..1 Klasse     |             |

skal representeres med en relasjonsoppføring under _links i Klasse-instansen som peker til en href som returnerer listen med alle mapper som hører til den klassen, og en relasjonsoppføring under _links i hver av disse Mappe-instansene som peker tilbake til Klasse-instansen.

Da blir Klasse-instansen seende ut ala dette:

```Python
{
   "systemID": "klassesystemid",
   "klasseID": "2.3",
   "tittel": "Lønn og pensjon",
   "_links": [
      { "rel": "self", "href": "klasse-2-3-url" },
      ...
      { "rel": "http://rel.kxml.no/noark5/v4/api/arkivstruktur/mappe/",
        "href": "mappe-liste-url"}
   ]
}
```

Listen over mappe-instanser ser noe ala dette ut:

```Python
{
    "count": 100,
    "results": [
        {
          "systemID": "mappesystemid",
          "tittel": "Skjult mappe",
          ...
          "_links": [
            { "rel": self", "href": "mappe-self-url" },
            ...
            { "rel": "http://rel.kxml.no/noark5/v4/api/arkivstruktur/klasse/",
              "href": "klasse-2-3-url" }
          ]
       },
       ...
    ],
    "_links: ...
}
```

Og en individuell Mappe-instans seende ut ala dette:

```Python
{
   "systemID": "mappesystemid",
   "tittel": "Skjult mappe",
   ...
   "_links": [
     { "rel": self", "href": "mappe-self-url" },
     ...
     { "rel": "http://rel.kxml.no/noark5/v4/api/arkivstruktur/klasse/",
       "href": "klasse-2-3-url" }

   ]
}
```

Merk hvordan href-verdiene "mappe-self-url" og "klasse-2-3-url" brukes på tvers av disse JSON-resultatene.

Relasjonsnavnene (mappe/klasse her) henviser dermed til relasjonsnøklene http://rel.kxml.no/noark5/v4/api/arkivstruktur/mappe/ og http://rel.kxml.no/noark5/v4/api/arkivstruktur/klasse/ som brukes for å finne "barn" og "foreldre".  Det eneste tilfellet der dette ikke fungerer er hvor en entitetstype henviser til seg selv, som i undermappe.  Der må det brukes spesielle relasjonsnøkler som henviser til barn og foreldre, for å unngå navnekollisjon med relasjonsnøkkelen som identifiserer instansen selv.

**Comment by petterreinholdtsen** [comment]
Denne mangelmeldingen er relatert til mangelmeldingene #38, #41, #100 og #101.  Problemet som beskrives er fortsatt ikke avklart i spesifikasjonen.

**Comment by petterreinholdtsen** [comment]
Dette temaet ble diskutert på et møte hos Arkivverket for noen uker siden, og det var der enighet om å bruke 'overxx' og 'underxx' til å referere til overliggende og underliggende instanser for entiteter som tillot rekrusive strukturer.  Det var ikke tid på møtet til å diskutere hvordan disse skulle oppdateres.  Det gjorde at det ikke var klart hvordan spesifikasjonen skal oppdateres rundt dette.  En god start er kanskje å definiere relasjonsnøkler for over* og under* der det er aktuelt i spesifikasjonen, og så løse oppretting og oppdatering som neste steg?

Det bør også defineres relasjonsnøkler for instanser som har pekere til sideliggende instanser (som for eksempel Arkivdel sin forløper/etterfoelger og Moetemappe sin forrigemoete/nestemoete), og en mekanisme for å opprette og oppdatere disse. Kanskje samme mekanisme bør brukes begge steder?  Oppdatering av slike relasjoner mellom instanser trengs også for Kryssreferanse.  Jeg mistenker dermed valg av mekanisme bør vurdere alle disse tre relasjonene (over/under, forrige/neste og kryssreferanse) under et når løsning finnes.
