### ISSUE TITLE
Eksempel på kryssreferanse [18]

### ISSUE THREAD

**Issue by henningjensen** [arkivverket/noark5-tjenestegrensesnitt-standard#46]
Vi trenger et realistisk eksempel på bruk av kryssereferanse som vi kan implementere i eksempelapplikasjonen og som kan benyttes til dokumentasjonen.

**Comment by henningjensen** [comment]
<xs:complexType name="KryssreferanseType" sawsdl:modelReference="http://arkivverket.metakat.no/Objekttype/Index/EAID_84C37388_F2C5_41ff_B4CA_B6AE9151E66D"><xs:complexContent><xs:extension base="rest:AbstraktResourceType"><xs:sequence><xs:element name="referanseTilMappe" type="n5mdk:SystemIDType" nillable="true" minOccurs="0" maxOccurs="1"/><xs:element name="referanseTilKlasse" type="n5mdk:SystemIDType" nillable="true" minOccurs="0" maxOccurs="1"/><xs:element name="referanseTilRegistrering" type="n5mdk:SystemIDType" nillable="true" minOccurs="0" maxOccurs="1"/><xs:element name="mappe" type="as:MappeType" nillable="true" minOccurs="0" maxOccurs="1"/><xs:element name="klasse" type="as:KlasseType" nillable="true" minOccurs="0" maxOccurs="1"/><xs:element name="registrering" type="as:BasisregistreringType" nillable="true" minOccurs="0" maxOccurs="1"/>

This is to be understood as a many‐to‐many relationship between the involved objects. Hence, the database needs to implement referanseFra fields as well.Such fields are by intention not part of the Kryssreferanse object, since the parent "from‐object" can be found via the named association, e.g. "registering".

We also suggest to remove all the ny- links on the Kryssreferanse object, since such actions will be in the context of beeing on an actual mappe, registrering or klasse.

ConclusionsArkitektum confirms the superfluous ny-links are removed from the spec. However, the referanseFra- fields will not be included in the Kryssreferanse object.This means search is not possible using the referanseFra fields directly ‐ one has to use the OData any syntax.

Arkivverket and Arkitektum: We suggest the referanseFra fields to be part of Kryssreferanse, in order to provide a more simple and effective search.Ref also our suggestion on a more general functionality concerning this - extracted from mail by Steinar Abrahamsen:"ForslagDet skal være å opprette kryssreferanse mellom alle objekter i arkivstrukturen. Dette kan avgrenses til hoved objektene (arkiv, arkivdel, mappe, basisregistrering, dokument og dokumentobjekt).Leverandørene bør utforme metoden så generelt av den kan benyttes for alle objekter eks fra bruker til bruker.Kryssreferanse skal være to veis: Dette innebærer at en kryssreferanse skal inneholde både fra og til verdien. Dette for å effektivisere søk/gjenfinning og gjenopprette bakoverkompabilitet.

ForenklingFølgende egenrelasjoner fjernes: Arkiv (underarkiv) og mappe (undermappe) da funksjonaliteten kan erstattes av kryssreferanser."

Arkitektum will create use case examples on this topic.It is correct that Kryssreferanse may exist on Basisregistrering, but not on Registrering (p53 and in xsd below).

"Relasjoner": It is correct with "Bi-directional", but the terms "Kilde" (source) and "Mål" (destination) seems a bit strange for Kryssreferanser. They should be read in both directions to be more understandable. (The lower case name in mål/kilde states the name (text) of the association, while the upper case name states the type the association points to/from.)

"Rel" links: These are links back to the from-object. The to-object may have been deleted or moved to historical archive, so one cannot link to them.The value in referanseTilxx is given in the response, and it's up to service consumer how to use this in their own UI (or in other apps).

Rev 20/10-17Arkitektum status is Unresolved. Must extend with referanseFraMappe, referanseFraKlasse❓, referanseFraRegistrering.Arkivverket. Could we drop using ..TilKlasse and …FraKlasse – and insteadof this use referanse-Sekundærklassifikasjon?

**Comment by henningjensen** [comment]
Tor Kjetil Nilsen
11 months ago

datamodell skal være ok. heter klasse, mappe og registrering og ikke referanseFraMappe o.l

**Comment by henningjensen** [comment]
Tor Kjetil Nilsen
10 months ago

Eksempel lages i testapplikasjon når ny xsd er lagd og brukes i dokumentasjonen

**Comment by hanber** [comment]
Eksempel på bruk av kryssreferanse mellom mappe og/eller saksmappe og møtemappe: I en byggesak kan det dukke opp saksbehandling (dispensasjonssøknad) som krever politisk behandling, man vil da saksbehandle i saksmappe (teknisk etat) og legge en kryssreferanse til møtemappe og saksbehandlingen i politisk sak (behandling i plan -og miljø).

**Comment by AnnKnu** [comment]
Hva innebærer denne endringen?

**Comment by henningjensen** [comment]
Opprette kodeeksempel på http://rel.kxml.no/noark5/v4/api/arkivstruktur/ny-kryssreferanse/
Samme som for http://rel.kxml.no/noark5/v4/api/arkivstruktur/ny-mappe/

Vis metodekallene:
GET /ny-kryssrefereranse
POST /ny-kryssrefereranse

**Comment by petterreinholdtsen** [comment]
Det er litt uklart for meg hva som foreslås her, og det virker på meg som om beskrivelsen av entiteten Kryssreferanse har unødvendig duplisering ved å både ha relasjoner og attributter med samme innhold.  Det holder jo med relasjoner, og attributtene trengs ikke.

En måte å opprette kryssreferanser er å sende inn relasjonene som trengs, f.eks. ala dette:

POST http://localhost:49708/api/arkivstruktur/ny-kryssreferanse/

```Python
{ "_links": [
 {
   "rel": "http://rel.kxml.no/noark5/v4/api/arkivstruktur/mappe/",
   "href": "http://localhost:49708/api/arkivstruktur/mappe/a0e450a4-5d10-11e9-8c2d-a3f306462684/"
 },
 {
   "rel": "http://rel.kxml.no/noark5/v4/api/arkivstruktur/klasse/",
   "href": "http://localhost:49708/api/arkivstruktur/klasse/5288a95e-5d11-11e9-827e-73fd489fe015/"
 },
 {
   "rel": "http://rel.kxml.no/noark5/v4/api/arkivstruktur/registrering/",
   "href": "http://localhost:49708/api/arkivstruktur/registrering/5a8bf624-5d11-11e9-97f9-af4bb6f7812c/"
 }
]}
```

Dette forutsetter at de refererte instansene av mappe, klasse og registrering allerede eksisterer.

Det gjør at entiteten ikke har noen attributter igjen, kun relasjoner, hvilket forsåvidt stemmer med det som skal avleveres.  Men kan det være en ide å gjøre den til en Arkivenhet, og sette SystemID og informasjon om hvem som opprettet og endret den?  Informasjonen kan ikke avleveres, men er kanskje nyttig å ha tilgjengelig mens arkivet er i produksjon?

**Comment by petterreinholdtsen** [comment]
Denne bør ses i sammenheng med mangelmelding #151.

**Comment by petterreinholdtsen** [comment]
Jeg ser i endringsforslag #162 som løsning på mangelmelding #49, også satser på duplisering av informasjon i både relasjoner og attributter.  Dette virker uheldig.  Finner ingen forklaring på hvordan dette er tenkt brukt, og hvorfor det anses lurt å duplisere informasjonen om relasjonene til en instans.
