### ISSUE TITLE
SystemID reference fields [8]

### ISSUE THREAD

**Issue by henningjensen** [arkivverket/noark5-tjenestegrensesnitt-standard#49]
E.g. referanseSaksansvarligThru-out the model, these are systemIDs , used for unique identification of objects. On inserting or updating such references, this means the clients must pass the systemIDs in the requests, potensially lookup such values in advance.For ephorte the primary keys are not necessarily globally unique on it's own - as they conform to the Noark 4 spec. However, they are unique, given the context, for instance in the avlevering (submission): "arkivdel:111:mappe:222:registrering:333"

referanseUtlaantTil exists in saksmappe, but not in journalpost. The field doesn't exist in the generated models either.

referanseArkivdel is present on scheme and in description for Registrering, but absent in xsd and in generated class

Conclusions1.0.beta now defines referanseUtlaantTil and referanseArkivdel.Arkitektum - can you check journalenhet? This is still a simple string, not a reference.

**Comment by henningjensen** [comment]
Hans Fredrik Berg
11 months ago

Trenger vi lenger utlån-opplysninger? Kan vi skaffe en oversikt over alle krav og metadata som bare gjelder papirarkiv?

**Comment by henningjensen** [comment]
Hans Fredrik Berg
last month

_referanseUtlaantTil _should exist in _saksmappe _as a systemID, and not in _journalpost _(metadata element M229). This is correct in arkivverket.metakat.no.
_referanseArkivdel _should exist in _registrering _as a systemID (metadata element M208). It is missing for _dokumentbeskrivelse _and _mappe _in arkivverket.metakat.no.

**Comment by hanber** [comment]
Se kommentaren over.

**Comment by henningjensen** [comment]
Oppsummering: 
Vi legger inn feltet **referanseArkivdel** på klassene **DokumentBeskrivelse** og **Mappe**.

**Comment by oivkru** [comment]
Fint, men Dokumentbeskrivelse med liten b

**Comment by jtellnes** [comment]
[Current code diff](https://github.com/arkivverket/noark5-tjenestegrensesnitt-standard/compare/master...jtellnes:%2349)

**Comment by petterreinholdtsen** [comment]
Jeg tror det gir mer mening å peke fra Mappe og Dokumentbeskrivelse til Arkivdel ved hjelp av en relasjon, i stedet for en attributt.  Det sikrer at API-klienter kan finne aktuell Arkivdel ved å slå opp href-verdien direkte, i stedet for å måtte søke opp aktuell Arkivdel med gitt SystemID-verdi.

**Comment by petterreinholdtsen** [comment]
Glemte å henvise til mangelmelding #101, som beskriver hvorfor relasjoner gir mer mening enn attributter for lenker til andre instanser i API-et.

**Comment by henningjensen** [comment]
Mappe har allerede relasjonen til arkivdel. Dokumentbeskrivelse mangler relasjonen.

Vi legger inn atributtene og relasjonslenkene.

**Comment by henningjensen** [comment]
Vi avventer til vi får mer bakgrunnsinformasjon fra Evry som sendte inn dette høringssvaret i utgangspunktet.

**Comment by petterreinholdtsen** [comment]
Når jeg leser igjennom denne mangelmeldingen på nytt, så slår det meg at, gitt at det skal være mulig å finne foreldreinstans for Dokumenbeskrivelse, Registrering, Mappe, Klasse og Klassifikasjonssystem, så vil en ved avlevering kunne utlede Arkivdel.  Ved deponering og avlevering vil det dermed være mulig å hente ut SystemID-verdien som trengs uten at det er en direkte kobling fra Dokumentbeskrivelse og Mappe.  Det gjør meg i tvil om det er noe poeng å legge inn denne direktekoblingen i andre entiteter enn de som er direktekoblet til Arkivdel.  Kan noen forklare hvorfor det trengs?

Argumentet mitt forutsetter dog at det beskrives hvordan en skal finne foreldreinstans, hvilket i dag ikke er godt beskrevet i API-spesifikasjonen.

**Comment by OmarLie** [comment]
Vedr referanseArkivdel og "..avventer .... mer bakgrunnsinformasjon fra Evry" 
Fra vår side er det viktig at det er samsvar mellom den tekstlige beskrivelsen av grensesnittet og implementasjonen (xsd filene).  Punktet kom opprinnelig opp ifm en uoverenstemmelse mellom disse.

Mappe og Klassifikasjonssystem må ha referanseArkivdel , men vi ser det ikke som nødvendig å legge inn på andre typer, dersom man ikke eksplisitt ønsker det skal være mulg å "overstyre" på under-objekter. 

Som nevnt over, vil man kunne utlede Arkivdel via foreldreinstansene.

**Comment by petterreinholdtsen** [comment]
Hei Omar, veldig hyggelig å se deg her. :)

[Omar Lie]
> Vedr referanseArkivdel og "..avventer .... mer bakgrunnsinformasjon fra Evry" 
> Fra vår side er det viktig at det er samsvar mellom den tekstlige
> beskrivelsen av grensesnittet og implementasjonen (xsd filene).
> Punktet kom opprinnelig opp ifm en uoverenstemmelse mellom disse.

Aha, nyttig å vite.  

> Mappe og Klassifikasjonssystem må ha referanseArkivdel , men vi ser
> det ikke som nødvendig å legge inn på andre typer, dersom man ikke
> eksplisitt ønsker det skal være mulg å "overstyre" på under-objekter.
>
> Som nevnt over, vil man kunne utlede Arkivdel via foreldreinstansene.

Kan du forklare hvorfor Mappe og Klassifikasjonssystem må ha
referanseArkivdel?  Holder det ikke med en relasjonsnøkkel som peker til
(liste med) riktig arkivdel(er) når det er aktuelt?

Når jeg sjekker arkivstruktur.xsd for n5v4, så finner jeg
referanseArkivdel i mappe, registrering og dokumentbeskrivelse men ikke
Klassifikasjonssystem.  Det samme gjelder n5v5.  Enhver instans av
Klassifikasjonssystem vil jo høre under en Arkivdel, og det er lagt opp
til relasjonsnøkler som peker "opp" og "ned" i datastrukturen i API-et.
Det virker dermed unødvendig å ha en egen attributt referanseArkivdel på
Klassifikasjonssystem.

Jeg er mer usikker på behoevet i Mappe, da jeg ikke forstår hvordan den
i så fall skulle brukes, og det derfor er uklart for meg om det er nok
med relasjonsnøkler eller om det er bedre med en attributt.  Dette er i
grunnen samme spørsmål som gjelder Kryssreferanse og
under/over/forrige/neste.

-- 
Vennlig hilsen
Petter Reinholdtsen

**Comment by tsodring** [comment]
Jeg opplever at der er to tråder her.

**1. referanseArkivdel er for tillegsreferanse**

referanseArkivdel-feltet brukes primært hvis feks an mappe eller registrering skal kobles til flere arkivdeler. Normalen er at disse arkivenhetene kobles ikke til flere arkivdeler. Men når periodisering skjer, kan det være slik at en mappe må kobles til to forskjellige arkivdeler.

Noark er jo teknologi uavhengig. Dersom det implementeres i en relasjonsdatabase vil arkivstruktur typisk implementeres med referanse* gjennom hele arkivstrukturen. Ingen andre arkivenheter har referanseTilForelder. Derfor blir referanseArkivdel litt forvirrende fordi i relasjonsdatabasen vil du automatisk ha laget en referanseArkivdel for å sikre arkivstrukturen som er i en 1:1 forhold, men du trenger en referanseArkivdel som er i en 1:m forhold.

Her er det vel egentlig snakk om en tolkning om hvordan det brukes i praksis kontra hvordan det er beskrevet i datamodellen. Krav 5.4.2 fra Noark standarden sier følgende 

> _En Mappe skal tilhøre en Arkivdel og en Arkivdel kan innehold ingen, en eller flere Mapper._

Men datamodellen (side 58, N5v4) viser at en mappe kan kobles til en arkivdel, mens på side 38 ser du at mappe.referanseArkivdel er en avhengighet til arkivdel. Det mangler bare en god forklaring hvordan det er tenkt dette skal brukes og jeg møter ofte at poenget bak dette attributtet feiltolkes. 

_Med forbehold at min tolkning her er feil, og hvis den er det vil jeg gjerne korrigeres på det._


Dette slår jo ut når du lager arkivstruktur.xml. Avhengig av når du lager XML, vil du ikke koble mappen til begge arkivdelene. Fordi den ene ar inaktiv, den andre aktiv. Uttrekket vil antageligvis lages på forskjellig tidspunkter. Jeg har også hørt at noen leverandører bruker ikke UUID til daglig og genererer UUID ved uttrekk. Hvis dette stemmer så vil en slik leverandør være nødt til å sørge for at UUID stemmer på tvers av uttrekkene, noe som kompliserer uttrekk betraktelig når uttrekk lages kanskje med noen års mellomrom.

**2. referanseArkivdel sin rolle i arkivstruktur**

> Kan du forklare hvorfor Mappe og Klassifikasjonssystem må ha referanseArkivdel?  Holder det ikke med en relasjonsnøkkel som peker til (liste med) riktig arkivdel(er) når det er aktuelt?

En mappe må kunne finne stien tilbake til arkivdel. Hvis du oppretter en mappe fra en klasse klasse->ny-mappe så *må* den klassen være koblet til en arkivdel. Her tror jeg praksis avviker litt fra standarden. Jeg tror mange implementerer systemene der *en* klassifikasjonsystem/liste av klasser deles på tvers av flere arkivdeler. Dette er gjort for enkelthetsskyld eller er noe som henger igjen fra Noark 4 (usikker hvorfor). I realiteten skal det opprettes et eget kopi av alle klassene for hver nytt arkivdel som bruker et sett med klasser. Jeg tror det er praksis som gjør at dette blir et problem, at det ikke er forklart godt nok i standarden hvordan dette skal tolkes/implementeres. Klassifikasjonssystem skal vel egentlig ikke ha referanseArkivdel, men arkivdel skal ha referanseKlassifikasjonssystem. Det er det som er fornuftig når du skal lage XML. Igjen tror jeg at dette tolkes vidt forskjellig der ute, men Noark er en konseptuell standard og er åpen til tolkning. Heldigvis skal tjenestegrensesnittet ikke være en konseptuell standard og da må det landes en entydig forståelse her.

_**Igjen, jeg vil gjerne korrigeres hvis min tolkning er feil.**_

**Comment by monadani** [comment]
27/06/2019 jeg har samme forståelse av dette som Thomas. @oivkru  er du enig? Kan du se på denne i dag?

**Comment by oivkru** [comment]
referanseArkivdel er for tilleggsreferanse, som Thomas skriver, og ikke en referanse til foreldreinstansen. Dette var beskrevet i Noark 5 versjon 4 side 47: 

_Arkivdeler kan brukes til å skille ut dokumenter som skal kasseres etter andre regler enn resten av dokumentene i mappen (f.eks. alle inngående dokumenter) eller registreringen (f.eks. alle vedlegg). Slike regler kan da knyttes til en egen arkivdel. Se mer om dette i kapittel 5.10 Bevaring og kassasjon, om kassasjon av dokumenttyper.

Det samme gjelder dokumenter som skal skjermes etter andre regler enn resten av dokumentene i mappen eller registreringen. Se mer under kapittel 6.6.1 Skjerming.

Dessuten kan det være tilfeller hvor noen dokumenter i en mappe eller registrering er arkivert på papir, mens resten av dokumentene er elektroniske. En egen arkivdel skiller da ut disse dokumentene. 

Arkivdeler som brukes til å angi andre kassasjonsvedtak, skjermingsregler og dokumentmedium enn de som gjelder for resten av innholdet i arkivet, vil være "tomme" – dvs. de har ikke egne barn. Mapper, registreringer og dokumentbeskrivelse som har referanse til slike arkivdeler, skal arve metadata fra disse.  Disse mappene, registreringene og dokumentbeskrivelsene vil indirekte også tilhøre arkivdelen som er utgangspunktet for den hierarkiske arkivstrukturen, men arv herfra blir overstyrt._

Det er altså ikke referanse i arkivstrukturen, men ut av arkivstrukturen. I den overordnete skissen av informasjonsmodellen på side 38 er dette illustrert med stiplete piler fra mappe, registrering og dokumentbeskrivelse til arkivdel. 

Denne siterte teksten ble tatt ut av Noark 5v5, siden beskrivelsen var utydelig og ikke ble konkretisert i faktiske krav. Vi gjorde en ryddejobb for å unngå at teksten ikke skulle beskrive krav til løsninger, som ikke også fremgikk av faktiske krav i standarden. Det er for eksempel ingen krav som sier at en slik referanseArkivdel skal overstyre arv fra foreldreinstans. 

Men det er mulig en forklaring på et tenkt bruksmønster som dermed også ble tatt ut. 

Usikker på om dette var svar på den opprinnelige issue...?

**Comment by monadani** [comment]
27/06/2019 da er vi enige om at dette ikke er en "issue", så denne issuen lukkes og vi går videre.
