### ISSUE TITLE
Mismatch in relations compared to Noark 5 v.3.1. spec [70]

### ISSUE THREAD

**Issue by henningjensen** [arkivverket/noark5-tjenestegrensesnitt-standard#50]
Noark 5 v.3.1 specifies Mappe *..1 Arkivdel, meaning Mappe must link to an Arkivdel. The service spec says Mappe *..0 ArkivdelThis violates requirement 5.4.2: "En Mappe skal tilhøre en Arkivdel og en Arkivdel kan innehold ingen, en eller flere Mapper."

Same goes for:Registrering - ArkivdelRegistrering - MappeKlasse - KlassifikasjonssystemRegistrering - Mappe.

ConclusionsArkitektum will change the model to show that a DokumentLink must have a parent Registrering.The spec should also be more clear on alternative parents, when it may (and must) be one of several.E.g. req. 5.4.2 and 5.4.3 should be removed - and better explained - like: "Ny - Mappe skal enten være tilknyttet arkivdel eller referanseForelderMappe eller klasse"

More on the same:Registrering must have a parent - either a Mappe, Klasse or ArkivdelKlasse must have a parent - either a Klassifikasjonssystem or a KlassePrimary Klasse is inherited from a parent Mappe to children of type Mappe and Registrering

Rev 27/10-17Still open. Arkivverket are now looking into possibilities for removing “model-related” requirements in the services spec, having this in the uml model instead. This however, raises questions on approval process.

Saken er migrert fra Arkivverkets Jira.

**Comment by hanber** [comment]
Det er modellen (Noark 5 v. 4.0 s. 38) som gjelder, ikke krav 5.4.2. (Tolkningen av dette kravet er at en _mappe_ skal tilhøre en _arkivdel_, enten direkte, eller via _klasse_ og _klassifikasjonssystem_)

**Comment by henningjensen** [comment]
Ta vekk krav 5.4.2 og 5.4.3 fra Mappe - kap 7

**Comment by petterreinholdtsen** [comment]
Kan noen bekrefte at mitt endringsforslag #97 er i tråd med det som er bestemt her?  Holder det å fjerne kravene, eller bør det formuleres ny tekst i tillegg?
