### ISSUE TITLE
Søk i virksomhetsspesifikke metadata [29]

### ISSUE THREAD

**Issue by henningjensen** [arkivverket/noark5-tjenestegrensesnitt-standard#51]
Virksomhetsspesifikke data

Page 24 says:Virksomhetsspesifikke metadata kan brukes for å legge ved mer data på enkelte objekter i kjernen. Disse vil ikke være søkbare i tjenestegrensesnitt.Søk i virksomhetsspesifikke data dekkes ikke av NOARK 5 tjenestegrensesnitt, men den enkelte arkivleverandør kan tilby tjenester som tilbyr søk i virksomhetsspesifikke data

Page 118 in Noark 5 v. 3.1 standarden.pdf says such data also has to be part of the Avlevering (submission). Further, this chapter states how such data can be specified in requests by using xml, also proving an xsd to describe the content.This may be customer specific data that should somehow be stored in ephorte. Is this to be understood as metadata beeing specific to ephorte? As if the example project types Byggesak, Prosess and Vedtak were types defined in ephorte - even though they are not defined in Noark 5.It has nothing to do with external systems having specific metadata they want to be stored in ephorte? E.g. one would want an external system's primary key value to be stored in ephorte (as a reference value).

Conclusions

a) We need to implement this on types as specified in the spec - and store such info in "div" (custom) fields on the relevant ephorte objects. The service-consumers will provide both the xsd describing the xml, so it can be stored together.

b) This may also be extended to support storing and reading such information by using ephorte-specific types, as the example project handles types Byggesak, Prosess and Vedtak - which are not defined in Noark 5.

If we implement point b, ephorte will need to provide the xsd for the our specific types.

Arkitektum 17/8 - Example:http://localhost:49708/api/arkivstruktur/Mappe?$filter=virksomhetsspesifikkeMetadata.bygningsnummer eq '12345678'Error in odata filter validation?

Could this be related to how odata gets access to metadata on "any" type for virksomhetsspesifikkeMetadata?

**Comment by henningjensen** [comment]
Tor Kjetil Nilsen
last year

Rev 20/10-17
Based on project meetings, this will not be prioritized with first version of the Noark 5 services implementation

**Comment by petterreinholdtsen** [comment]
Merk at bygningsnummer er beskrevet i mangelmelding #141 og endringsforslag #142, slik at en ikke skulle trenge å bruke API-feltet virksomhetsspesifikkeMetadata til felter relatert til NasjonaleIdentifikatorer hvis forslaget i #142 kommer inn.  Jeg håper uansett endringsforslag #78 også dekker behovet for søk i virksomhetsspesifikkeMetadata-felt.
