### ISSUE TITLE
Sletting - ferdigstille kapittelet?

### ISSUE THREAD

**Issue by henningjensen** [arkivverket/noark5-tjenestegrensesnitt-standard#53]
6.1.1.7 Slette objekter (Delete)Klienten sender en DELETE forespørsel på aktuell ressurs(url). Alle ressurslenker med rel=»self» kan potensielt slettes om bruker har nødvendige rettigheter. Respons gir statuskode 204 om ressursen er korrekt slettet.Et viktig krav i Noark 5 er at arkiverte elektroniske dokumenter ikke skal kunne slettes. Kontrollert sletting skal bare kunne foretas av autoriserte brukere i forbindelse med kassasjonSletting av Arkivdel – Kan også gjøres med oppdatering av arkivdel hvor det legges inn informasjon om sletting.Sletting av Dokumentbeskrivelse – her er flere type sletting så må gjøres med oppdatering?De som ikke har sletting datatype, hvordan skal de merkes/fjernes?Krav om logging nok?Skal ikke være mulig å slette uansett hvor mye rettigheter en bruker har? – Arkivverket må avklare dette

**Comment by henningjensen** [comment]
Hans Fredrik Berg
10 months ago

sletting skal ikke forekomme i arkivdel, bare dokumentbeskrivelse.

**Comment by henningjensen** [comment]
Tor Kjetil Nilsen
10 months ago

sletting er fjernet helt som datastruktur. Logg brukes i stedene til sporing av dette

**Comment by petterreinholdtsen** [comment]
En må kunne slette også arkivdeler, i hvert fall etter at de er eksportert ut av arkivet og avlevert arkivdeponi.  Det må naturligvis begrenses til svært priviligerte brukere.

**Comment by hanber** [comment]
Ja, det skal være mulig å slette _arkivdel_ gitt at betingelsene for dette er oppfylt, eksempelvis vellykket deponering/avlevering, priviligert bruker osv.

**Comment by petterreinholdtsen** [comment]
Kan det være en ide å markere hvilke objekter som kan slettes ved å bruke Allow-hodefeltet omtalt i mangelmelding #29?  Det gir en standardisert måte å annonsere om noe kan slettes eller ikke.  Som omtalt i mangelmelding #18, så sier punkt 5.13.23 på side 89 at det skal være mulig å slette også søkeresultater:

> Det bør være mulig å slette mange dokumentvarianter samtidig, f.eks. alle dokumentvarianter som er funnet etter et søk.

Jeg tolker dette til å bety at en kan gjøre DELETE på 'self'-URLen til et gitt søkeresultat.

**Comment by petterreinholdtsen** [comment]
En ting som er viktig rundt sletting, er at API-et gjør det mulig å hente ut all informasjonen som trengs for å lage deponi-XML av det arkiverte materialet, og dernest gjør det mulig å kassere avlevert materiale når det skal gjøres.  Det stiller krav til fungerende DELETE-operasjon på alt som kan kasseres, for priviligerte brukere.  Det bør antagelig være to ulike privilegier, et som kan lese ut alt som skal deponeres, og et høyere privilegiesett for script som skal gjøre endelig deponeringsuthenting og kassering.

**Comment by tsodring** [comment]
Dette er nok en av de tingene som er veldig utydelig i tjenestegrensesnittet. Men jeg oppfatter at sletting i arkivsammenheng er generelt et vanskelig tema og noe man egentlig ikke ønsker å ta stilling til. Det er flere typer sletting som er med i bildet.

1. Opps jeg lastet opp noe jeg ikke skulle gjort

Klassikeren, feilbruk av systemet. Her kan en bruker ha opprettet en klasse som ikke skulle vært opprettet. Ikke noe er lagt til og denne kan trygt slettes. Det kan feks være at man lagde en klasse for en byggning som ikke finnes og man ikke ønsker at det skal være i systemet lenger. Den kan man da slette med en POST DELETE og så er den borte. Det vil kanskje vises i loggen at det har skjedd, men logging og sporing er ikke en del av tjenestegrensesnittet så da kan vi ikke gå utifra at det finnes. Noen vil implementere _soft delete_, dvs at den er bare merket som slettet og kan alltid spores fram i databasen.

2. Uhjemlet kassasjon

Her går brukeren inn og sletter ting som de ikke skulle ha slettet eller ikke har lov til å slette. Så vidt jeg se er det teoretisk mulig at en gjest-bruker kan via  tjenestegrensesnittet gå inn og utføre en DELETE på en arkiv og slette hele arkivet. Hvis CASCADE DELETE er på med referanseintegritet i databasen så vil jo alt forsvinne. Det er kun en vag setning som hinter om dette.

> om bruker har nødvendige rettigheter

Når der ikke er definert noen steder kan "nødvendige rettigheter" bety at de er pålogget, avhengig av hvem og hvordan tjenestegrensesittet er implementert. Det er flere eksempler der dårlig implementasjoner, spesielt av eldre programvare, som får en nett-tjenestegrensesnitt resulterer i at brukere gjør ting de ikke skulle. Jeg tror dette er ofte noe som bygger på en tolkning hos leverandør at **autentisert = autorisert** .

3. Kassasjon

Her er det også en hint:

> Kontrollert sletting skal bare kunne foretas av autoriserte brukere i forbindelse med kassasjon

Igjen er ikke dette godt nok beskrevet. Med godviljen kan vi jo lese standarden for å få mer informasjon.  Kassasjon i seg selv skjer kun på dokumenter

> Kassasjon vil si at elektroniske dokumenter fjernes fra arkivstrukturen

så det å slette deler av arkivstruktur omfattes ikke som kassasjon. Så det å utføre en POST DELETE på en arkivdel, slik jeg tolker det når jeg legger godviljen til, er at det først må være en POST Kassasjon med informasjon om hjemmel. Dersom det finnes kan jeg slette alle dokumenter koblet til arkivdelen. Når slettingen er utført skal jeg ta en POST Utfoertkassasjon. Da har jeg utført en kassasjon. Men det står ingenting om hva som skjer dersom vi får en timeout fra disklagring og prosessen blir forstyrret.  Logikken jeg skisserer over er noe jeg bare går utifra er riktig.  Når tjenestegrensesnittet bare skal være en CRUD tilnærming da må det vil bli sånn.

I standarden omtales det en kassasjonsliste som skal _"være en hjelp i selve kassasjonsarbeidet"_. Men denne er ikke definert. Kanske det går ann å lage det via en OData spørring.

Noen tanker som vi kanskje bør ha i bakhodet her.

Hvis Datatilsynet pålegger sletting av informasjon fra et arkivsystem, hvordan kan og skal det gjøres i tjenestegrensesnittet? Jeg forstår at vi være nødt til å slette et dokument men hva hvis et slettevedtak inneholder også å fjerne personopplysninger som feks personnummer og navn? Hvilken opplysninger blir liggende igjen i arkivstruktur? Det snakkes om en "logg", hvis slettingen er logget vil vedtaket omfatte loggen også?

Jeg er usikker hvor mye av dette tilhører i tjenestegrensesnittet og hvor mye tilhører i implementasjon. En del av business logikken ligger utenfor rekkevidden til en CRUD tjenestegrensesnitt, men det bør forklares litt mer hvordan dere ser for seg at ting skal skje.

Problemet med sletting er kanskje er at DELETE på en entitet/liste resulterer i at noe blir slittet.  Spørsmålet er hvorvidt metadata-konseptet kassasjon har noe å si denne sammenhengen?

Kan forøvrig si litt om hva nikita gjør. DELETE kan utføres på alt du eier. Du kan DELETE entiteter og lister og kan filtrere DELETE lister med ODATA. Kassasjon og utfoertKassasjon er implementert i datamodellen men ikke i logikken. Slette problematikken vi jobber med er hvorvidt vi skal har en rollebasert eller en tilgangskontrollliste tilnærming til å slette. Rollebasert, som jeg oppfatter Noark, generelt sett, hinter mot å være er for svak og vi må ha en tilgangskontrollliste tilnærming til det.

**Comment by oivkru** [comment]
Sletting og kassasjon er vanskelig å forklare, og blir ofte misforstått. Riktignok foreslås det i NOU’en om ny arkivlov at begrepet kassasjon skal erstattes med begrepet sletting, men jeg vet ikke hvor gjennomtenkt det er (ref. bl.a. politiregisterforskriften § 16-2). Sletting kan skje ved arkivbegrensning (lagret noe i mappa som ikke har verdi som arkiv/dokumentasjon, eller opprettet noe ved en feil, osv.), kontrollert kassasjon, eller at det slettes i produksjonssystemet etter at det er overført til arkivdepot. Uhjemlet kassasjon skal jo ikke forekomme, og dette er jo noe av det viktigste som skiller et arkivsystem fra et hvilket som helst annet system som lagrer dokument/informasjon: all sletting skal være kontrollert, i henhold til virksomhetens plan for bevaring av informasjon – den enkelte bruker skal ikke ha mulighet for å slette noe uten at det skjer i henhold til virksomhetens regler for sletting.  

MoReq2010 er tydeligere på forskjellen mellom destruction (sletting, men tar vare på visse metadata og logging) og deletion (sletting uten å etterlate spor). 

I Noark 5 er kassasjon beskrevet i et eget kapittel, mens sletting er omtalt i ulike krav spredt utover i ulike kapittel: 
•	Det generelle kravet 2.2.1 sier at «En Noark 5-løsning skal ha tjenester/funksjoner for å lagre, gjenfinne, endre og slette data og utvalg av data i henhold til metadatabeskrivelsene i alle arkivenheter og tilhørende klasser som er dokumentert i de konseptuelle modellene og metadatatabellene i Noark 5.» 
•	Krav 2.3.2 og 2.3.5 sier at når en tjeneste/funksjon sletter et helt arkiv/en arkivdel, skal dette logges. Det er ikke angitt betingelser for sletting av arkiv/arkivdel.
•	Krav 2.7.14 til 2.7.25 omhandler sletting av dokumentversjoner, dokumentvarianter og dokumentformater, dvs. at dokumentobjektet slettes, slik at dokumentbeskrivelse får en forekomst av sletting per dokumentobjekt som er slettet, til forskjell fra kassasjon og utfoertKassasjon. 
•	Krav 2.8.4 og 5 sier at kryssreferanse kan slettes.
•	Presedenser kan ikke slettes, jf. Krav 2.8.18 og 19.
•	Det skal ikke være mulig å slette en mappe som er avsluttet (krav 3.2.3)
•	Det skal ikke være mulig å slette en saksmappe som inneholder journalposter med status ekspedert, journalført eller arkivert (krav 3.2.12)
•	Det skal ikke være mulig å slette en registrering som er arkivert (krav 3.2.16), jf. Krav 2.7.7 som sier at det ikke skal være mulig å slette et arkivert dokument, men som også sier at eldre versjoner av dokumentet skal kunne slettes.
•	Det skal ikke være mulig å slette en journalpost som har eller har hatt status ekspedert, journalført, arkivert eller utgår (krav 3.2.19).
•	Det bør helle rikke være mulig å slette journalpost med status ferdigstilt fra saksbehandler eller godkjent av leder (krav 3.2.20), men dette er ikke forbudt. 
•	Det bør være mulig å slette en journalpost med status reservert. 

Dette er altså variantene av sletting i Noark 5, som ikke er kassasjon. Noen har krav om at sletting skal logges, noen har krav om et eget sletteobjekt som dokumenterer slettingen, mens andre ikke har detaljerte krav i det hele tatt. Det er godt mulig standarden bør bli mer gjennomarbeidet på akkurat dette. 

Merk også at det ikke er konkrete krav til hvem (hvilke roller) som skal kunne slette, kun for noen av kravene at det skal være brukere som er autorisert – standarden tar ikke stilling til hvem som skal autoriseres, det må være opp til virksomheten selv (jf. § 2-10 i den gamle arkivforskriften, om at ledelsen i organet må bestemme hvem som skal kunne gjøre ulike registreringer i systemet).

**Comment by monadani** [comment]
27/06/2019 Mona skrive forslag til ny tekst:
6.1.1.11 Slette objekter (Delete) 783 Klienten sender en DELETE forespørsel på aktuell ressurs(url). Alle ressurslenker med rel="self" kan potensielt slettes om 784 bruker har nødvendige rettigheter. Respons gir statuskode 204 om ressursen er korrekt slettet. 785 Et viktig krav i Noark 5 er at arkiverte elektroniske dokumenter ikke skal kunne slettes. Kontrollert sletting skal bare kunne 786 foretas av autoriserte brukere i forbindelse med kassasjon 787 Sletting av Arkivdel – Kan også gjøres med oppdatering av arkivdel hvor det legges inn informasjon om sletting. 788 Sletting av Dokumentbeskrivelse – her er flere type sletting så må gjøres med oppdatering? 789 De som ikke har sletting datatype, hvordan skal de merkes/fjernes?Krav om logging nok?Skal ikke være mulig å slette uansett 790 hvor mye rettigheter en bruker har? – Arkivverket må avklare dette

**Comment by monadani** [comment]
I Noark 5 er kassasjon beskrevet i et eget kapittel, mens sletting er omtalt i ulike krav spredt utover i ulike kapitler i standarden.

Et viktig krav i Noark 5 er at arkiverte elektroniske dokumenter ikke skal kunne slettes. Et arkivert dokument (Journalstatus på Journalpost og Dokumentstatus på Dokumentbeskrivelse) har følgende kjente verdier:

Journalført (J), Ferdigstilt fra saksbehandler (F), Godkjent av leder (G), Ekspedert (E), Utgår (U), Midlertidig registrering av innkommet dokument (M), Saksbehandler har registrert innkommet dokument (e-post) (S) og Reservert dokument (ikke ferdigstilt) (R).

Dokumenter med status R (Reservert dokument) kan slettes. Dokumenter med status M (Midlertidig) kan benyttes ulikt i forskjellige organ / systemer, så disse kan eksempelvis ikke slettes om de er overført fra et fagsystem hvor de har status F og er satt opp til å få status M i Noark-systemet.
 
For dokumenter som ikke er knyttet til Journalpost, må man se på verdier knyttet til Dokumentbeskrivelse og Dokumentstatus når man vurderer om et dokument kan slettes.

Når det foreligger behov for autorisert kassasjon sender klienten en DELETE forespørsel på aktuell ressurs (URL). Alle ressurslenker med relasjonsnøkkel "self" kan potensielt slettes om autorisert bruker har nødvendige rettigheter. Respons har statuskode 204 hvis ressursen ble slettet.

+ kap 7 merknad mht status S

**Comment by monadani** [comment]
obs: Saksbehandler har registrert innkommet dokument (hovedsaklig e-post) (S)
