### ISSUE TITLE
Skal klasse ha relasjonsnøklene (ny-)klassifikasjonssystem?

### ISSUE THREAD

**Issue by petterreinholdtsen** [arkivverket/noark5-tjenestegrensesnitt-standard#67]
Dette er en mangelmelding som kun er registrert på github, og ikke er sendt inn til Arkivverkets postmottak.  Se også https://github.com/petterreinholdtsen/noark5-tester/blob/master/mangelmelding/sendt/2019-02-09-klassifikasjonssystem-under-klasse.md .

 ------------------  ---------------------------------
           Prosjekt  NOARK 5 Tjenestegresesnitt
           Kategori  Versjon 1.0 beta
        Alvorlighet  kommentar
       Meldingstype  trenger klargjøring
    Brukerreferanse  pere@hungry.com
        Dokumentdel  7.2.1.12
         Sidenummer  115
        Linjenummer  n/a
    Innsendingsdato  2019-02-09
 ------------------  ---------------------------------

Beskrivelse
-----------

Dette er relatert til tilsvarende [mangelmelding #33 om klassifikasjonssystem](https://github.com/arkivverket/noark5-tjenestegrensesnitt-standard/issues/33).

Spesifikasjonens del 7.2.1.12 (Klasse) på side 115 lister opp to relasjonsnøkler som gir inntrykk av at det skal være mulig å lage et underklassifikasjonssystem knyttet til et eksisterende klasse samt liste opp de tilknyttede underklassifikasjonssystemene:

 * http://rel.kxml.no/noark5/v4/api/arkivstruktur/ny-klassifikasjonssystem/
 * http://rel.kxml.no/noark5/v4/api/arkivstruktur/klassifikasjonssystem/

Tilsvarende relasjon i for eksempel Arkiv for å lage Arkivdel (ny-arkivdel), og i Arkivdel for å lage mappe (ny-mappe) og registrering (ny-registrering) og der er det mer åpenbart hva relasjonene betyr.

Det er så vidt jeg kan se ingenting i Noark 5-standarden som indikerer at det skal være mulig å ha et "under"-klassifikasjonssystem i klassestrukturen.  Dermed virker dette å være en skrivefeil i tjenestegrensesnittet.  Dette synet styrkes når en ser i [arkivstruktur.xsd](http://schema.arkivverket.no/N5/v4.0/arkivstruktur.xsd) der elementet klasse ikke har støtte for underklassifikasjonssystem.

Det vil være nyttig for API-klienter å kunne slå opp "foreldre"-klassifikasjonssystem for en klasse, der slik finnes, men det bør antagelig bruke en annen relasjonsstruktur.

De to relasjonene for å lage nytt og liste opp klassifikasjonssystem er allerede listed opp under del 7.2.1.2 (Arkivdel), der de virker å høre hjemme i henhold til Noark 5-standarden.

Ønsket endring
--------------

Endre relasjonsnøkkel-listen på side 115, fjern disse relasjonene:

 * http://rel.kxml.no/noark5/v4/api/arkivstruktur/ny-klassifikasjonssystem/
 * http://rel.kxml.no/noark5/v4/api/arkivstruktur/klassifikasjonssystem/

**Comment by hanber** [comment]
Vi venter med operasjoner på klassifikasjonssystem til en senere versjon, i tråd med antakelsen om at nytt klassifikasjonssystem neppe vil bli utført fra et fagsystem (unntatt dersom det utvikles en administrasjons-applikasjon som kan trenge det, hvilket vi kke tar høyde for her).

**Comment by petterreinholdtsen** [comment]
Slik jeg forstår dette er det en relativt åpenbar skrivefeil i spesifikasjonsteksten, i en del som må være korrekt for at en API-tjeneste skal kunne stå på egne ben.  Dette har ingenting med hva et fagsystem trenger eller ikke.

**Comment by petterreinholdtsen** [comment]
Når jeg tar en nærmere titt på kapittel 7 ser jeg at det er flere ny-*-referanser som forvirrer meg.  For eksempel har Registrering, Mappe og Saksmappe alle relasjonen http://rel.kxml.no/noark5/v4/api/arkivstruktur/ny-klasse/.  Hva betyr det der?  Ingen av dem kan ha "underklasser".  Kanskje er det som trengs er en beskrivelse av hva hva hver enkelt relasjon betyr når den er oppført/tilknyttet en instans, for å forklare konkret hva det betyr i hvert enkelt tilfelle.  Noen peker "oppver", andre peker "nedover" i hierarkiet av instanser i databasen, men det er ikke åpenbart hvilke som peker hvilken vei.

For eksempel, gitt en instans av Dokumentbeskrivelse, hvordan finner en ut hvilken instans av Registrering den er knyttet til?  Er det en attributt registrering som peker til en liste med relasjonslenker, ala dette:

GET .../dokumentbeskrivelse/d84a9470-4fd9-11e9-92b5-bf7bf9f32627
```
{
   [...]
   "registrering": [
       "http://localhost:49708/api/arkivstruktur/registreing/b75d726e-4fd9-11e9-89e0-479e4aa411ae",
       "http://localhost:49708/api/arkivstruktur/registrering/c3ac6b24-4fd9-11e9-8d11-973ec9a46423"
    ],
    [...]
}
```

Alternativt, skal en bruke relasjonslenker i _links for å peke til "foreldrene"?  Jeg vet ikke hvordan det i så fall skal se ut, gitt at rel-lenkene i _links skal forekomme maksimalt en gang i en gitt _links-liste.

Og gitt at det er mulig å ha en Dokumentbeskrivelse-instans som er knyttet til mer enn et registrering, hvordan knyttes den til registrering nummer to?  En kan jo ikke bruke ny-dokumentbeskrivelse-relasjonen i den andre registreringen, da den jo vil opprette en ny Dokumentbeskrivelse-instans og ikke knytte en eksisterende til ønsket Registrering-instans.  Hvis tanken er å bruke relasjoner til ny-<klasse> og <klasse> til foreldrelenker, så er jeg redd jeg ikke forstår hvordan dette skal fungere.

**Comment by petterreinholdtsen** [comment]
Se også #33.

**Comment by petterreinholdtsen** [comment]
Ved nærmere ettertanke er det kun relasjonsnøkkelen ny-klassifikasjonssystem som er feilplassert.  De øvrige feilene (ny-klasse i Registrering, Mappe, Saksmappe får tas i en annen mangelmelding.
