### ISSUE TITLE
Hvordan skal innholdet i filstørrelse (M707) tolkes?

### ISSUE THREAD

**Issue by petterreinholdtsen** [arkivverket/noark5-tjenestegrensesnitt-standard#69]
Dette er en kopi av mangelmelding sendt inn til Arkivverket, se også https://github.com/petterreinholdtsen/noark5-tester/blob/master/mangelmelding/sendt/2017-05-26-m707-filstoerrelse.md .

Hovedfeilen er uklarheter i Noark 5s metadatakatalog (både versjon 4 og 5), som får konsekvenser for tjenestegrensesnittet, som bør endres til å gjøre tolkningen av feltet utvetydig.

 ------------------  ---------------------------------
           Prosjekt  NOARK 5
           Kategori  Versjon 4.0
        Alvorlighet  protest
       Meldingstype  trenger klargjøring
    Brukerreferanse  thomas.sodring@hioa.no
        Dokumentdel  Vedlegg 1
         Sidenummer  61
        Linjenummer  n/a
    Innsendingsdato  2017-05-26
 ------------------  ---------------------------------

Beskrivelse
-----------

M707 filstørrelse (filstoerrelse i XSD) er definert i vedlegg 1 (Metadatakatalog) til Noark 5 versjon 4.0, og med følgende beskrivelse «Definisjon: Størrelsen på fila i antall bytes oppgitt med desimaltall Kilde: Registreres automatisk i forbindelse med eksport for avlevering Kommentarer: (ingen)».  I metadatakatalog.xsdl er den oppført med datatype «string» .

Et [desimaltall](https://no.wikipedia.org/wiki/Desimaltall) er i følge definisjonen i norsk Wikipedia, «tall som er satt sammen av en heltallsdel og en fraksjonsdel. Disse to delene er skilt med et desimalskilletegn. Et eksempel kan være tallet «49,90» der heltallsdelen er «49» og fraksjondelen er «90».» Store Norske Leksikon bekrefter denne språkbruken blant annet i beskrivelsen av [numerisk metode](https://snl.no/numerisk_metode).

At definisjonen bruker «desimaltall» tyder dermed på at størrelsen skal kunne være brøkdeler av en byte, hvilket ikke gir mening.  Er tanken at det skal være mulig å lagre størrelsen i kibibytes, kilobytes eller lignende, dvs. lagre «1,2 KiB» i feltet?  Dette vil i så fall kreve klare regler for avrunding og gjøre det vanskelig å bruke verdien til å sjekke at komplett fil er lastet opp og ned på grunn av avrunding.  For eksempel er det vanskelig å vite hva størrelsen egentlig er hvis det står 1,2 KiB, da 1,2*1024 jo er 1228,8, og størrelsen jo må være enten 1228 eller 1229 bytes.

I tillegg kommer tolkningsutfordringer når det gjelder f.eks. «KB», som både kan tolkes som verdi ganger 1000 eller 1024.  Her må spesifikasjonen klargjøre hvordan slike verdier skal tolkes hvis det skal være mulig med desimaltall.

En annen utfordring er at desimaltall-formater er språkavhengig, der noen bruker punktum som desimalskille, mens andre bruker komma.

Det vil være enklere for alle, både API-klienter og andre implementasjoner, hvis dette feltet har en klar og entydig betydning, og alltid er et heltall større eller lik null som oppgir filstørrelsen i bytes.

Dette bør ha en konsekvens på hvordan filstoerrelse er definert i metadatakatalog.xsdl.  Følgende forslag kan definere filstoerrelse som heltall større eller lik 0.

```
<xs:simpleType name="filstoerrelse">
  <xs:annotation>
    <xs:documentation>M707</xs:documentation>
  </xs:annotation>
  <xs:restriction base="xs:string">
    <xs:pattern value="[0-9]+"/>    
  </xs:restriction>
</xs:simpleType>
```

Dette vil også gjøre det klart at kun ikke-negative heltall aksepteres i dette feltet.

En annen ide er å bytte type fra xs:string til en numerisk type. Dette bør i så fall gjøres på en måte som ikke begrenser mulige filstørrelser.  Feltet «filstørrelse» er brukt på sidene 29, 50, 52, 54, 105 og 203 i spesifikasjonen for Noark 5 Tjenestegrensesnitt. Hvis typen skal endres i metadatakatalog.xsdl så må det endres også her.

Ønsket endring
--------------

Endre oppføringen for M707 på side 61 i vedlegg 1 (Metadatakatalog) til Noark 5 versjon 4.0, bytte ut

> Størrelsen på fila i antall bytes oppgitt med desimaltall

til

> Størrelsen på fila som en tekststreng med antall bytes i oppgitt som
> et ikke-negativt heltall i titallsystemet, f.eks. "123456890".

Endre beskrivelsen av M707 i metadatakatalog.xsdl, bytt ut

> ```
> <xs:restriction base="xs:string"/>
> ```

med

> ```
> <xs:restriction base="xs:string">
>   <xs:pattern value="[0-9]+"/>
> </xs:restriction>
> ```

Endre feltbeskrivelsen i del 7.2.1.7 (Dokumentobjekt) på side 105 i spesifikasjonen for Noark 5 tjenestegrensenitt 1.0 beta fra

> Definisjon: Størrelsen på fila i antall bytes oppgitt med
> desimaltall

til

> Definisjon: Størrelsen på fila som en tekststreng med antall bytes i
> oppgitt som et ikke-negativt heltall i titallsystemet,
> f.eks. "123456890".

**Comment by petterreinholdtsen** [comment]
Siden denne mangelmeldingen ble skrevet har jeg kommet over eksempler som bruker verdien som et fritekstfelt:

```
            <filstoerrelse>87 kB</filstoerrelse>
            <filstoerrelse>87kB</filstoerrelse>
```

Det er håpløst for en API-klient å skulle tolke slike verdier, da en ikke kan vite om kB henviser til 1000 bytes eller 1024 bytes, og antagelig må håndtere både kB, kb, kib og alle andre varianter for kilobyte, megabyte, terrabyte, petabyte etc etc...

**Comment by petterreinholdtsen** [comment]
Når API-et bruker JSON, så kan en med fordel la dette feltet være 'number'.  Som en kan se i RFC og f.eks. http://json.org/, er det ingen grenser for hvor mange siffer et JSON-nummer kan ha.  Det åpner riktignok for vitenskapelig tallnotasjon (f.eks. 3.2e10), men det bør ikke være noe problem så lenge definisjonen er entydig og klar.  Det viktigste i så måte er vel å sikre at det ikke er begresninger på hvor store tall som kan brukes, da det vil begrense hvor store filer som kan arkiveres.

**Comment by joergen-vs** [comment]
I Noark 5 v5.0 vil filstoerrelse få typen integer, som ikke er begrenset oppover på lik linje med json's number-type. I tillegg blir det en begrensing på verdier høyere eller lik 0 (tom fil). Notasjon er bytes, og krever ingen ytterligere forklaringer i feltet.

  <xs:simpleType name="filstoerrelse">
    <xs:annotation>
      <xs:documentation>M707</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="0"/>
    </xs:restriction>
  </xs:simpleType>

**Comment by petterreinholdtsen** [comment]
Godt å høre.  Da bør API-spesifikasjonen skrives om tilsvarende, det er ingen grunn til å akseptere fritekststrenger i et tallfelt som i fremtiden vil være heltall, ikke streng.

**Comment by hanber** [comment]
Vi gjør det slik Jørgen (og Petter) foreslår.

**Comment by petterreinholdtsen** [comment]
Merk at i mangelmelding #25 er det foreslått å ikke akseptere opplasting av tomme filer (filstoerrelse=0).  Er det en grunnen til at tomme filer aksepteres i depot-XML-formatet?

**Comment by petterreinholdtsen** [comment]
Hvis typen endres fra 'string' til 'integer' for feltet, så trenger en vel ikke si at verdien er i tiltallsystemet, og eksemplet blir også litt overflødig?

Jeg foreslår dermed at ```Definisjon: Størrelsen på fila i antall bytes oppgitt med desimaltall . ``` endres til ```Definisjon: Størrelsen på fila som en tekststreng med antall bytes i oppgitt som et heltall større enn 0.```

Merk at jeg her sier at tomme filer ikke aksepteres.  Jeg ser ikke helt poenget i å "arkivere" tomme filer, det er jo i praksis bare et filnavn med tidsstempel og eierskap som arkiveres.

Skal jeg lage PR på endringen for å få den inn i teksten, eller holder det med beskrivelsen her?

**Comment by petterreinholdtsen** [comment]
Jeg tok med en litt annen variant i forslag til forbedret beskrivelse av opplastingsprosessen.  Mulig den bør byttes ut med definisjonen som er brukt i oppdatert metadatakatalog, men den teksten har jeg ikke sett.

**Comment by petterreinholdtsen** [comment]
Det har i ettertid slått meg at selv om JSON og XML håndterer uendelig antall siffer i heltall helt fint, så gjør de færreste SQL-databaser det.  Det gjør det kanskje lite lurt å velge datatyper i grensesnittet som ikke kan lages i SQL-databaser?

**Comment by joergen-vs** [comment]
Hvor mange filer på 8 exabyte [bigint], eller for den saks skyld, 2 gigabyte [int], håndteres i en database?

**Comment by petterreinholdtsen** [comment]
[Jørgen]
> Hvor mange filer på 8 exabyte [bigint], eller for den saks skyld, 2
> gigabyte [int], håndteres i en database?

Ingen aning.  Hvordan tenkte du det er relevant for en klar og entydelig
spesifiksjon?  Video passerer gjerne 2 GiB, i hvert fall.

Vi har opplevd år 2000-overgangen, GPS-ukenummeroversvømmelsen kommer
neste måned og år 2038-oversvømmelsen kommer om ikke lenge.  Alle disse
velkjente problemene forteller meg at det er dumt å ikke planlegge for
fremtiden, og at det bør være klart og tydelig beskrevet hva som skal
gjøres når verdien blir for stor for feltet sitt for å unngå kaos og
forvirring i fremtiden.

Det enkleste er naturligvis å kreve uendelige verdiområde, men jeg er
usikker på om det er realistisk og lurt.

-- 
Vennlig hilsen
Petter Reinholdtsen

**Comment by joergen-vs** [comment]
En meget dårlig metode er å si at størrelsen er en tekststreng, for så å legge begrensing på innholdet at det er et eller flere tall [<xs:pattern value="([0-9])+"/>].
Problemet blir den automatiske valideringen og konvertering i programvare kan ta opp _mye_ tid.
På nåværende tidspunkt finnes det ingen bedre løsning.

**Comment by petterreinholdtsen** [comment]
[Jørgen]
> En meget dårlig metode er å si at størrelsen er en tekststreng, for så
> å legge begrensing på innholdet at det er et eller flere tall
> [<xs:pattern value="([0-9])+"/>].  Problemet blir den automatiske
> valideringen og konvertering i programvare kan ta opp _mye_ tid.  På
> nåværende tidspunkt finnes det ingen bedre løsning.

I og med at API-tjeneren ikke er XML, men et program som kan tolke og gi
tilbakemelding til API-klientet, så finnes det andre og kanskje bedre
løsninger.  Vi kan f.eks. si at det er en minimums-maksverdi og
dokumentere hvordan klienten skal forholde seg til feilmeldingen som
kommer hvis filen som forsøkes lastet opp er for stor.

Kanskje det bør defineres en måte for API-tjenesten å fortelle klienter
hvor store filer den håndterer?  Da kan grensen endres over tid, etter
hva API-tjeneren er i stand til å håndtere.

-- 
Vennlig hilsen
Petter Reinholdtsen

**Comment by petterreinholdtsen** [comment]
Mekanismen for å publisere produktinformasjon i mangelmelding #98 kan kanskje brukes til å annonsere maks-størrelsen på 'integer' i en API-tjeneste?
