### ISSUE TITLE
Fjern formulering som krever ekstra innsats for å hindre søk

### ISSUE THREAD

**Issue by petterreinholdtsen** [arkivverket/noark5-tjenestegrensesnitt-standard#79]
Dette er mangelmelding sendt inn til Arkivverket, se også https://github.com/petterreinholdtsen/noark5-tester/blob/master/mangelmelding/sendt/2019-03-24-soek-i-alt.md .

 ------------------  ---------------------------------
           Prosjekt  Noark 5 Tjenestegresesnitt
           Kategori  Versjon 1.0 beta
        Alvorlighet  protest
       Meldingstype  trenger klargjøring
    Brukerreferanse  pere@hungry.com
        Dokumentdel  7.2.1 (Arkivstruktur / Registrering)
         Sidenummer  47
        Linjenummer  n/a
    Innsendingsdato  2019-03-24
 ------------------  ---------------------------------

Denne teksten er del av en samling innspill til Noark5-standarden tilgjengelig fra [https://github.com/petterreinholdtsen/noark5-tester/](https://github.com/petterreinholdtsen/noark5-tester/).

Beskrivelse
-----------

I dokumentdel 7.2.1 (Arkivstruktur), like under UML-diagrammet som viser Registrering, så står det følgende (min utheving):

> Her må dokumentene nødvendigvis bli registrert, men dette skal skje
> på en automatisk måte og med minst mulig metadata.  **Denne typen
> dokumenter skal ikke kunne søkes fram etter innhold**, og de skal
> heller ikke inngå i den ordinære identifikasjonen (nummereringen) av
> journalposter.

Formuleringen gir inntrykk at at det må gjøres ekstra innsats når en lager API-implementasjonen for å hindre søk som det ellers ville være naturlig fungerte på samme måte som søk på alle andre dokumenter og metadata i arkivet.  Dette fremstår som helt urimelig.  Det som gir mening, både datafaglig, arkivmessig og forsåvidt for å understøtte åpenhet i et demokratisk samfunn, er å la slike oppføringer fungere som alle andre oppføringer i arkivet.

Ønsket endring
--------------

Bytt ut setning "Denne typen dokumenter skal ikke kunne søkes fram etter innhold, og de skal heller ikke inngå i den ordinære identifikasjonen (nummereringen) av journalposter." fra avsnittet som starter med "I fysiske sakarkiver har det vært vanlig å legge..." på side 47 i spesifikasjonen med følgende formulering:

> Denne typen dokumenter tildeles ikke identifikasjonen
> (nummereringen) i motsetning til journalposter.

**Comment by petterreinholdtsen** [comment]
Er det noe uklart her når det gjelder å fjerne formuleringen som nekter systemer å implementere søk på enkelte data i arkivet?  Trengs det henvisning for lov, forskrift eller rundskriv før endringen kan komme inn?

**Comment by tsodring** [comment]
Jeg husker vagt en diskusjon under fagdagen hos dere fjor, lurer på om det var Martin Bould som nevnte noe om føringer som hadde kommet rundt interne dokumenter når arbeidet med Noark 5 kom i gang. Mener at det ble sagt at det var tullete føringer. Jeg oppfatter at ArkivNotat er et forsøk på å ta tak i den problemstillingen. 

Hvis det jeg mistenker er det som ligger til grunn for teksten og at ArkivNotat gjør denne teksten overflødig nå så det er godt argument for å standardisere opp mot Noark 5 versjon 5. Da burde alle være glad!

**Comment by petterreinholdtsen** [comment]
Jeg antar du snakker om [fagdagen 19. november 2018](https://www.arkivverket.no/forvaltning-og-utvikling/noark-standarden/hva-skjer-med-noark/fagmote-om-noark-19-11-2018), der en kan høre Martin Boulds innspill rundt dette fra 1:46 i opptaket fra møtet.  Det er bedt om innsyn i dokumentet han viser til i https://www.mimesbronn.no/request/horingsuttalelse_om_arkiv_og_noa , så kan vi finne ut hva som konkret sto i det høringssvaret.  Slik jeg forstår det, er dette kravet til å nekte søkefunksjonalitet i arkivsystemet nå fjernet, dermed skal den heller ikke være med i denne API-spesifikasjonen.

**Comment by tsodring** [comment]
I Noark 4 standarden (Riksarkivet 17.08.2005) står det følgende (side 60) om dette mener jeg:

> Dette kapitlet ble fastsatt som et tillegg til Noark-4 01.03.2004. De fleste kravene i dette
> kapitlet har fått typebetegnelsen O3, og kommer dermed på toppen i et hierarki med O2,
> O1 og O som underliggende nivåer.
> Visse typer arkivdokumenter skal kunne arkiveres selv om de ikke er journalført, jf.
> arkivforskriften § 2-6 første ledd. I et papirbasert arkiv legges slike dokumenter i
> saksomslaget for den aktuelle sak, uten noen form for registrering, og det finnes dermed
> ingen spor etter dem i Noark-systemet. I et elektronisk arkiv skal dokumentene arkiveres
> (lagres) i Noark-systemet, og systemet må derfor ha tilstrekkelige arkivstyringsfunksjoner
> til å plassere dem på rett sted, finne dem igjen og skjerme dem mot uautorisert innsyn. Det
> er disse arkivstyringsfunksjonene som beskrives i dette kapitlet, samt forholdet mellom
> arkivstyring og den elektroniske lagring av dokumentene.
> Grunnlaget for arkivstyringen legges ved at systemet fører en logg over slike dokumenter
> når de arkiveres. Loggingen foretas automatisk av systemet når det enkelte dokument
> arkiveres. Denne typen dokumenter omtales derfor i det følgende som loggede
> dokumenter.

Men jeg er litt usikker om PDF'n er offentlig tilgjengelig.
