### ISSUE TITLE
Samkjør katalognavn i forskrift og standard for hvor arkivdokumenter skal plasseres

### ISSUE THREAD

**Issue by petterreinholdtsen** [arkivverket/noark5-tjenestegrensesnitt-standard#88]
Dette er en mangelmelding sendt inn til Arkivverket, se også https://github.com/petterreinholdtsen/noark5-tester/blob/master/mangelmelding/sendt/2019-03-28-noark5-forskrift-katalog.md .

 ------------------  ---------------------------------
           Prosjekt  Noark 5
           Kategori  Versjon 5.0
        Alvorlighet  protest
       Meldingstype  trenger klargjøring 
    Brukerreferanse  pere@hungry.com
        Dokumentdel  krav 6.4.15:
         Sidenummer  98
        Linjenummer  n/a
    Innsendingsdato  2019-03-28
 ------------------  ---------------------------------

Denne teksten er del av en samling innspill til Noark5-standarden tilgjengelig fra [https://github.com/petterreinholdtsen/noark5-tester/](https://github.com/petterreinholdtsen/noark5-tester/).

Beskrivelse
-----------

Det bør beskrives på en entydig og klar måte hvor arkivdokumentfilene skal ligge i en avleveringspakke.  I dag spriker beskrivelsen mellom forskrift, Noark 5-spesifikasjon og praksis.

Følgende står i [Riksarkivarens forskrift), paragraf 5-31 b) og c)](https://lovdata.no/dokument/SF/forskrift/2017-12-19-2286/KAPITTEL_5):

> § 5-31. Organisering av datafiler i avleverings- eller deponeringspakke
>
> (1) Filene som utgjør arkivuttrekket, skal være organisert på følgende måte:
> 
> [...]
> 
> b) For arkivdokumenter skal det opprettes en katalog med navnet
>    DOKUMENT på første nivå under rotkatalogen på vedkommende
>    lagringsenhet. Dokumentfilene skal samles på andre nivå under
>    rotkatalogen og eventuelt struktureres i underkataloger. Dersom
>    et enkelt arkivdokument består av flere filer, skal disse samles
>    i én katalog med et entydig navn. Filformat for arkivdokumenter
>    angis ved filendelse, f.eks. XML, PDF eller TIF.

(Forskriften nevner også katalogen 'RAPPORT', men den finner jeg ikke omtalt i noen Noark 5-standard.)

Katalognavnet 'DOKUMENT' er forskjellig fra det som står i Noark 5 version 3.1 side 97 og Noark 4.0 side 99 (i PDF, mangler sidetall):

> Filene i en avleveringspakke
>
[...]
>
> F) Dokumentfilene. Disse skal ligge i en underkatalog kalt
>    dokumenter.  Denne katalogen kan struktureres i nye
>    underkataloger etter fritt valg, f.eks. en underkatalog for hver
>    måned. Det er ingen krav til navngiving av dokumentfilene, men
>    filenes endelse skal angi arkivformat: pdf, tif, txt osv.

I Noark 5 versjon 5 side 98 står det derimot følgende i krav 6.4.15:

> Dokumentene skal ligge i en underkatalog kalt DOKUMENT. Denne
> katalogen kan struktureres i nye underkataloger etter fritt
> valg. Dokumentfilene endelse skal angi arkivformat: pdf, tif, txt
> osv.

På Noark 5 versjon 5 side 109 i del 6.4.9 (Arkivdokumentene) står det derimot følgende:

> Arkivdokumentene skal lagres i en egen underkatalog i
> avleveringspakken, og denne underkatalogen kan struktureres i nye
> underkataloger etter behov.  Referansen fra arkivstrukturen til
> dokumentfilene vil ligge i dokumentobjektet, dvs. på laveste nivå i
> strukturen. Alle dokumentfiler som det blir referert til i
> arkivstruktur.xml, skal være med i uttrekket.  Dessuten må ikke
> uttrekket inneholde noen dokumentfiler som mangler referanse fra
> dokumentobjektet. Referansen fra arkivstrukturen skal vre relativ
> til dokumentfilene, dvs.  inneholde hele «stien» til dokumentet -
> f.eks. slik: dokumenter/2010/januar/123456789.pdf.

Underkatalogen skal altså enten hete «DOKUMENT» eller «dokumenter» alt etter hvor en leser, men er ikke mulig at en og samme katalog kan hete begge deler samtidig og det er dermed ikke mulig å følge både standard og forskrift samtidig.  Er det noen gode grunner til å bruke store bokstaver i katalognavnene?  Det virker mer fornuftig på meg å bruke
små bokstaver i katalognavn.

Dagens praksis er at katalogen heter «dokumenter», hvilket ikke er overrraskende når det har vært spesifisiert i Noark 3 fra 2013-03-22 og 4 fra 2016-12-01.  Dagens praksis kan for eksempel observeres i testfilene som følger med [Arkivverkets Arkade 5](https://github.com/arkivverket/arkade5/) under src/Arkivverket.Arkade.CLI.Tests/TestData/N5-archive/ og src/Arkivverket.Arkade.Core.Tests/TestData/Noark5/ samt [Documasters Noark Extraction validator samples](https://github.com/documaster/noark-extraction-validator-samples/tree/master/0.2.0/invalid-pdfa/extraction).

Det virker å være minst jobb og lavest kostnader for samfunnet totalt sett å endre forskrift og en av formuleringene i Noark 5 versjon 5 (som kom 2018-12-06) og ingen har implementert så langt, enn å endre alle uttrekkssystem som er laget for Noark 3 og 4, samt verktøy som Arkade 5 som er laget for å verifisere slike uttrekk.

Ønsket endring
--------------

Det viktigste er at det brukes samme katalognavn overalt.  Jeg foreslår å endre Riksarkivarens forskrift og Noark 5-standarden til å bruke katalognavn med små bokstaver, dvs.  «dokumenter» og «rapporter», for å være i tråd med mangeårig innarbeidet praksis med bakgrunn i spesifikasjonen fra Noark 3 og 4.

**Comment by AnnKnu** [comment]
@petterreinholdtsen , på nåværende tidspunkt må vi forholde oss gjeldene lov med forskrifter og gjeldene versjon av Noark standarden.  Protest fjernes, og taes opp igjen høsten 2019

**Comment by petterreinholdtsen** [comment]
@AnnKnu Hva mener du med "vi må forholde oss til gjeldende lov med forskrifter og gjeldende versjon av noark standarden"?  Hva betyr det for valg av katalognavn hvis en avleverer et arkiv elektronisk i tråd med for eksempel Noark 5 versjon 4?

Jeg forstår ikke helt hvorfor du fjerner markøren for alvorlighet fra denne mangelmeldingen.   Den er en referanse til de to nivåene av alvorlighet beskrevet i #14, dvs. 'kommentar' eller 'protest'. Mener du alvorlighetsgrad 'protest' er feil, og skulle vært 'kommentar', eller er det noe annet?  Jeg mener at dagens forskrift og de ulike versjonene av Noark 5 er innbyrdes inkonsistent og at det i mange tilfeller vli være umulig å velge et katalognavn som både følger forskrift og noark-standarden, og at dette må løses før en kan forvente at noen skal kunne "forholde seg til forskrift og standard".  Det er bakgrunnen for at jeg mener denne mangelmeldingen beskriver et problem med høyeste nivå av alvorlighet - "protest".

**Comment by oivkru** [comment]
Det er riktig at det er misforhold her. I Noark 5 frem til og med versjon 4.0 var det et krav som sa at filene skulle ligge i en katalog kalt dokumenter. Dette var i strid med forskriften, hvor det står at katalogen i uttrekk (Noark og ikke-Noark) skal hete DOKUMENT (RAF § 5-31). Testprogrammet har godtatt dette, dvs. det har akseptert både dokumenter og DOKUMENT som katalognavn. Vi endret allikevel kravet (6.4.15) i versjon 5 nettopp for at det skulle være konsistent, samt at forskriften går foran standarden. (Tilfellet på side 109 i standarden ble oversett i denne redigeringen). 

Det er altså DOKUMENT som er korrekt, for det står i forskriften. (Ikke spør hvorfor det er med store bokstaver, det må evt. sjekkes med andre i etaten.) 

Beskrivelsen i mangelmeldingen viser til avleveringspakken, og selve standarden, men ikke til tjenestegrensesnittspesifikasjonen. Betyr det at dette ikke er en feil til tjenestegrensesnittspesifikasjonen?

**Comment by petterreinholdtsen** [comment]
Det stemmer.  Har forsøkt å bruke "Prosjekt  Noark 5" i mangelmeldingens metadata i starten for å markere at dette er en feil i noark 5, ikke tjenestegrensesnittet.  Har brukt "Prosjekt  NOARK 5 Tjenestegresesnitt" for det som gjelder tjenestegrensesnittet.

Problemstillingen er aktuell for min bruk av tjenestegrensesnittet for å hente ut arkivdata for deponering og avlevering, der jeg trenger å vite hvilket katalognavn som skal brukes.

**Comment by petterreinholdtsen** [comment]
Denne mangelmeldingen er flyttet til https://github.com/arkivverket/noark5-standard/issues/51.
