### ISSUE TITLE
Vurder overgang til RST som kildeformat for spesifikasjonen?

### ISSUE THREAD

**Issue by petterreinholdtsen** [arkivverket/noark5-tjenestegrensesnitt-standard#9]
I dag brukes markdown som kildeformat.  Det har begrenset støtte for figurer og tabeller, spesifikt for figur- og tabelltitler.  Bør det vurdres å bytte til et mer rikholding format?  Jeg mistenker formatet RST kan være velegnet.  Jeg har testet overgang til RST og en slik grovmigrering tar ca. 1 time ved hjep av pandoc og litt manuell rydding.  Jeg testet ved å kjøre følgende løkke:

```
cd kapitler; for f in [01]*.md; do \
  pandoc -f markdown_github+table_captions+auto_identifiers+implicit_figures \
    $f -o ${f%.md}-new.rst; git mv $f ${f%.md}.rst; mv ${f%.md}-new.rst ${f%.md}.rst; \
done
```

**Comment by oivkru** [comment]
Arkivverket har ingen formening om dette...

**Comment by petterreinholdtsen** [comment]
Det mer rikholdige "vokabularet i rst har mest konsekvens for PDF-utgaven av dokumentet.  Hvis Arkivverket ikke ser det som vesentlig fremover å lage vakker PDF av standard-dokumentet, så er det liten gevinst i å bytte underlagsformat fra markdown til rst.

**Comment by oivkru** [comment]
Kan du kanskje lage en PDF av md-formatet, så vi ser hvor "lite vakker" den blir? Evt. om jeg kan gjøre det selv, på enkelt vis? (Vi skjønte ikke helt denne betydningen av det som stod over...)

**Comment by petterreinholdtsen** [comment]
Her er dagens markdown typesatt som PDF av pandoc og dblatex.  Jeg laget den ved å sjekke ut git-depotet på en Debian Buster-maskin og kjøre 'make pdf'.

[tjenestegrensesnitt-git-md-20190303.pdf](https://github.com/arkivverket/noark5-tjenestegrensesnitt-standard/files/2922850/tjenestegrensesnitt-git-md-20190303.pdf)

**Comment by petterreinholdtsen** [comment]
Jeg har testet mer rundt overgang til RST, og funnet en automatisk måte som konverterer dagens markdown til rst på en ganske bra måte.  Dere kan se resultatet i https://github.com/petterreinholdtsen/noark5-tjenestegrensesnitt-standard/tree/use-rst-format/kapitler .

Legger ved en PDF laget fra RST-utgaven.  Den største fordelen ses i starten av kapittel 7, der uml-diagrammene har fått mer fornuftig størrelse.  Markdown har ikke mekanisme for å si noe om bildestørrelse, mens RST har et vokabular som tillatter en å si noe om dette.

Hvis vi bestemmer oss for å gå over til RST, så foreslår jeg at konvertingen gjøres etter at de fleste endringsforslagene er tatt inn i markdown-koden, da en overgang nå vil gjøre alle slike patcher ugyldige, da de endrer på tekst som bytter format.

[tjenestegrensesnitt-git-rst-20190404.pdf](https://github.com/arkivverket/noark5-tjenestegrensesnitt-standard/files/3042515/tjenestegrensesnitt-git-rst-20190404.pdf)

**Comment by petterreinholdtsen** [comment]
På dagens møte med Arkivverket ble det bestemt at vi går over til RST.  Jeg planlegger å gjøre det når alle eller de fleste endringsforslag (pull request) som oppdatere markdown-filene er tatt inn i master, for å spare meg arbeidet som trengs for å oppdatere disse etter formatendringen.

**Comment by petterreinholdtsen** [comment]
Mona ga beskjed om at det er best å vente me RST-overgangen til etter at Arkitektum, som går igang over påske, har gjort seg ferdig med sin innsats i løpet av mai.  Dermed lever vi med dagens sideutlegg frem til da.  Omformingen gjøres ved å følge kommandoene i Makefile i git-grenen nevnt over, og tar noen få minutter.

**Comment by monadani** [comment]
Denne er ok, og fungerer bra.

**Comment by petterreinholdtsen** [comment]
I og med at noark5-standard-depoet gjøres i rst, så foreslår jeg at vi også omformer tjenestegrensesnitt-spesifikasjonen til rst. Konkret foreslår jeg at vi tar inn alle endringsforslag som er klare, så omformer til rst og fortsetter utviklingen av spesifikasjonen som rst.  Høres det greit ut for dere andre?

**Comment by petterreinholdtsen** [comment]
Depotet ble endret til RST i dag, fullført i 079be8ef48c2507d11c410f5fc3fb1590f9495fa.  Lukker denne som løst.
