### ISSUE TITLE
Definer måte å hente ut produktinformasjon fra tjenestegrensesnittet

### ISSUE THREAD

**Issue by petterreinholdtsen** [arkivverket/noark5-tjenestegrensesnitt-standard#98]
Dette er en mangelmelding sendt inn til Arkivverket, se også https://github.com/petterreinholdtsen/noark5-tester/blob/master/mangelmelding/sendt/2019-04-01-produktinformasjon.md .

 ------------------  ---------------------------------
           Prosjekt  Noark 5 Tjenestegresesnitt
           Kategori  Versjon 1.0 beta
        Alvorlighet  kommentar
       Meldingstype  utelatt
    Brukerreferanse  pere@hungry.com
        Dokumentdel  6
         Sidenummer  13
        Linjenummer  n/a
    Innsendingsdato  2019-04-01
 ------------------  ---------------------------------

Denne teksten er del av en samling innspill til Noark5-standarden tilgjengelig fra [https://github.com/petterreinholdtsen/noark5-tester/](https://github.com/petterreinholdtsen/noark5-tester/).

Beskrivelse
-----------

Det er nyttig å kunne hente ut informasjon via selve webtjenesten om programvaren som tilbyr tjenestegrensesnittet.  Dette er hensiktsmessig når det skal feilsøkes (vite hvilket produkt og versjon som benyttes hvis oppførselen har endret seg over tid), og også når det skal lages uttrekk med navn på systemet/løsningen (i arkivuttrekk.xml sitt systemName-felt).

Det hadde dermed vært en fordel om det ble definert i spesifikasjonen for tjenestegrensesnittet en relasjon på toppnivå som peker til URL der slik informasjon kan finnes.  Det kan f.eks. returneres et JSON-objekt med aktuelle attributter.

Det kan være en sikkerhetsmessig utfordring å dele ut versjon og versjonsdato offentlig, når det er sikkerhetsproblemer med en gitt API-implementasjon.  Det bør derfor vurderes om slik produktinformasjon kun skal være tilgjengelig for innloggede brukere.

Det bør videre vurderes om en skal støtte flere protokollversjoner (dvs. en liste med strenger i stedet for en streng), jamfør diskusjonen i [mangelmelding #71](https://github.com/arkivverket/noark5-tjenestegrensesnitt-standard/issues/71) om hvordan en skal håndtere ikke-kompatible endringer i API-spesifikasjonen

Ønsket endring
--------------

Legg inn ny relasjon/href i det som returneres fra toppnivå, dvs del 6.1.1.1 (Oppkobling og ressurslenker), med relasjonsnøkkel `http://rel.kxml.no/noark5/v4/api/admin/system/`.

Legg inn følgende del foran del 6.1.1.2 (Finne objekter (Read)) på side 13:

> #### Systeminformasjon
> 
> Når en tar GET mot href for relasjonsnøkkelen
> `http://rel.arkivverket.no/noark5/v4/api/admin/system/`, så får en informasjon
> om API-tjenersystemet.  Responsen inneholder følgende felter:
> 
>  * `leverandoer` - tekststreng med navn på leverandør av
>                tjenestegrensesnittimplementasjonen.
>  * `produkt` - tekststreng med navn på produktet som leverer
>                tjenestegrensesnittet.
>  * `versjon` - tekststreng med versjon for produktet fra leverandøren.
>  * `versjonsdato` - tekststreng med dato for når produktet ble lansert
>                / programmet ble sist oppdatert.
>  * `protokollversjon` - tekststreng med versjon av
>                tjenestegrensesnittspesifikasjonen som støttes.
>                For dagens utgave vil verdien være '1.0 beta'.
> 
> Responsen kan for eksempel se slik ut:
> 
> ```Python
> {
>   "leverandoer": "Hoffleverandøren",
>   "produkt": "Arkivsystemet Noark 5 kjerne",
>   "versjon": "0.1",
>   "versjonsdato": "2019-03-22",
>   "protokollversjon": "1.0 Beta"
> }
> ```
> 
> Det kan være en sikkerhetsmessig fordel å unngå å fortelle
> potensielle angripere hvilken versjon som kjører på maskinen.  Det
> kan derfor være lurt å kun gjøre dette endepunktet tilgjengelig for
> innloggede brukere.

**Comment by tsodring** [comment]
Det som er litt interessant her Petter er at noe av det du peker på trengs for info.xml og arkivuttrekk.xml. Feks ta info.xml 

_For info.xml_

```
<system systemType="Noark 5" versjon="4.0">
  <systemNavn>Arkivsystemet Noark 5 kjerne</systemNavn>
  <versjon>0.1</versjon>
</system>
```

_For arkivuttrekk.xml_
```
 <additionalElement name="systemType">
    <value>Arkivsystemet Noark 5 kjerne</value>
  </additionalElement>
  <additionalElement name="systemName">
    <value>0.1</value>
  </additionalElement>
```

**Comment by petterreinholdtsen** [comment]
Er system.systemNavn i info.xml en redundant kopi av systemType i arkivuttrekk.xml, eller er det tilfeldigvis samme innhold i begge?  Tilsvarende for system.versjon og systemName?  Jeg skal justere forslaget til å sikre at disse verdiene er tilgjengelig via API-et, slik at jeg kan lage et eksportscript som henter ut deponi-XML via API-et som kan bruke disse verdiene.

**Comment by tsodring** [comment]
Prøvde å tenke litt på. Uanset, hvis disse ikke er definert i metadakatalogen så burde de vel bli spesifisert der ....

**Comment by petterreinholdtsen** [comment]
Hvor er innholdet i info.xml og arkivuttrekk.xml definert?  Jeg klarer bare finne noen eksempler, men ingen spesifikasjon.

Fant et [eksempel på arkivuttrekk.xml på Arkivverkets sider](https://www.arkivverket.no/forvaltning-og-utvikling/noark-standarden/noark-5/noark5-standarden/_/attachment/download/3028497f-7100-48c0-aa6d-ae0c9d37d996:41ecc8d6566c9f37aa92a4701c6869c72bae9861/Noark5v4%20vedl5%20Eksempel%20p%C3%A5%20arkivuttrekk_xml.pdf), men det forklarer ikke om det er samme informasjon i begge filene.

**Comment by monadani** [comment]
27/06/2019 Fornuftig å ta dette med i versjon 1.0, ser videre på tematikken i versjon 2.0
